# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'conjunctionwidget.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_conjunctionwidget(object):
    def setupUi(self, conjunctionwidget):
        conjunctionwidget.setObjectName(_fromUtf8("conjunctionwidget"))
        conjunctionwidget.resize(400, 700)
        conjunctionwidget.setMinimumSize(QtCore.QSize(300, 500))
        conjunctionwidget.setMaximumSize(QtCore.QSize(600, 1000))
        self.verticalLayout_2 = QtGui.QVBoxLayout(conjunctionwidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.data_treewidget = QtGui.QTreeWidget(conjunctionwidget)
        self.data_treewidget.setObjectName(_fromUtf8("data_treewidget"))
        self.gridLayout.addWidget(self.data_treewidget, 4, 0, 1, 4)
        self.kstep_spinbox = QtGui.QSpinBox(conjunctionwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.kstep_spinbox.sizePolicy().hasHeightForWidth())
        self.kstep_spinbox.setSizePolicy(sizePolicy)
        self.kstep_spinbox.setMinimum(1)
        self.kstep_spinbox.setMaximum(99999)
        self.kstep_spinbox.setObjectName(_fromUtf8("kstep_spinbox"))
        self.gridLayout.addWidget(self.kstep_spinbox, 0, 1, 1, 1)
        self.groupBox = QtGui.QGroupBox(conjunctionwidget)
        self.groupBox.setEnabled(False)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(True)
        self.groupBox.setChecked(False)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.dec_d_spinbox = QtGui.QSpinBox(self.groupBox)
        self.dec_d_spinbox.setMinimum(-90)
        self.dec_d_spinbox.setMaximum(90)
        self.dec_d_spinbox.setObjectName(_fromUtf8("dec_d_spinbox"))
        self.gridLayout_2.addWidget(self.dec_d_spinbox, 3, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 0, 3, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.label_9, 2, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 0, 1, 1, 1)
        self.ra_m_spinbox = QtGui.QSpinBox(self.groupBox)
        self.ra_m_spinbox.setMaximum(59)
        self.ra_m_spinbox.setObjectName(_fromUtf8("ra_m_spinbox"))
        self.gridLayout_2.addWidget(self.ra_m_spinbox, 1, 2, 1, 1)
        self.ra_s_spinbox = QtGui.QSpinBox(self.groupBox)
        self.ra_s_spinbox.setMaximum(59)
        self.ra_s_spinbox.setObjectName(_fromUtf8("ra_s_spinbox"))
        self.gridLayout_2.addWidget(self.ra_s_spinbox, 1, 3, 1, 1)
        self.ra_h_spinbox = QtGui.QSpinBox(self.groupBox)
        self.ra_h_spinbox.setMaximum(23)
        self.ra_h_spinbox.setObjectName(_fromUtf8("ra_h_spinbox"))
        self.gridLayout_2.addWidget(self.ra_h_spinbox, 1, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 2, 2, 1, 1)
        self.dec_m_spinbox = QtGui.QSpinBox(self.groupBox)
        self.dec_m_spinbox.setMaximum(59)
        self.dec_m_spinbox.setObjectName(_fromUtf8("dec_m_spinbox"))
        self.gridLayout_2.addWidget(self.dec_m_spinbox, 3, 2, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 0, 2, 1, 1)
        self.dec_s_spinbox = QtGui.QSpinBox(self.groupBox)
        self.dec_s_spinbox.setMaximum(59)
        self.dec_s_spinbox.setObjectName(_fromUtf8("dec_s_spinbox"))
        self.gridLayout_2.addWidget(self.dec_s_spinbox, 3, 3, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_2.addWidget(self.label_8, 2, 3, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 3, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.gridLayout.addWidget(self.groupBox, 2, 0, 1, 4)
        self.export_btn = QtGui.QPushButton(conjunctionwidget)
        self.export_btn.setObjectName(_fromUtf8("export_btn"))
        self.gridLayout.addWidget(self.export_btn, 0, 2, 1, 1)
        self.compute_btn = QtGui.QPushButton(conjunctionwidget)
        self.compute_btn.setObjectName(_fromUtf8("compute_btn"))
        self.gridLayout.addWidget(self.compute_btn, 0, 3, 1, 1)
        self.line = QtGui.QFrame(conjunctionwidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 1, 0, 1, 4)
        self.label = QtGui.QLabel(conjunctionwidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.line_2 = QtGui.QFrame(conjunctionwidget)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout.addWidget(self.line_2, 3, 0, 1, 4)
        self.verticalLayout_2.addLayout(self.gridLayout)

        self.retranslateUi(conjunctionwidget)
        QtCore.QMetaObject.connectSlotsByName(conjunctionwidget)

    def retranslateUi(self, conjunctionwidget):
        conjunctionwidget.setWindowTitle(_translate("conjunctionwidget", "Compute Conjunction Times", None))
        self.data_treewidget.headerItem().setText(0, _translate("conjunctionwidget", "HJD", None))
        self.data_treewidget.headerItem().setText(1, _translate("conjunctionwidget", "Min Type", None))
        self.groupBox.setTitle(_translate("conjunctionwidget", "Compute UTC", None))
        self.label_6.setText(_translate("conjunctionwidget", "Second", None))
        self.label_9.setText(_translate("conjunctionwidget", "°", None))
        self.label_4.setText(_translate("conjunctionwidget", "Hour", None))
        self.label_7.setText(_translate("conjunctionwidget", "\'", None))
        self.label_5.setText(_translate("conjunctionwidget", "Minute", None))
        self.label_8.setText(_translate("conjunctionwidget", "\"", None))
        self.label_2.setText(_translate("conjunctionwidget", "Right Ascension", None))
        self.label_3.setText(_translate("conjunctionwidget", "Declination", None))
        self.export_btn.setText(_translate("conjunctionwidget", "Export", None))
        self.compute_btn.setText(_translate("conjunctionwidget", "Compute", None))
        self.label.setToolTip(_translate("conjunctionwidget", "Space conjunction times by a whole orbit cycles per minima [KTSTEP]", None))
        self.label.setText(_translate("conjunctionwidget", "Cycle Step", None))

