# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'curvepropertiesdialog.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_CurvePropertiesDialog(object):
    def setupUi(self, CurvePropertiesDialog):
        CurvePropertiesDialog.setObjectName(_fromUtf8("CurvePropertiesDialog"))
        CurvePropertiesDialog.resize(640, 520)
        CurvePropertiesDialog.setMinimumSize(QtCore.QSize(640, 520))
        CurvePropertiesDialog.setMaximumSize(QtCore.QSize(640, 520))
        self.accept_btn = QtGui.QPushButton(CurvePropertiesDialog)
        self.accept_btn.setGeometry(QtCore.QRect(10, 460, 305, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.accept_btn.setFont(font)
        self.accept_btn.setObjectName(_fromUtf8("accept_btn"))
        self.datawidget = QtGui.QTreeWidget(CurvePropertiesDialog)
        self.datawidget.setGeometry(QtCore.QRect(325, 100, 305, 301))
        self.datawidget.setObjectName(_fromUtf8("datawidget"))
        self.label = QtGui.QLabel(CurvePropertiesDialog)
        self.label.setGeometry(QtCore.QRect(325, 50, 161, 20))
        self.label.setObjectName(_fromUtf8("label"))
        self.filepath_label = QtGui.QLabel(CurvePropertiesDialog)
        self.filepath_label.setGeometry(QtCore.QRect(325, 72, 301, 20))
        self.filepath_label.setObjectName(_fromUtf8("filepath_label"))
        self.discard_btn = QtGui.QPushButton(CurvePropertiesDialog)
        self.discard_btn.setGeometry(QtCore.QRect(325, 460, 305, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.discard_btn.setFont(font)
        self.discard_btn.setObjectName(_fromUtf8("discard_btn"))
        self.band_box = QtGui.QSpinBox(CurvePropertiesDialog)
        self.band_box.setGeometry(QtCore.QRect(60, 60, 31, 20))
        self.band_box.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.band_box.setMinimum(1)
        self.band_box.setMaximum(94)
        self.band_box.setProperty("value", 7)
        self.band_box.setObjectName(_fromUtf8("band_box"))
        self.label_2 = QtGui.QLabel(CurvePropertiesDialog)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 51, 20))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.l1_ipt = QtGui.QLineEdit(CurvePropertiesDialog)
        self.l1_ipt.setGeometry(QtCore.QRect(10, 110, 145, 25))
        self.l1_ipt.setObjectName(_fromUtf8("l1_ipt"))
        self.label_3 = QtGui.QLabel(CurvePropertiesDialog)
        self.label_3.setGeometry(QtCore.QRect(10, 90, 16, 20))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(CurvePropertiesDialog)
        self.label_4.setGeometry(QtCore.QRect(170, 90, 16, 20))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.l2_ipt = QtGui.QLineEdit(CurvePropertiesDialog)
        self.l2_ipt.setGeometry(QtCore.QRect(170, 110, 145, 25))
        self.l2_ipt.setObjectName(_fromUtf8("l2_ipt"))
        self.x2_ipt = QtGui.QLineEdit(CurvePropertiesDialog)
        self.x2_ipt.setGeometry(QtCore.QRect(170, 160, 145, 25))
        self.x2_ipt.setObjectName(_fromUtf8("x2_ipt"))
        self.label_5 = QtGui.QLabel(CurvePropertiesDialog)
        self.label_5.setGeometry(QtCore.QRect(10, 140, 16, 20))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.x1_ipt = QtGui.QLineEdit(CurvePropertiesDialog)
        self.x1_ipt.setGeometry(QtCore.QRect(10, 160, 145, 25))
        self.x1_ipt.setObjectName(_fromUtf8("x1_ipt"))
        self.label_6 = QtGui.QLabel(CurvePropertiesDialog)
        self.label_6.setGeometry(QtCore.QRect(170, 140, 16, 20))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(CurvePropertiesDialog)
        self.label_7.setGeometry(QtCore.QRect(10, 190, 16, 20))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.y2_ipt = QtGui.QLineEdit(CurvePropertiesDialog)
        self.y2_ipt.setGeometry(QtCore.QRect(170, 210, 145, 25))
        self.y2_ipt.setObjectName(_fromUtf8("y2_ipt"))
        self.label_8 = QtGui.QLabel(CurvePropertiesDialog)
        self.label_8.setGeometry(QtCore.QRect(170, 190, 16, 20))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.y1_ipt = QtGui.QLineEdit(CurvePropertiesDialog)
        self.y1_ipt.setGeometry(QtCore.QRect(10, 210, 145, 25))
        self.y1_ipt.setObjectName(_fromUtf8("y1_ipt"))
        self.label_9 = QtGui.QLabel(CurvePropertiesDialog)
        self.label_9.setGeometry(QtCore.QRect(10, 303, 41, 20))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.opsf_ipt = QtGui.QLineEdit(CurvePropertiesDialog)
        self.opsf_ipt.setGeometry(QtCore.QRect(10, 377, 140, 25))
        self.opsf_ipt.setObjectName(_fromUtf8("opsf_ipt"))
        self.label_10 = QtGui.QLabel(CurvePropertiesDialog)
        self.label_10.setGeometry(QtCore.QRect(10, 357, 41, 20))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.el3a_ipt = QtGui.QLineEdit(CurvePropertiesDialog)
        self.el3a_ipt.setGeometry(QtCore.QRect(10, 323, 140, 25))
        self.el3a_ipt.setObjectName(_fromUtf8("el3a_ipt"))
        self.label_11 = QtGui.QLabel(CurvePropertiesDialog)
        self.label_11.setGeometry(QtCore.QRect(170, 303, 51, 20))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.sigma_ipt = QtGui.QLineEdit(CurvePropertiesDialog)
        self.sigma_ipt.setGeometry(QtCore.QRect(170, 323, 145, 25))
        self.sigma_ipt.setObjectName(_fromUtf8("sigma_ipt"))
        self.e3_ipt = QtGui.QLineEdit(CurvePropertiesDialog)
        self.e3_ipt.setGeometry(QtCore.QRect(170, 260, 64, 25))
        self.e3_ipt.setObjectName(_fromUtf8("e3_ipt"))
        self.label_12 = QtGui.QLabel(CurvePropertiesDialog)
        self.label_12.setGeometry(QtCore.QRect(10, 240, 16, 20))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtGui.QLabel(CurvePropertiesDialog)
        self.label_13.setGeometry(QtCore.QRect(250, 240, 16, 20))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(CurvePropertiesDialog)
        self.label_14.setGeometry(QtCore.QRect(170, 240, 16, 20))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.e2_ipt = QtGui.QLineEdit(CurvePropertiesDialog)
        self.e2_ipt.setGeometry(QtCore.QRect(90, 260, 64, 25))
        self.e2_ipt.setObjectName(_fromUtf8("e2_ipt"))
        self.e4_ipt = QtGui.QLineEdit(CurvePropertiesDialog)
        self.e4_ipt.setGeometry(QtCore.QRect(250, 260, 64, 25))
        self.e4_ipt.setObjectName(_fromUtf8("e4_ipt"))
        self.label_15 = QtGui.QLabel(CurvePropertiesDialog)
        self.label_15.setGeometry(QtCore.QRect(90, 240, 16, 20))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.e1_ipt = QtGui.QLineEdit(CurvePropertiesDialog)
        self.e1_ipt.setGeometry(QtCore.QRect(10, 260, 64, 25))
        self.e1_ipt.setObjectName(_fromUtf8("e1_ipt"))
        self.line = QtGui.QFrame(CurvePropertiesDialog)
        self.line.setGeometry(QtCore.QRect(10, 287, 301, 21))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.ksd_box = QtGui.QSpinBox(CurvePropertiesDialog)
        self.ksd_box.setGeometry(QtCore.QRect(200, 59, 51, 22))
        self.ksd_box.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.ksd_box.setMinimum(1)
        self.ksd_box.setMaximum(3)
        self.ksd_box.setProperty("value", 1)
        self.ksd_box.setObjectName(_fromUtf8("ksd_box"))
        self.label_16 = QtGui.QLabel(CurvePropertiesDialog)
        self.label_16.setGeometry(QtCore.QRect(170, 60, 41, 20))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_17 = QtGui.QLabel(CurvePropertiesDialog)
        self.label_17.setGeometry(QtCore.QRect(170, 357, 51, 21))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.line_12 = QtGui.QFrame(CurvePropertiesDialog)
        self.line_12.setGeometry(QtCore.QRect(10, 30, 621, 21))
        self.line_12.setFrameShape(QtGui.QFrame.HLine)
        self.line_12.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_12.setObjectName(_fromUtf8("line_12"))
        self.label_53 = QtGui.QLabel(CurvePropertiesDialog)
        self.label_53.setGeometry(QtCore.QRect(10, 10, 381, 31))
        self.label_53.setObjectName(_fromUtf8("label_53"))
        self.line_2 = QtGui.QFrame(CurvePropertiesDialog)
        self.line_2.setGeometry(QtCore.QRect(305, 50, 30, 351))
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.whatsthis_btn = QtGui.QPushButton(CurvePropertiesDialog)
        self.whatsthis_btn.setGeometry(QtCore.QRect(275, 50, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.whatsthis_btn.setFont(font)
        self.whatsthis_btn.setObjectName(_fromUtf8("whatsthis_btn"))
        self.noise_combobox = QtGui.QComboBox(CurvePropertiesDialog)
        self.noise_combobox.setGeometry(QtCore.QRect(170, 377, 145, 25))
        self.noise_combobox.setObjectName(_fromUtf8("noise_combobox"))
        self.noise_combobox.addItem(_fromUtf8(""))
        self.noise_combobox.addItem(_fromUtf8(""))
        self.noise_combobox.addItem(_fromUtf8(""))
        self.label_18 = QtGui.QLabel(CurvePropertiesDialog)
        self.label_18.setGeometry(QtCore.QRect(170, 410, 81, 20))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.wla_ipt = QtGui.QLineEdit(CurvePropertiesDialog)
        self.wla_ipt.setGeometry(QtCore.QRect(10, 430, 145, 25))
        self.wla_ipt.setObjectName(_fromUtf8("wla_ipt"))
        self.aextinc_ipt = QtGui.QLineEdit(CurvePropertiesDialog)
        self.aextinc_ipt.setGeometry(QtCore.QRect(170, 430, 145, 25))
        self.aextinc_ipt.setWhatsThis(_fromUtf8(""))
        self.aextinc_ipt.setObjectName(_fromUtf8("aextinc_ipt"))
        self.label_19 = QtGui.QLabel(CurvePropertiesDialog)
        self.label_19.setGeometry(QtCore.QRect(10, 410, 41, 20))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.label_20 = QtGui.QLabel(CurvePropertiesDialog)
        self.label_20.setGeometry(QtCore.QRect(485, 410, 61, 20))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.xunit_ipt = QtGui.QLineEdit(CurvePropertiesDialog)
        self.xunit_ipt.setGeometry(QtCore.QRect(325, 430, 145, 25))
        self.xunit_ipt.setObjectName(_fromUtf8("xunit_ipt"))
        self.calib_ipt = QtGui.QLineEdit(CurvePropertiesDialog)
        self.calib_ipt.setGeometry(QtCore.QRect(485, 430, 145, 25))
        self.calib_ipt.setObjectName(_fromUtf8("calib_ipt"))
        self.label_21 = QtGui.QLabel(CurvePropertiesDialog)
        self.label_21.setGeometry(QtCore.QRect(325, 410, 111, 20))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.line_3 = QtGui.QFrame(CurvePropertiesDialog)
        self.line_3.setGeometry(QtCore.QRect(305, 460, 30, 51))
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))

        self.retranslateUi(CurvePropertiesDialog)
        self.noise_combobox.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(CurvePropertiesDialog)

    def retranslateUi(self, CurvePropertiesDialog):
        CurvePropertiesDialog.setWindowTitle(_translate("CurvePropertiesDialog", "Curve Properties", None))
        self.accept_btn.setText(_translate("CurvePropertiesDialog", "Accept", None))
        self.datawidget.headerItem().setText(0, _translate("CurvePropertiesDialog", "Time/Phase", None))
        self.datawidget.headerItem().setText(1, _translate("CurvePropertiesDialog", "Observation", None))
        self.datawidget.headerItem().setText(2, _translate("CurvePropertiesDialog", "Weight", None))
        self.label.setText(_translate("CurvePropertiesDialog", "Data Preview of file:", None))
        self.filepath_label.setText(_translate("CurvePropertiesDialog", "FILEPATH//////////////////////////////////", None))
        self.discard_btn.setText(_translate("CurvePropertiesDialog", "Discard", None))
        self.label_2.setToolTip(_translate("CurvePropertiesDialog", "Band identification number. Check [Bandpass List] table for all available bands and their respective #\'s", None))
        self.label_2.setText(_translate("CurvePropertiesDialog", "Band #", None))
        self.l1_ipt.setText(_translate("CurvePropertiesDialog", "0", None))
        self.label_3.setToolTip(_translate("CurvePropertiesDialog", "Bandpass luminosity for star 1 [HLA]", None))
        self.label_3.setText(_translate("CurvePropertiesDialog", "L1", None))
        self.label_4.setToolTip(_translate("CurvePropertiesDialog", "Bandpass luminosity for star 2 [CLA]", None))
        self.label_4.setText(_translate("CurvePropertiesDialog", "L2", None))
        self.l2_ipt.setText(_translate("CurvePropertiesDialog", "0", None))
        self.x2_ipt.setText(_translate("CurvePropertiesDialog", "0", None))
        self.label_5.setToolTip(_translate("CurvePropertiesDialog", "Wavelength-specific limb darkening coefficient in linear term, for star 1 [X1A] ", None))
        self.label_5.setText(_translate("CurvePropertiesDialog", "X1", None))
        self.x1_ipt.setText(_translate("CurvePropertiesDialog", "0", None))
        self.label_6.setToolTip(_translate("CurvePropertiesDialog", "Wavelength-specific limb darkening coefficient in linear term, for star 2 [X2A] ", None))
        self.label_6.setText(_translate("CurvePropertiesDialog", "X2", None))
        self.label_7.setToolTip(_translate("CurvePropertiesDialog", "Bandpass-specific limb darkening coefficient in non-linear term, for star 1 [Y1A] ", None))
        self.label_7.setText(_translate("CurvePropertiesDialog", "Y1", None))
        self.y2_ipt.setText(_translate("CurvePropertiesDialog", "0", None))
        self.label_8.setToolTip(_translate("CurvePropertiesDialog", "Bandpass-specific limb darkening coefficient in non-linear term, for star 2 [Y2A] ", None))
        self.label_8.setText(_translate("CurvePropertiesDialog", "Y2", None))
        self.y1_ipt.setText(_translate("CurvePropertiesDialog", "0", None))
        self.label_9.setToolTip(_translate("CurvePropertiesDialog", "Third light", None))
        self.label_9.setText(_translate("CurvePropertiesDialog", "EL3A", None))
        self.opsf_ipt.setText(_translate("CurvePropertiesDialog", "0", None))
        self.label_10.setToolTip(_translate("CurvePropertiesDialog", "Opacity, attenuation of star light by circumstellar matter", None))
        self.label_10.setText(_translate("CurvePropertiesDialog", "OPSF", None))
        self.el3a_ipt.setText(_translate("CurvePropertiesDialog", "0", None))
        self.label_11.setToolTip(_translate("CurvePropertiesDialog", "Estimated standard deviation of observed light", None))
        self.label_11.setText(_translate("CurvePropertiesDialog", "SIGMA", None))
        self.sigma_ipt.setText(_translate("CurvePropertiesDialog", "0", None))
        self.e3_ipt.setText(_translate("CurvePropertiesDialog", "0", None))
        self.label_12.setToolTip(_translate("CurvePropertiesDialog", "Phase 1", None))
        self.label_12.setText(_translate("CurvePropertiesDialog", "E1", None))
        self.label_13.setToolTip(_translate("CurvePropertiesDialog", "Phase 4", None))
        self.label_13.setText(_translate("CurvePropertiesDialog", "E4", None))
        self.label_14.setToolTip(_translate("CurvePropertiesDialog", "Phase 3", None))
        self.label_14.setText(_translate("CurvePropertiesDialog", "E3", None))
        self.e2_ipt.setText(_translate("CurvePropertiesDialog", "0", None))
        self.e4_ipt.setText(_translate("CurvePropertiesDialog", "0", None))
        self.label_15.setToolTip(_translate("CurvePropertiesDialog", "Phase 2", None))
        self.label_15.setText(_translate("CurvePropertiesDialog", "E2", None))
        self.e1_ipt.setText(_translate("CurvePropertiesDialog", "0", None))
        self.label_16.setToolTip(_translate("CurvePropertiesDialog", "Set standard deviation apply method. [?]", None))
        self.label_16.setWhatsThis(_translate("CurvePropertiesDialog", "<html><head/><body><p>An integer array that is 0, 1, or 2 for each input sub-dataset (velocity, light, or eclipse timings). </p><p>The KSDs tell DC whether to apply the input standard deviations (σ’s) to compute curvedependent weights (KSD=0), </p><p>to apply DC’s internally computed σ’s for the weights (KSD=1),</p><p>or to apply σ’s based on one or two restricted phase ranges for the weights (KSD=2).</p><p><span style=\" font-weight:600;\">If unsure, set to 1.</span></p></body></html>", None))
        self.label_16.setText(_translate("CurvePropertiesDialog", "KSD", None))
        self.label_17.setToolTip(_translate("CurvePropertiesDialog", "Set how observational scatter scales with the light level. [?]", None))
        self.label_17.setWhatsThis(_translate("CurvePropertiesDialog", "<html><head/><body><p><span style=\" font-weight:600;\">NOISE</span> should be set to 1 for scatter that scales with the square root of the light level, such as counting statistics, and to 2 for scatter that scales with the light level, such as scintillation noise or fluctuations in sky transparency. If <span style=\" font-weight:600;\">NOISE</span> is set to 0, no level-dependent weighting is applied. </p><p>As a side note, level-dependent weighting does not apply to velocity curves.</p></body></html>", None))
        self.label_17.setText(_translate("CurvePropertiesDialog", "NOISE", None))
        self.label_53.setText(_translate("CurvePropertiesDialog", "TITLE/////////////////", None))
        self.whatsthis_btn.setText(_translate("CurvePropertiesDialog", "?", None))
        self.noise_combobox.setItemText(0, _translate("CurvePropertiesDialog", "None", None))
        self.noise_combobox.setItemText(1, _translate("CurvePropertiesDialog", "Square Root", None))
        self.noise_combobox.setItemText(2, _translate("CurvePropertiesDialog", "Linear", None))
        self.label_18.setToolTip(_translate("CurvePropertiesDialog", "Interstellar extinction in magnitude in the designated [LINKEXT] photometric band. [?]", None))
        self.label_18.setWhatsThis(_translate("CurvePropertiesDialog", "<html><head/><body><p>AEXTINC refers to a definite photometric band (the band designated by control integer LINKEXT), so it has only one value and it is not band-dependent.</p></body></html>", None))
        self.label_18.setText(_translate("CurvePropertiesDialog", "AEXTINC", None))
        self.wla_ipt.setText(_translate("CurvePropertiesDialog", "0", None))
        self.aextinc_ipt.setText(_translate("CurvePropertiesDialog", "0", None))
        self.label_19.setToolTip(_translate("CurvePropertiesDialog", "<html><head/><body><p>Observational wavelenght in microns. </p><p>Wavelengths are no longer used for light curves, which are based on integrated bandpass radiation since the 2003 revision.</p><p>They are still entered for use as reference wavelengths for line profiles and for opacity computations in circumstellar attenuation.</p></body></html>", None))
        self.label_19.setText(_translate("CurvePropertiesDialog", "WLA", None))
        self.label_20.setToolTip(_translate("CurvePropertiesDialog", "Flux calibration constant in erg s −1 cm −3 for a star of magnitude 0.00.  ", None))
        self.label_20.setText(_translate("CurvePropertiesDialog", "CALIB", None))
        self.xunit_ipt.setText(_translate("CurvePropertiesDialog", "1.0000", None))
        self.calib_ipt.setText(_translate("CurvePropertiesDialog", "0", None))
        self.label_21.setToolTip(_translate("CurvePropertiesDialog", "The multiplier that restores the flux numbers to directly inverted magnitudes. [?]", None))
        self.label_21.setWhatsThis(_translate("CurvePropertiesDialog", "<html><head/><body><p>This quantity is intended only for flux (as opposed to magnitude) input, and allows rescaling of observed fluxes so that the input flux numbers can be in a convenient range. If input fluxes are simply inverted magnitudes (e.g. 10<span style=\" vertical-align:super;\">−0.4V</span> for V magnitudes), then XUNIT should be unity. However, it may be convenient to enter rescaled (i.e. wrongly scaled) fluxes in cases where they would otherwise be of order, say, 10<span style=\" vertical-align:super;\">−10</span> or 10<span style=\" vertical-align:super;\">3</span> . Then XUNIT can be the multiplier that restores the flux numbers to directly inverted magnitudes. If working in (presumably standard) magnitudes with control integer MAGLITE=1, of course, then don’t worry about XUNIT—just set it to 1.0000.</p></body></html>", None))
        self.label_21.setText(_translate("CurvePropertiesDialog", "XUNIT", None))

