# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dcwidget.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DCWidget(object):
    def setupUi(self, DCWidget):
        DCWidget.setObjectName(_fromUtf8("DCWidget"))
        DCWidget.resize(1100, 600)
        self.horizontalLayout_8 = QtGui.QHBoxLayout(DCWidget)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_8 = QtGui.QLabel(DCWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMaximumSize(QtCore.QSize(150, 16777215))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 0, 0, 2, 1)
        self.line_9 = QtGui.QFrame(DCWidget)
        self.line_9.setFrameShape(QtGui.QFrame.VLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName(_fromUtf8("line_9"))
        self.gridLayout.addWidget(self.line_9, 0, 5, 2, 1)
        self.exportresults_btn = QtGui.QPushButton(DCWidget)
        self.exportresults_btn.setObjectName(_fromUtf8("exportresults_btn"))
        self.gridLayout.addWidget(self.exportresults_btn, 1, 4, 1, 1)
        self.updateinputs_btn = QtGui.QPushButton(DCWidget)
        self.updateinputs_btn.setObjectName(_fromUtf8("updateinputs_btn"))
        self.gridLayout.addWidget(self.updateinputs_btn, 0, 4, 1, 1)
        self.rundc2015_btn = QtGui.QPushButton(DCWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rundc2015_btn.sizePolicy().hasHeightForWidth())
        self.rundc2015_btn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.rundc2015_btn.setFont(font)
        self.rundc2015_btn.setObjectName(_fromUtf8("rundc2015_btn"))
        self.gridLayout.addWidget(self.rundc2015_btn, 0, 2, 2, 1)
        self.viewlastdcin_btn = QtGui.QPushButton(DCWidget)
        self.viewlastdcin_btn.setObjectName(_fromUtf8("viewlastdcin_btn"))
        self.gridLayout.addWidget(self.viewlastdcin_btn, 0, 6, 1, 1)
        self.iteration_spinbox = QtGui.QSpinBox(DCWidget)
        self.iteration_spinbox.setMaximumSize(QtCore.QSize(50, 16777215))
        self.iteration_spinbox.setMinimum(1)
        self.iteration_spinbox.setObjectName(_fromUtf8("iteration_spinbox"))
        self.gridLayout.addWidget(self.iteration_spinbox, 0, 1, 2, 1)
        self.line_2 = QtGui.QFrame(DCWidget)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout.addWidget(self.line_2, 0, 3, 2, 1)
        self.viewlaastdcout_btn = QtGui.QPushButton(DCWidget)
        self.viewlaastdcout_btn.setObjectName(_fromUtf8("viewlaastdcout_btn"))
        self.gridLayout.addWidget(self.viewlaastdcout_btn, 1, 6, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.line_10 = QtGui.QFrame(DCWidget)
        self.line_10.setFrameShape(QtGui.QFrame.HLine)
        self.line_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_10.setObjectName(_fromUtf8("line_10"))
        self.verticalLayout_2.addWidget(self.line_10)
        self.tabWidget_2 = QtGui.QTabWidget(DCWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget_2.sizePolicy().hasHeightForWidth())
        self.tabWidget_2.setSizePolicy(sizePolicy)
        self.tabWidget_2.setMinimumSize(QtCore.QSize(500, 200))
        self.tabWidget_2.setMaximumSize(QtCore.QSize(850, 250))
        self.tabWidget_2.setTabPosition(QtGui.QTabWidget.West)
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.tab_5)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.tabWidget_3 = QtGui.QTabWidget(self.tab_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget_3.sizePolicy().hasHeightForWidth())
        self.tabWidget_3.setSizePolicy(sizePolicy)
        self.tabWidget_3.setObjectName(_fromUtf8("tabWidget_3"))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.tab_2)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setHorizontalSpacing(2)
        self.gridLayout_2.setVerticalSpacing(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.f1_chk = QtGui.QCheckBox(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.f1_chk.setFont(font)
        self.f1_chk.setObjectName(_fromUtf8("f1_chk"))
        self.gridLayout_2.addWidget(self.f1_chk, 3, 0, 1, 1)
        self.s1lat_chk = QtGui.QCheckBox(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.s1lat_chk.setFont(font)
        self.s1lat_chk.setObjectName(_fromUtf8("s1lat_chk"))
        self.gridLayout_2.addWidget(self.s1lat_chk, 5, 0, 1, 1)
        self.tc3b_chk = QtGui.QCheckBox(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tc3b_chk.setFont(font)
        self.tc3b_chk.setObjectName(_fromUtf8("tc3b_chk"))
        self.gridLayout_2.addWidget(self.tc3b_chk, 4, 4, 1, 1)
        self.q_chk = QtGui.QCheckBox(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.q_chk.setFont(font)
        self.q_chk.setObjectName(_fromUtf8("q_chk"))
        self.gridLayout_2.addWidget(self.q_chk, 1, 3, 1, 1)
        self.p3b_chk = QtGui.QCheckBox(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.p3b_chk.setFont(font)
        self.p3b_chk.setObjectName(_fromUtf8("p3b_chk"))
        self.gridLayout_2.addWidget(self.p3b_chk, 4, 1, 1, 1)
        self.alb2_chk = QtGui.QCheckBox(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.alb2_chk.setFont(font)
        self.alb2_chk.setObjectName(_fromUtf8("alb2_chk"))
        self.gridLayout_2.addWidget(self.alb2_chk, 2, 5, 1, 1)
        self.incl_chk = QtGui.QCheckBox(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.incl_chk.setFont(font)
        self.incl_chk.setObjectName(_fromUtf8("incl_chk"))
        self.gridLayout_2.addWidget(self.incl_chk, 1, 2, 1, 1)
        self.t2_chk = QtGui.QCheckBox(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.t2_chk.setFont(font)
        self.t2_chk.setObjectName(_fromUtf8("t2_chk"))
        self.gridLayout_2.addWidget(self.t2_chk, 2, 1, 1, 1)
        self.vgam_chk = QtGui.QCheckBox(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.vgam_chk.setFont(font)
        self.vgam_chk.setObjectName(_fromUtf8("vgam_chk"))
        self.gridLayout_2.addWidget(self.vgam_chk, 1, 5, 1, 1)
        self.alb1_chk = QtGui.QCheckBox(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.alb1_chk.setFont(font)
        self.alb1_chk.setObjectName(_fromUtf8("alb1_chk"))
        self.gridLayout_2.addWidget(self.alb1_chk, 2, 4, 1, 1)
        self.f2_chk = QtGui.QCheckBox(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.f2_chk.setFont(font)
        self.f2_chk.setObjectName(_fromUtf8("f2_chk"))
        self.gridLayout_2.addWidget(self.f2_chk, 3, 1, 1, 1)
        self.s1rad_chk = QtGui.QCheckBox(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.s1rad_chk.setFont(font)
        self.s1rad_chk.setObjectName(_fromUtf8("s1rad_chk"))
        self.gridLayout_2.addWidget(self.s1rad_chk, 5, 2, 1, 1)
        self.s2long_chk = QtGui.QCheckBox(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.s2long_chk.setFont(font)
        self.s2long_chk.setObjectName(_fromUtf8("s2long_chk"))
        self.gridLayout_2.addWidget(self.s2long_chk, 6, 1, 1, 1)
        self.a_chk = QtGui.QCheckBox(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.a_chk.setFont(font)
        self.a_chk.setObjectName(_fromUtf8("a_chk"))
        self.gridLayout_2.addWidget(self.a_chk, 1, 0, 1, 1)
        self.jd0_chk = QtGui.QCheckBox(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.jd0_chk.setFont(font)
        self.jd0_chk.setObjectName(_fromUtf8("jd0_chk"))
        self.gridLayout_2.addWidget(self.jd0_chk, 0, 0, 1, 1)
        self.x2_chk = QtGui.QCheckBox(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.x2_chk.setFont(font)
        self.x2_chk.setObjectName(_fromUtf8("x2_chk"))
        self.gridLayout_2.addWidget(self.x2_chk, 3, 5, 1, 1)
        self.g1_chk = QtGui.QCheckBox(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.g1_chk.setFont(font)
        self.g1_chk.setObjectName(_fromUtf8("g1_chk"))
        self.gridLayout_2.addWidget(self.g1_chk, 2, 2, 1, 1)
        self.logd_chk = QtGui.QCheckBox(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.logd_chk.setFont(font)
        self.logd_chk.setObjectName(_fromUtf8("logd_chk"))
        self.gridLayout_2.addWidget(self.logd_chk, 1, 4, 1, 1)
        self.l1_chk = QtGui.QCheckBox(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.l1_chk.setFont(font)
        self.l1_chk.setObjectName(_fromUtf8("l1_chk"))
        self.gridLayout_2.addWidget(self.l1_chk, 3, 2, 1, 1)
        self.e_chk = QtGui.QCheckBox(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.e_chk.setFont(font)
        self.e_chk.setObjectName(_fromUtf8("e_chk"))
        self.gridLayout_2.addWidget(self.e_chk, 1, 1, 1, 1)
        self.e3b_chk = QtGui.QCheckBox(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.e3b_chk.setFont(font)
        self.e3b_chk.setObjectName(_fromUtf8("e3b_chk"))
        self.gridLayout_2.addWidget(self.e3b_chk, 4, 3, 1, 1)
        self.a3b_chk = QtGui.QCheckBox(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.a3b_chk.setFont(font)
        self.a3b_chk.setObjectName(_fromUtf8("a3b_chk"))
        self.gridLayout_2.addWidget(self.a3b_chk, 4, 0, 1, 1)
        self.s1long_chk = QtGui.QCheckBox(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.s1long_chk.setFont(font)
        self.s1long_chk.setObjectName(_fromUtf8("s1long_chk"))
        self.gridLayout_2.addWidget(self.s1long_chk, 5, 1, 1, 1)
        self.t1_chk = QtGui.QCheckBox(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.t1_chk.setFont(font)
        self.t1_chk.setObjectName(_fromUtf8("t1_chk"))
        self.gridLayout_2.addWidget(self.t1_chk, 2, 0, 1, 1)
        self.clearbaseset_btn = QtGui.QPushButton(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clearbaseset_btn.sizePolicy().hasHeightForWidth())
        self.clearbaseset_btn.setSizePolicy(sizePolicy)
        self.clearbaseset_btn.setObjectName(_fromUtf8("clearbaseset_btn"))
        self.gridLayout_2.addWidget(self.clearbaseset_btn, 5, 8, 2, 1)
        self.addsubset_btn = QtGui.QPushButton(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addsubset_btn.sizePolicy().hasHeightForWidth())
        self.addsubset_btn.setSizePolicy(sizePolicy)
        self.addsubset_btn.setObjectName(_fromUtf8("addsubset_btn"))
        self.gridLayout_2.addWidget(self.addsubset_btn, 3, 8, 2, 1)
        self.p0_chk = QtGui.QCheckBox(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.p0_chk.setFont(font)
        self.p0_chk.setObjectName(_fromUtf8("p0_chk"))
        self.gridLayout_2.addWidget(self.p0_chk, 0, 1, 1, 1)
        self.s2lat_chk = QtGui.QCheckBox(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.s2lat_chk.setFont(font)
        self.s2lat_chk.setObjectName(_fromUtf8("s2lat_chk"))
        self.gridLayout_2.addWidget(self.s2lat_chk, 6, 0, 1, 1)
        self.x1_chk = QtGui.QCheckBox(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.x1_chk.setFont(font)
        self.x1_chk.setObjectName(_fromUtf8("x1_chk"))
        self.gridLayout_2.addWidget(self.x1_chk, 3, 4, 1, 1)
        self.s1temp_chk = QtGui.QCheckBox(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.s1temp_chk.setFont(font)
        self.s1temp_chk.setObjectName(_fromUtf8("s1temp_chk"))
        self.gridLayout_2.addWidget(self.s1temp_chk, 5, 3, 1, 1)
        self.perr0_chk = QtGui.QCheckBox(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.perr0_chk.setFont(font)
        self.perr0_chk.setObjectName(_fromUtf8("perr0_chk"))
        self.gridLayout_2.addWidget(self.perr0_chk, 0, 3, 1, 1)
        self.xinc3b_chk = QtGui.QCheckBox(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.xinc3b_chk.setFont(font)
        self.xinc3b_chk.setObjectName(_fromUtf8("xinc3b_chk"))
        self.gridLayout_2.addWidget(self.xinc3b_chk, 4, 2, 1, 1)
        self.g2_chk = QtGui.QCheckBox(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.g2_chk.setFont(font)
        self.g2_chk.setObjectName(_fromUtf8("g2_chk"))
        self.gridLayout_2.addWidget(self.g2_chk, 2, 3, 1, 1)
        self.s2rad_chk = QtGui.QCheckBox(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.s2rad_chk.setFont(font)
        self.s2rad_chk.setObjectName(_fromUtf8("s2rad_chk"))
        self.gridLayout_2.addWidget(self.s2rad_chk, 6, 2, 1, 1)
        self.pot2_chk = QtGui.QCheckBox(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pot2_chk.setFont(font)
        self.pot2_chk.setObjectName(_fromUtf8("pot2_chk"))
        self.gridLayout_2.addWidget(self.pot2_chk, 3, 7, 1, 1)
        self.s1tstart_chk = QtGui.QCheckBox(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.s1tstart_chk.setFont(font)
        self.s1tstart_chk.setObjectName(_fromUtf8("s1tstart_chk"))
        self.gridLayout_2.addWidget(self.s1tstart_chk, 5, 4, 1, 1)
        self.dperdt_chk = QtGui.QCheckBox(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dperdt_chk.setFont(font)
        self.dperdt_chk.setObjectName(_fromUtf8("dperdt_chk"))
        self.gridLayout_2.addWidget(self.dperdt_chk, 0, 4, 1, 1)
        self.l2_chk = QtGui.QCheckBox(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.l2_chk.setFont(font)
        self.l2_chk.setObjectName(_fromUtf8("l2_chk"))
        self.gridLayout_2.addWidget(self.l2_chk, 3, 3, 1, 1)
        self.pshift_chk = QtGui.QCheckBox(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pshift_chk.setFont(font)
        self.pshift_chk.setObjectName(_fromUtf8("pshift_chk"))
        self.gridLayout_2.addWidget(self.pshift_chk, 0, 5, 1, 1)
        self.s1tmax1_chk = QtGui.QCheckBox(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.s1tmax1_chk.setFont(font)
        self.s1tmax1_chk.setObjectName(_fromUtf8("s1tmax1_chk"))
        self.gridLayout_2.addWidget(self.s1tmax1_chk, 5, 5, 1, 1)
        self.s2tmax1_chk = QtGui.QCheckBox(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.s2tmax1_chk.setFont(font)
        self.s2tmax1_chk.setObjectName(_fromUtf8("s2tmax1_chk"))
        self.gridLayout_2.addWidget(self.s2tmax1_chk, 6, 5, 1, 1)
        self.s2tmax2_chk = QtGui.QCheckBox(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.s2tmax2_chk.setFont(font)
        self.s2tmax2_chk.setObjectName(_fromUtf8("s2tmax2_chk"))
        self.gridLayout_2.addWidget(self.s2tmax2_chk, 6, 6, 1, 1)
        self.perr3b_chk = QtGui.QCheckBox(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.perr3b_chk.setFont(font)
        self.perr3b_chk.setObjectName(_fromUtf8("perr3b_chk"))
        self.gridLayout_2.addWidget(self.perr3b_chk, 4, 5, 1, 1)
        self.s2tend_chk = QtGui.QCheckBox(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.s2tend_chk.setFont(font)
        self.s2tend_chk.setObjectName(_fromUtf8("s2tend_chk"))
        self.gridLayout_2.addWidget(self.s2tend_chk, 6, 7, 1, 1)
        self.s1tend_chk = QtGui.QCheckBox(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.s1tend_chk.setFont(font)
        self.s1tend_chk.setObjectName(_fromUtf8("s1tend_chk"))
        self.gridLayout_2.addWidget(self.s1tend_chk, 5, 7, 1, 1)
        self.s1tmax2_chk = QtGui.QCheckBox(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.s1tmax2_chk.setFont(font)
        self.s1tmax2_chk.setObjectName(_fromUtf8("s1tmax2_chk"))
        self.gridLayout_2.addWidget(self.s1tmax2_chk, 5, 6, 1, 1)
        self.label_80 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_80.setFont(font)
        self.label_80.setObjectName(_fromUtf8("label_80"))
        self.gridLayout_2.addWidget(self.label_80, 1, 6, 1, 2)
        self.dpdt_chk = QtGui.QCheckBox(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dpdt_chk.setFont(font)
        self.dpdt_chk.setObjectName(_fromUtf8("dpdt_chk"))
        self.gridLayout_2.addWidget(self.dpdt_chk, 0, 2, 1, 1)
        self.s2temp_chk = QtGui.QCheckBox(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.s2temp_chk.setFont(font)
        self.s2temp_chk.setObjectName(_fromUtf8("s2temp_chk"))
        self.gridLayout_2.addWidget(self.s2temp_chk, 6, 3, 1, 1)
        self.s2tstart_chk = QtGui.QCheckBox(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.s2tstart_chk.setFont(font)
        self.s2tstart_chk.setObjectName(_fromUtf8("s2tstart_chk"))
        self.gridLayout_2.addWidget(self.s2tstart_chk, 6, 4, 1, 1)
        self.vlr_spinbox = QtGui.QDoubleSpinBox(self.tab_2)
        self.vlr_spinbox.setMaximumSize(QtCore.QSize(16777215, 25))
        self.vlr_spinbox.setDecimals(3)
        self.vlr_spinbox.setMaximum(1.0)
        self.vlr_spinbox.setSingleStep(0.01)
        self.vlr_spinbox.setProperty("value", 1.0)
        self.vlr_spinbox.setObjectName(_fromUtf8("vlr_spinbox"))
        self.gridLayout_2.addWidget(self.vlr_spinbox, 1, 8, 1, 1)
        self.pot1_chk = QtGui.QCheckBox(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pot1_chk.setFont(font)
        self.pot1_chk.setObjectName(_fromUtf8("pot1_chk"))
        self.gridLayout_2.addWidget(self.pot1_chk, 3, 6, 1, 1)
        self.el3_chk = QtGui.QCheckBox(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.el3_chk.setFont(font)
        self.el3_chk.setToolTip(_fromUtf8(""))
        self.el3_chk.setObjectName(_fromUtf8("el3_chk"))
        self.gridLayout_2.addWidget(self.el3_chk, 4, 6, 1, 1)
        self.desextinc_chk = QtGui.QCheckBox(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.desextinc_chk.setFont(font)
        self.desextinc_chk.setObjectName(_fromUtf8("desextinc_chk"))
        self.gridLayout_2.addWidget(self.desextinc_chk, 4, 7, 1, 1)
        self.marqmul_spinbox = QtGui.QSpinBox(self.tab_2)
        self.marqmul_spinbox.setMaximumSize(QtCore.QSize(16777215, 25))
        self.marqmul_spinbox.setProperty("value", 5)
        self.marqmul_spinbox.setObjectName(_fromUtf8("marqmul_spinbox"))
        self.gridLayout_2.addWidget(self.marqmul_spinbox, 0, 8, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_79 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_79.setFont(font)
        self.label_79.setObjectName(_fromUtf8("label_79"))
        self.horizontalLayout_4.addWidget(self.label_79)
        self.label_2 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_4.addWidget(self.label_2)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 0, 6, 1, 2)
        self.line = QtGui.QFrame(self.tab_2)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_2.addWidget(self.line, 2, 6, 1, 3)
        self.horizontalLayout_2.addLayout(self.gridLayout_2)
        self.tabWidget_3.addTab(self.tab_2, _fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.tabWidget_3)
        self.tabWidget_2.addTab(self.tab_5, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.tab_6)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.del_g1_ipt = QtGui.QLineEdit(self.tab_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.del_g1_ipt.sizePolicy().hasHeightForWidth())
        self.del_g1_ipt.setSizePolicy(sizePolicy)
        self.del_g1_ipt.setMaximumSize(QtCore.QSize(16777215, 30))
        self.del_g1_ipt.setObjectName(_fromUtf8("del_g1_ipt"))
        self.gridLayout_3.addWidget(self.del_g1_ipt, 5, 0, 1, 1)
        self.del_g2_ipt = QtGui.QLineEdit(self.tab_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.del_g2_ipt.sizePolicy().hasHeightForWidth())
        self.del_g2_ipt.setSizePolicy(sizePolicy)
        self.del_g2_ipt.setMaximumSize(QtCore.QSize(16777215, 30))
        self.del_g2_ipt.setObjectName(_fromUtf8("del_g2_ipt"))
        self.gridLayout_3.addWidget(self.del_g2_ipt, 5, 1, 1, 1)
        self.del_alb1_ipt = QtGui.QLineEdit(self.tab_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.del_alb1_ipt.sizePolicy().hasHeightForWidth())
        self.del_alb1_ipt.setSizePolicy(sizePolicy)
        self.del_alb1_ipt.setMaximumSize(QtCore.QSize(16777215, 30))
        self.del_alb1_ipt.setObjectName(_fromUtf8("del_alb1_ipt"))
        self.gridLayout_3.addWidget(self.del_alb1_ipt, 5, 4, 1, 1)
        self.label_54 = QtGui.QLabel(self.tab_6)
        self.label_54.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_54.setObjectName(_fromUtf8("label_54"))
        self.gridLayout_3.addWidget(self.label_54, 4, 0, 1, 1)
        self.del_pshift_ipt = QtGui.QLineEdit(self.tab_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.del_pshift_ipt.sizePolicy().hasHeightForWidth())
        self.del_pshift_ipt.setSizePolicy(sizePolicy)
        self.del_pshift_ipt.setMaximumSize(QtCore.QSize(16777215, 30))
        self.del_pshift_ipt.setObjectName(_fromUtf8("del_pshift_ipt"))
        self.gridLayout_3.addWidget(self.del_pshift_ipt, 3, 4, 1, 1)
        self.label_59 = QtGui.QLabel(self.tab_6)
        self.label_59.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_59.setObjectName(_fromUtf8("label_59"))
        self.gridLayout_3.addWidget(self.label_59, 2, 4, 1, 1)
        self.label_39 = QtGui.QLabel(self.tab_6)
        self.label_39.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.gridLayout_3.addWidget(self.label_39, 4, 9, 1, 1)
        self.label_52 = QtGui.QLabel(self.tab_6)
        self.label_52.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_52.setObjectName(_fromUtf8("label_52"))
        self.gridLayout_3.addWidget(self.label_52, 2, 0, 1, 1)
        self.label_37 = QtGui.QLabel(self.tab_6)
        self.label_37.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.gridLayout_3.addWidget(self.label_37, 4, 1, 1, 1)
        self.del_s1lng_ipt = QtGui.QLineEdit(self.tab_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.del_s1lng_ipt.sizePolicy().hasHeightForWidth())
        self.del_s1lng_ipt.setSizePolicy(sizePolicy)
        self.del_s1lng_ipt.setMaximumSize(QtCore.QSize(16777215, 30))
        self.del_s1lng_ipt.setObjectName(_fromUtf8("del_s1lng_ipt"))
        self.gridLayout_3.addWidget(self.del_s1lng_ipt, 7, 1, 1, 1)
        self.label_36 = QtGui.QLabel(self.tab_6)
        self.label_36.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.gridLayout_3.addWidget(self.label_36, 2, 1, 1, 1)
        self.label_62 = QtGui.QLabel(self.tab_6)
        self.label_62.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_62.setObjectName(_fromUtf8("label_62"))
        self.gridLayout_3.addWidget(self.label_62, 2, 5, 1, 1)
        self.del_l2_ipt = QtGui.QLineEdit(self.tab_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.del_l2_ipt.sizePolicy().hasHeightForWidth())
        self.del_l2_ipt.setSizePolicy(sizePolicy)
        self.del_l2_ipt.setMaximumSize(QtCore.QSize(16777215, 30))
        self.del_l2_ipt.setObjectName(_fromUtf8("del_l2_ipt"))
        self.gridLayout_3.addWidget(self.del_l2_ipt, 3, 9, 1, 1)
        self.del_perr0_ipt = QtGui.QLineEdit(self.tab_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.del_perr0_ipt.sizePolicy().hasHeightForWidth())
        self.del_perr0_ipt.setSizePolicy(sizePolicy)
        self.del_perr0_ipt.setMaximumSize(QtCore.QSize(16777215, 30))
        self.del_perr0_ipt.setObjectName(_fromUtf8("del_perr0_ipt"))
        self.gridLayout_3.addWidget(self.del_perr0_ipt, 3, 5, 1, 1)
        self.del_t2_ipt = QtGui.QLineEdit(self.tab_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.del_t2_ipt.sizePolicy().hasHeightForWidth())
        self.del_t2_ipt.setSizePolicy(sizePolicy)
        self.del_t2_ipt.setMaximumSize(QtCore.QSize(16777215, 30))
        self.del_t2_ipt.setObjectName(_fromUtf8("del_t2_ipt"))
        self.gridLayout_3.addWidget(self.del_t2_ipt, 5, 3, 1, 1)
        self.del_s2tmpf_ipt = QtGui.QLineEdit(self.tab_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.del_s2tmpf_ipt.sizePolicy().hasHeightForWidth())
        self.del_s2tmpf_ipt.setSizePolicy(sizePolicy)
        self.del_s2tmpf_ipt.setMaximumSize(QtCore.QSize(16777215, 30))
        self.del_s2tmpf_ipt.setObjectName(_fromUtf8("del_s2tmpf_ipt"))
        self.gridLayout_3.addWidget(self.del_s2tmpf_ipt, 7, 7, 1, 1)
        self.label_47 = QtGui.QLabel(self.tab_6)
        self.label_47.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.gridLayout_3.addWidget(self.label_47, 2, 7, 1, 1)
        self.label_48 = QtGui.QLabel(self.tab_6)
        self.label_48.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_48.setStatusTip(_fromUtf8(""))
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.gridLayout_3.addWidget(self.label_48, 6, 5, 1, 1)
        self.del_t1_ipt = QtGui.QLineEdit(self.tab_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.del_t1_ipt.sizePolicy().hasHeightForWidth())
        self.del_t1_ipt.setSizePolicy(sizePolicy)
        self.del_t1_ipt.setMaximumSize(QtCore.QSize(16777215, 30))
        self.del_t1_ipt.setObjectName(_fromUtf8("del_t1_ipt"))
        self.gridLayout_3.addWidget(self.del_t1_ipt, 5, 2, 1, 1)
        self.label_56 = QtGui.QLabel(self.tab_6)
        self.label_56.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_56.setObjectName(_fromUtf8("label_56"))
        self.gridLayout_3.addWidget(self.label_56, 2, 3, 1, 1)
        self.label_50 = QtGui.QLabel(self.tab_6)
        self.label_50.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_50.setStatusTip(_fromUtf8(""))
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.gridLayout_3.addWidget(self.label_50, 6, 4, 1, 1)
        self.label_53 = QtGui.QLabel(self.tab_6)
        self.label_53.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_53.setObjectName(_fromUtf8("label_53"))
        self.gridLayout_3.addWidget(self.label_53, 2, 8, 1, 1)
        self.del_s2lng_ipt = QtGui.QLineEdit(self.tab_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.del_s2lng_ipt.sizePolicy().hasHeightForWidth())
        self.del_s2lng_ipt.setSizePolicy(sizePolicy)
        self.del_s2lng_ipt.setMaximumSize(QtCore.QSize(16777215, 30))
        self.del_s2lng_ipt.setObjectName(_fromUtf8("del_s2lng_ipt"))
        self.gridLayout_3.addWidget(self.del_s2lng_ipt, 7, 5, 1, 1)
        self.del_i_ipt = QtGui.QLineEdit(self.tab_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.del_i_ipt.sizePolicy().hasHeightForWidth())
        self.del_i_ipt.setSizePolicy(sizePolicy)
        self.del_i_ipt.setMaximumSize(QtCore.QSize(16777215, 30))
        self.del_i_ipt.setObjectName(_fromUtf8("del_i_ipt"))
        self.gridLayout_3.addWidget(self.del_i_ipt, 3, 2, 1, 1)
        self.label_42 = QtGui.QLabel(self.tab_6)
        self.label_42.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_42.setStatusTip(_fromUtf8(""))
        self.label_42.setWhatsThis(_fromUtf8(""))
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.gridLayout_3.addWidget(self.label_42, 6, 0, 1, 1)
        self.label_40 = QtGui.QLabel(self.tab_6)
        self.label_40.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.gridLayout_3.addWidget(self.label_40, 2, 9, 1, 1)
        self.label_57 = QtGui.QLabel(self.tab_6)
        self.label_57.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_57.setObjectName(_fromUtf8("label_57"))
        self.gridLayout_3.addWidget(self.label_57, 4, 3, 1, 1)
        self.label_51 = QtGui.QLabel(self.tab_6)
        self.label_51.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_51.setObjectName(_fromUtf8("label_51"))
        self.gridLayout_3.addWidget(self.label_51, 6, 2, 1, 1)
        self.del_pot2_ipt = QtGui.QLineEdit(self.tab_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.del_pot2_ipt.sizePolicy().hasHeightForWidth())
        self.del_pot2_ipt.setSizePolicy(sizePolicy)
        self.del_pot2_ipt.setMaximumSize(QtCore.QSize(16777215, 30))
        self.del_pot2_ipt.setObjectName(_fromUtf8("del_pot2_ipt"))
        self.gridLayout_3.addWidget(self.del_pot2_ipt, 3, 7, 1, 1)
        self.del_s1agrad_ipt = QtGui.QLineEdit(self.tab_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.del_s1agrad_ipt.sizePolicy().hasHeightForWidth())
        self.del_s1agrad_ipt.setSizePolicy(sizePolicy)
        self.del_s1agrad_ipt.setMaximumSize(QtCore.QSize(16777215, 30))
        self.del_s1agrad_ipt.setObjectName(_fromUtf8("del_s1agrad_ipt"))
        self.gridLayout_3.addWidget(self.del_s1agrad_ipt, 7, 2, 1, 1)
        self.label_43 = QtGui.QLabel(self.tab_6)
        self.label_43.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.gridLayout_3.addWidget(self.label_43, 2, 6, 1, 1)
        self.del_x2_ipt = QtGui.QLineEdit(self.tab_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.del_x2_ipt.sizePolicy().hasHeightForWidth())
        self.del_x2_ipt.setSizePolicy(sizePolicy)
        self.del_x2_ipt.setMaximumSize(QtCore.QSize(16777215, 30))
        self.del_x2_ipt.setObjectName(_fromUtf8("del_x2_ipt"))
        self.gridLayout_3.addWidget(self.del_x2_ipt, 5, 9, 1, 1)
        self.del_s1tmpf_ipt = QtGui.QLineEdit(self.tab_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.del_s1tmpf_ipt.sizePolicy().hasHeightForWidth())
        self.del_s1tmpf_ipt.setSizePolicy(sizePolicy)
        self.del_s1tmpf_ipt.setMaximumSize(QtCore.QSize(16777215, 30))
        self.del_s1tmpf_ipt.setObjectName(_fromUtf8("del_s1tmpf_ipt"))
        self.gridLayout_3.addWidget(self.del_s1tmpf_ipt, 7, 3, 1, 1)
        self.label_38 = QtGui.QLabel(self.tab_6)
        self.label_38.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.gridLayout_3.addWidget(self.label_38, 4, 2, 1, 1)
        self.label_58 = QtGui.QLabel(self.tab_6)
        self.label_58.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_58.setObjectName(_fromUtf8("label_58"))
        self.gridLayout_3.addWidget(self.label_58, 2, 2, 1, 1)
        self.del_s2lat_ipt = QtGui.QLineEdit(self.tab_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.del_s2lat_ipt.sizePolicy().hasHeightForWidth())
        self.del_s2lat_ipt.setSizePolicy(sizePolicy)
        self.del_s2lat_ipt.setMaximumSize(QtCore.QSize(16777215, 30))
        self.del_s2lat_ipt.setObjectName(_fromUtf8("del_s2lat_ipt"))
        self.gridLayout_3.addWidget(self.del_s2lat_ipt, 7, 4, 1, 1)
        self.label_45 = QtGui.QLabel(self.tab_6)
        self.label_45.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_45.setStatusTip(_fromUtf8(""))
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.gridLayout_3.addWidget(self.label_45, 6, 7, 1, 1)
        self.label_46 = QtGui.QLabel(self.tab_6)
        self.label_46.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.gridLayout_3.addWidget(self.label_46, 4, 4, 1, 1)
        self.del_q_ipt = QtGui.QLineEdit(self.tab_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.del_q_ipt.sizePolicy().hasHeightForWidth())
        self.del_q_ipt.setSizePolicy(sizePolicy)
        self.del_q_ipt.setMaximumSize(QtCore.QSize(16777215, 30))
        self.del_q_ipt.setObjectName(_fromUtf8("del_q_ipt"))
        self.gridLayout_3.addWidget(self.del_q_ipt, 3, 3, 1, 1)
        self.label_55 = QtGui.QLabel(self.tab_6)
        self.label_55.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_55.setObjectName(_fromUtf8("label_55"))
        self.gridLayout_3.addWidget(self.label_55, 4, 8, 1, 1)
        self.setdeldefaults_btn = QtGui.QPushButton(self.tab_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setdeldefaults_btn.sizePolicy().hasHeightForWidth())
        self.setdeldefaults_btn.setSizePolicy(sizePolicy)
        self.setdeldefaults_btn.setObjectName(_fromUtf8("setdeldefaults_btn"))
        self.gridLayout_3.addWidget(self.setdeldefaults_btn, 6, 8, 2, 2)
        self.label_41 = QtGui.QLabel(self.tab_6)
        self.label_41.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.gridLayout_3.addWidget(self.label_41, 6, 3, 1, 1)
        self.del_f2_ipt = QtGui.QLineEdit(self.tab_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.del_f2_ipt.sizePolicy().hasHeightForWidth())
        self.del_f2_ipt.setSizePolicy(sizePolicy)
        self.del_f2_ipt.setMaximumSize(QtCore.QSize(16777215, 30))
        self.del_f2_ipt.setObjectName(_fromUtf8("del_f2_ipt"))
        self.gridLayout_3.addWidget(self.del_f2_ipt, 5, 7, 1, 1)
        self.del_s2agrad_ipt = QtGui.QLineEdit(self.tab_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.del_s2agrad_ipt.sizePolicy().hasHeightForWidth())
        self.del_s2agrad_ipt.setSizePolicy(sizePolicy)
        self.del_s2agrad_ipt.setMaximumSize(QtCore.QSize(16777215, 30))
        self.del_s2agrad_ipt.setObjectName(_fromUtf8("del_s2agrad_ipt"))
        self.gridLayout_3.addWidget(self.del_s2agrad_ipt, 7, 6, 1, 1)
        self.label_63 = QtGui.QLabel(self.tab_6)
        self.label_63.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_63.setObjectName(_fromUtf8("label_63"))
        self.gridLayout_3.addWidget(self.label_63, 6, 1, 1, 1)
        self.del_alb2_ipt = QtGui.QLineEdit(self.tab_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.del_alb2_ipt.sizePolicy().hasHeightForWidth())
        self.del_alb2_ipt.setSizePolicy(sizePolicy)
        self.del_alb2_ipt.setMaximumSize(QtCore.QSize(16777215, 30))
        self.del_alb2_ipt.setObjectName(_fromUtf8("del_alb2_ipt"))
        self.gridLayout_3.addWidget(self.del_alb2_ipt, 5, 5, 1, 1)
        self.label_49 = QtGui.QLabel(self.tab_6)
        self.label_49.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.gridLayout_3.addWidget(self.label_49, 4, 6, 1, 1)
        self.del_e_ipt = QtGui.QLineEdit(self.tab_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.del_e_ipt.sizePolicy().hasHeightForWidth())
        self.del_e_ipt.setSizePolicy(sizePolicy)
        self.del_e_ipt.setMaximumSize(QtCore.QSize(16777215, 30))
        self.del_e_ipt.setObjectName(_fromUtf8("del_e_ipt"))
        self.gridLayout_3.addWidget(self.del_e_ipt, 3, 1, 1, 1)
        self.label_60 = QtGui.QLabel(self.tab_6)
        self.label_60.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_60.setStatusTip(_fromUtf8(""))
        self.label_60.setObjectName(_fromUtf8("label_60"))
        self.gridLayout_3.addWidget(self.label_60, 6, 6, 1, 1)
        self.label_44 = QtGui.QLabel(self.tab_6)
        self.label_44.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.gridLayout_3.addWidget(self.label_44, 4, 5, 1, 1)
        self.del_x1_ipt = QtGui.QLineEdit(self.tab_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.del_x1_ipt.sizePolicy().hasHeightForWidth())
        self.del_x1_ipt.setSizePolicy(sizePolicy)
        self.del_x1_ipt.setMaximumSize(QtCore.QSize(16777215, 30))
        self.del_x1_ipt.setObjectName(_fromUtf8("del_x1_ipt"))
        self.gridLayout_3.addWidget(self.del_x1_ipt, 5, 8, 1, 1)
        self.del_a_ipt = QtGui.QLineEdit(self.tab_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.del_a_ipt.sizePolicy().hasHeightForWidth())
        self.del_a_ipt.setSizePolicy(sizePolicy)
        self.del_a_ipt.setMaximumSize(QtCore.QSize(16777215, 30))
        self.del_a_ipt.setObjectName(_fromUtf8("del_a_ipt"))
        self.gridLayout_3.addWidget(self.del_a_ipt, 3, 0, 1, 1)
        self.del_s1lat_ipt = QtGui.QLineEdit(self.tab_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.del_s1lat_ipt.sizePolicy().hasHeightForWidth())
        self.del_s1lat_ipt.setSizePolicy(sizePolicy)
        self.del_s1lat_ipt.setMaximumSize(QtCore.QSize(16777215, 30))
        self.del_s1lat_ipt.setToolTip(_fromUtf8(""))
        self.del_s1lat_ipt.setObjectName(_fromUtf8("del_s1lat_ipt"))
        self.gridLayout_3.addWidget(self.del_s1lat_ipt, 7, 0, 1, 1)
        self.del_pot1_ipt = QtGui.QLineEdit(self.tab_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.del_pot1_ipt.sizePolicy().hasHeightForWidth())
        self.del_pot1_ipt.setSizePolicy(sizePolicy)
        self.del_pot1_ipt.setMaximumSize(QtCore.QSize(16777215, 30))
        self.del_pot1_ipt.setObjectName(_fromUtf8("del_pot1_ipt"))
        self.gridLayout_3.addWidget(self.del_pot1_ipt, 3, 6, 1, 1)
        self.del_f1_ipt = QtGui.QLineEdit(self.tab_6)
        self.del_f1_ipt.setMaximumSize(QtCore.QSize(16777215, 30))
        self.del_f1_ipt.setObjectName(_fromUtf8("del_f1_ipt"))
        self.gridLayout_3.addWidget(self.del_f1_ipt, 5, 6, 1, 1)
        self.label_35 = QtGui.QLabel(self.tab_6)
        self.label_35.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.gridLayout_3.addWidget(self.label_35, 4, 7, 1, 1)
        self.del_l1_ipt = QtGui.QLineEdit(self.tab_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.del_l1_ipt.sizePolicy().hasHeightForWidth())
        self.del_l1_ipt.setSizePolicy(sizePolicy)
        self.del_l1_ipt.setMaximumSize(QtCore.QSize(16777215, 30))
        self.del_l1_ipt.setObjectName(_fromUtf8("del_l1_ipt"))
        self.gridLayout_3.addWidget(self.del_l1_ipt, 3, 8, 1, 1)
        self.label_61 = QtGui.QLabel(self.tab_6)
        self.label_61.setObjectName(_fromUtf8("label_61"))
        self.gridLayout_3.addWidget(self.label_61, 0, 0, 1, 10)
        self.line_8 = QtGui.QFrame(self.tab_6)
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.gridLayout_3.addWidget(self.line_8, 1, 0, 1, 10)
        self.horizontalLayout_5.addLayout(self.gridLayout_3)
        self.tabWidget_2.addTab(self.tab_6, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.tabWidget_2)
        self.line_3 = QtGui.QFrame(DCWidget)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout_2.addWidget(self.line_3)
        self.tabWidget_4 = QtGui.QTabWidget(DCWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget_4.sizePolicy().hasHeightForWidth())
        self.tabWidget_4.setSizePolicy(sizePolicy)
        self.tabWidget_4.setMinimumSize(QtCore.QSize(500, 200))
        self.tabWidget_4.setObjectName(_fromUtf8("tabWidget_4"))
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName(_fromUtf8("tab_7"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.tab_7)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.component_treewidget = QtGui.QTreeWidget(self.tab_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(15)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.component_treewidget.sizePolicy().hasHeightForWidth())
        self.component_treewidget.setSizePolicy(sizePolicy)
        self.component_treewidget.setAlternatingRowColors(True)
        self.component_treewidget.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.component_treewidget.setObjectName(_fromUtf8("component_treewidget"))
        self.gridLayout_4.addWidget(self.component_treewidget, 0, 2, 1, 1)
        self.result_treewidget = QtGui.QTreeWidget(self.tab_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(25)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.result_treewidget.sizePolicy().hasHeightForWidth())
        self.result_treewidget.setSizePolicy(sizePolicy)
        self.result_treewidget.setAlternatingRowColors(True)
        self.result_treewidget.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.result_treewidget.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.result_treewidget.setHeaderHidden(False)
        self.result_treewidget.setObjectName(_fromUtf8("result_treewidget"))
        self.gridLayout_4.addWidget(self.result_treewidget, 0, 0, 1, 1)
        self.residual_treewidget = QtGui.QTreeWidget(self.tab_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.residual_treewidget.sizePolicy().hasHeightForWidth())
        self.residual_treewidget.setSizePolicy(sizePolicy)
        self.residual_treewidget.setMaximumSize(QtCore.QSize(16777215, 75))
        self.residual_treewidget.setAlternatingRowColors(True)
        self.residual_treewidget.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.residual_treewidget.setObjectName(_fromUtf8("residual_treewidget"))
        self.gridLayout_4.addWidget(self.residual_treewidget, 2, 0, 1, 3)
        self.line_5 = QtGui.QFrame(self.tab_7)
        self.line_5.setFrameShape(QtGui.QFrame.VLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.gridLayout_4.addWidget(self.line_5, 0, 1, 1, 1)
        self.line_6 = QtGui.QFrame(self.tab_7)
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.gridLayout_4.addWidget(self.line_6, 1, 0, 1, 3)
        self.horizontalLayout_6.addLayout(self.gridLayout_4)
        self.tabWidget_4.addTab(self.tab_7, _fromUtf8(""))
        self.tab_8 = QtGui.QWidget()
        self.tab_8.setObjectName(_fromUtf8("tab_8"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.tab_8)
        self.horizontalLayout_7.setMargin(0)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.curvestat_treewidget = QtGui.QTreeWidget(self.tab_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.curvestat_treewidget.sizePolicy().hasHeightForWidth())
        self.curvestat_treewidget.setSizePolicy(sizePolicy)
        self.curvestat_treewidget.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.curvestat_treewidget.setIndentation(0)
        self.curvestat_treewidget.setColumnCount(5)
        self.curvestat_treewidget.setObjectName(_fromUtf8("curvestat_treewidget"))
        self.horizontalLayout_7.addWidget(self.curvestat_treewidget)
        self.tabWidget_4.addTab(self.tab_8, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.tabWidget_4)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.line_7 = QtGui.QFrame(DCWidget)
        self.line_7.setFrameShape(QtGui.QFrame.VLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.horizontalLayout.addWidget(self.line_7)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setVerticalSpacing(0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.plot_btn = QtGui.QPushButton(DCWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot_btn.sizePolicy().hasHeightForWidth())
        self.plot_btn.setSizePolicy(sizePolicy)
        self.plot_btn.setMaximumSize(QtCore.QSize(100, 16777215))
        self.plot_btn.setObjectName(_fromUtf8("plot_btn"))
        self.gridLayout_5.addWidget(self.plot_btn, 0, 4, 2, 1)
        self.popmain_btn = QtGui.QPushButton(DCWidget)
        self.popmain_btn.setMaximumSize(QtCore.QSize(100, 16777215))
        self.popmain_btn.setObjectName(_fromUtf8("popmain_btn"))
        self.gridLayout_5.addWidget(self.popmain_btn, 0, 5, 2, 1)
        self.autoupdate_chk = QtGui.QCheckBox(DCWidget)
        self.autoupdate_chk.setMaximumSize(QtCore.QSize(125, 16777215))
        self.autoupdate_chk.setObjectName(_fromUtf8("autoupdate_chk"))
        self.gridLayout_5.addWidget(self.autoupdate_chk, 0, 2, 1, 1)
        self.data_combobox = QtGui.QComboBox(DCWidget)
        self.data_combobox.setObjectName(_fromUtf8("data_combobox"))
        self.gridLayout_5.addWidget(self.data_combobox, 0, 0, 2, 1)
        self.time_combobox = QtGui.QComboBox(DCWidget)
        self.time_combobox.setMaximumSize(QtCore.QSize(125, 16777215))
        self.time_combobox.setObjectName(_fromUtf8("time_combobox"))
        self.time_combobox.addItem(_fromUtf8(""))
        self.time_combobox.addItem(_fromUtf8(""))
        self.gridLayout_5.addWidget(self.time_combobox, 0, 1, 2, 1)
        self.uselc_chk = QtGui.QCheckBox(DCWidget)
        self.uselc_chk.setMaximumSize(QtCore.QSize(125, 16777215))
        self.uselc_chk.setChecked(True)
        self.uselc_chk.setObjectName(_fromUtf8("uselc_chk"))
        self.gridLayout_5.addWidget(self.uselc_chk, 1, 2, 1, 1)
        self.line_11 = QtGui.QFrame(DCWidget)
        self.line_11.setFrameShape(QtGui.QFrame.VLine)
        self.line_11.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_11.setObjectName(_fromUtf8("line_11"))
        self.gridLayout_5.addWidget(self.line_11, 0, 3, 2, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_5)
        self.line_4 = QtGui.QFrame(DCWidget)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.verticalLayout_3.addWidget(self.line_4)
        self.plotwidget = QtGui.QWidget(DCWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotwidget.sizePolicy().hasHeightForWidth())
        self.plotwidget.setSizePolicy(sizePolicy)
        self.plotwidget.setMinimumSize(QtCore.QSize(300, 300))
        self.plotwidget.setObjectName(_fromUtf8("plotwidget"))
        self.verticalLayout_3.addWidget(self.plotwidget)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.horizontalLayout_8.addLayout(self.horizontalLayout)

        self.retranslateUi(DCWidget)
        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget_4.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(DCWidget)

    def retranslateUi(self, DCWidget):
        DCWidget.setWindowTitle(_translate("DCWidget", "Run Differential Corrections", None))
        self.label_8.setText(_translate("DCWidget", "Number of iterations", None))
        self.exportresults_btn.setText(_translate("DCWidget", "Export Results", None))
        self.updateinputs_btn.setText(_translate("DCWidget", "Update Inputs", None))
        self.rundc2015_btn.setText(_translate("DCWidget", "Run DC", None))
        self.viewlastdcin_btn.setText(_translate("DCWidget", "dcin.active", None))
        self.viewlaastdcout_btn.setText(_translate("DCWidget", "dcout.active", None))
        self.f1_chk.setText(_translate("DCWidget", "F1", None))
        self.s1lat_chk.setText(_translate("DCWidget", "S1 LAT", None))
        self.tc3b_chk.setText(_translate("DCWidget", "TC3B", None))
        self.q_chk.setText(_translate("DCWidget", "Q", None))
        self.p3b_chk.setText(_translate("DCWidget", "P3B", None))
        self.alb2_chk.setText(_translate("DCWidget", "ALB2", None))
        self.incl_chk.setText(_translate("DCWidget", "INCL", None))
        self.t2_chk.setText(_translate("DCWidget", "T2", None))
        self.vgam_chk.setText(_translate("DCWidget", "VGAM", None))
        self.alb1_chk.setText(_translate("DCWidget", "ALB1", None))
        self.f2_chk.setText(_translate("DCWidget", "F2", None))
        self.s1rad_chk.setText(_translate("DCWidget", "S1 RAD", None))
        self.s2long_chk.setText(_translate("DCWidget", "S2 LON", None))
        self.a_chk.setText(_translate("DCWidget", "a", None))
        self.jd0_chk.setText(_translate("DCWidget", "JD0", None))
        self.x2_chk.setText(_translate("DCWidget", "X2", None))
        self.g1_chk.setText(_translate("DCWidget", "G1", None))
        self.logd_chk.setText(_translate("DCWidget", "logD", None))
        self.l1_chk.setText(_translate("DCWidget", "L1", None))
        self.e_chk.setText(_translate("DCWidget", "e", None))
        self.e3b_chk.setText(_translate("DCWidget", "E3B", None))
        self.a3b_chk.setText(_translate("DCWidget", "A3B", None))
        self.s1long_chk.setText(_translate("DCWidget", "S1 LON", None))
        self.t1_chk.setText(_translate("DCWidget", "T1", None))
        self.clearbaseset_btn.setText(_translate("DCWidget", "Clear", None))
        self.addsubset_btn.setText(_translate("DCWidget", "Add", None))
        self.p0_chk.setText(_translate("DCWidget", "P0", None))
        self.s2lat_chk.setText(_translate("DCWidget", "S2 LAT", None))
        self.x1_chk.setText(_translate("DCWidget", "X1", None))
        self.s1temp_chk.setText(_translate("DCWidget", "S1 TEMP", None))
        self.perr0_chk.setText(_translate("DCWidget", "PERR0", None))
        self.xinc3b_chk.setText(_translate("DCWidget", "XINC3B", None))
        self.g2_chk.setText(_translate("DCWidget", "G2", None))
        self.s2rad_chk.setText(_translate("DCWidget", "S2 RAD", None))
        self.pot2_chk.setText(_translate("DCWidget", "POT2", None))
        self.s1tstart_chk.setText(_translate("DCWidget", "S1 Tstart", None))
        self.dperdt_chk.setText(_translate("DCWidget", "dPERdt", None))
        self.l2_chk.setText(_translate("DCWidget", "L2", None))
        self.pshift_chk.setText(_translate("DCWidget", "PSHIFT", None))
        self.s1tmax1_chk.setText(_translate("DCWidget", "S1 Tmax1", None))
        self.s2tmax1_chk.setText(_translate("DCWidget", "S2 Tmax1", None))
        self.s2tmax2_chk.setText(_translate("DCWidget", "S2 Tmax2", None))
        self.perr3b_chk.setText(_translate("DCWidget", "PERR3B", None))
        self.s2tend_chk.setText(_translate("DCWidget", "S2 Tend", None))
        self.s1tend_chk.setText(_translate("DCWidget", "S1 Tend", None))
        self.s1tmax2_chk.setText(_translate("DCWidget", "S1 Tmax2", None))
        self.label_80.setToolTip(_translate("DCWidget", "The fraction of DC’s output corrections to be applied to the input parameters to form the output parameters.", None))
        self.label_80.setStatusTip(_translate("DCWidget", "VLR", None))
        self.label_80.setText(_translate("DCWidget", "Vector Reduction:", None))
        self.dpdt_chk.setText(_translate("DCWidget", "dPdt", None))
        self.s2temp_chk.setText(_translate("DCWidget", "S2 TEMP", None))
        self.s2tstart_chk.setText(_translate("DCWidget", "S2 Tstart", None))
        self.pot1_chk.setText(_translate("DCWidget", "POT1", None))
        self.el3_chk.setText(_translate("DCWidget", "EL3", None))
        self.desextinc_chk.setToolTip(_translate("DCWidget", "DESEXTINC", None))
        self.desextinc_chk.setText(_translate("DCWidget", "DEXT", None))
        self.label_79.setToolTip(_translate("DCWidget", "Multiplier (λ) to be used in the Levenberg-Marquardt method.", None))
        self.label_79.setStatusTip(_translate("DCWidget", "XLAMDA", None))
        self.label_79.setText(_translate("DCWidget", "  λ: ", None))
        self.label_2.setText(_translate("DCWidget", "1.000d −", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_2), _translate("DCWidget", "Base Set", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("DCWidget", "KEEP\'s", None))
        self.del_g1_ipt.setText(_translate("DCWidget", "0.01", None))
        self.del_g2_ipt.setText(_translate("DCWidget", "0.01", None))
        self.del_alb1_ipt.setText(_translate("DCWidget", "0.05", None))
        self.label_54.setToolTip(_translate("DCWidget", "Gravity darkening exponent", None))
        self.label_54.setText(_translate("DCWidget", "G1", None))
        self.del_pshift_ipt.setText(_translate("DCWidget", "0.002", None))
        self.label_59.setToolTip(_translate("DCWidget", "Phase Shift", None))
        self.label_59.setText(_translate("DCWidget", "PSHIFT", None))
        self.label_39.setToolTip(_translate("DCWidget", "Limb darkening coefficient", None))
        self.label_39.setText(_translate("DCWidget", "X2", None))
        self.label_52.setToolTip(_translate("DCWidget", "Semi-major axis", None))
        self.label_52.setText(_translate("DCWidget", "a", None))
        self.label_37.setToolTip(_translate("DCWidget", "Gravity darkening exponent", None))
        self.label_37.setText(_translate("DCWidget", "G2", None))
        self.del_s1lng_ipt.setText(_translate("DCWidget", "0.02", None))
        self.label_36.setToolTip(_translate("DCWidget", "Orbit eccentricity", None))
        self.label_36.setText(_translate("DCWidget", "e", None))
        self.label_62.setToolTip(_translate("DCWidget", "V Gamma", None))
        self.label_62.setText(_translate("DCWidget", "PERR0", None))
        self.del_l2_ipt.setText(_translate("DCWidget", "0.01", None))
        self.del_perr0_ipt.setText(_translate("DCWidget", "0.01", None))
        self.del_t2_ipt.setText(_translate("DCWidget", "0.02", None))
        self.del_s2tmpf_ipt.setText(_translate("DCWidget", "0.02", None))
        self.label_47.setToolTip(_translate("DCWidget", "Surface potential", None))
        self.label_47.setText(_translate("DCWidget", "POT2", None))
        self.label_48.setToolTip(_translate("DCWidget", "Spot 2 Longitude", None))
        self.label_48.setText(_translate("DCWidget", "S2 LON", None))
        self.del_t1_ipt.setText(_translate("DCWidget", "0.02", None))
        self.label_56.setToolTip(_translate("DCWidget", "Mass ratio, star 2/star 1", None))
        self.label_56.setText(_translate("DCWidget", "Q", None))
        self.label_50.setToolTip(_translate("DCWidget", "Spot 2 Latitude", None))
        self.label_50.setText(_translate("DCWidget", "S2 LAT", None))
        self.label_53.setToolTip(_translate("DCWidget", "Relative monochromatic luminosity", None))
        self.label_53.setText(_translate("DCWidget", "L1", None))
        self.del_s2lng_ipt.setText(_translate("DCWidget", "0.001", None))
        self.del_i_ipt.setText(_translate("DCWidget", "0.2", None))
        self.label_42.setToolTip(_translate("DCWidget", "Spot 1 Latitude", None))
        self.label_42.setText(_translate("DCWidget", "S1 LAT", None))
        self.label_40.setToolTip(_translate("DCWidget", "Relative monochromatic luminosity", None))
        self.label_40.setText(_translate("DCWidget", "L2", None))
        self.label_57.setToolTip(_translate("DCWidget", "Average surface temperature in 10000K", None))
        self.label_57.setText(_translate("DCWidget", "T2", None))
        self.label_51.setToolTip(_translate("DCWidget", "Spot 1 Angular Radius", None))
        self.label_51.setText(_translate("DCWidget", "S1 RAD", None))
        self.del_pot2_ipt.setText(_translate("DCWidget", "0.02", None))
        self.del_s1agrad_ipt.setText(_translate("DCWidget", "0.001", None))
        self.label_43.setToolTip(_translate("DCWidget", "Surface potential", None))
        self.label_43.setText(_translate("DCWidget", "POT1", None))
        self.del_x2_ipt.setText(_translate("DCWidget", "0.01", None))
        self.del_s1tmpf_ipt.setText(_translate("DCWidget", "0.02", None))
        self.label_38.setToolTip(_translate("DCWidget", "Average surface temperature in 10000K", None))
        self.label_38.setText(_translate("DCWidget", "T1", None))
        self.label_58.setToolTip(_translate("DCWidget", "Inclination", None))
        self.label_58.setText(_translate("DCWidget", "i", None))
        self.del_s2lat_ipt.setText(_translate("DCWidget", "0.02", None))
        self.label_45.setToolTip(_translate("DCWidget", "Spot 2 Temperature Factor", None))
        self.label_45.setText(_translate("DCWidget", "S2 TEMP", None))
        self.label_46.setToolTip(_translate("DCWidget", "Bolometric Albedo", None))
        self.label_46.setText(_translate("DCWidget", "ALB1", None))
        self.del_q_ipt.setText(_translate("DCWidget", "0.003", None))
        self.label_55.setToolTip(_translate("DCWidget", "Limb darkening coefficient", None))
        self.label_55.setText(_translate("DCWidget", "X1", None))
        self.setdeldefaults_btn.setText(_translate("DCWidget", "Set Defaults", None))
        self.label_41.setToolTip(_translate("DCWidget", "Spot 1 Temperature Factor", None))
        self.label_41.setText(_translate("DCWidget", "S1 TEMP", None))
        self.del_f2_ipt.setText(_translate("DCWidget", "0.01", None))
        self.del_s2agrad_ipt.setText(_translate("DCWidget", "0.0001", None))
        self.label_63.setToolTip(_translate("DCWidget", "Spot 1 Longitude", None))
        self.label_63.setText(_translate("DCWidget", "S1 LON", None))
        self.del_alb2_ipt.setText(_translate("DCWidget", "0.05", None))
        self.label_49.setToolTip(_translate("DCWidget", "Ratio of axial rotation rate vs. mean orbital rate", None))
        self.label_49.setText(_translate("DCWidget", "F1", None))
        self.del_e_ipt.setText(_translate("DCWidget", "0.001", None))
        self.label_60.setToolTip(_translate("DCWidget", "Spot 2 Angular Radius", None))
        self.label_60.setText(_translate("DCWidget", "S2 RAD", None))
        self.label_44.setToolTip(_translate("DCWidget", "Bolometric Albedo", None))
        self.label_44.setText(_translate("DCWidget", "ALB2", None))
        self.del_x1_ipt.setText(_translate("DCWidget", "0.01", None))
        self.del_a_ipt.setText(_translate("DCWidget", "0.05", None))
        self.del_s1lat_ipt.setText(_translate("DCWidget", "0.02", None))
        self.del_pot1_ipt.setText(_translate("DCWidget", "0.02", None))
        self.del_f1_ipt.setText(_translate("DCWidget", "0.01", None))
        self.label_35.setToolTip(_translate("DCWidget", "Ratio of axial rotation rate vs. mean orbital rate", None))
        self.label_35.setText(_translate("DCWidget", "F2", None))
        self.del_l1_ipt.setText(_translate("DCWidget", "0.01", None))
        self.label_61.setText(_translate("DCWidget", "Parameter increments for approximating derivatives in finite differences. ", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), _translate("DCWidget", "DEL\'s", None))
        self.component_treewidget.headerItem().setText(0, _translate("DCWidget", "Component", None))
        self.component_treewidget.headerItem().setText(1, _translate("DCWidget", "r (R/a)", None))
        self.component_treewidget.headerItem().setText(2, _translate("DCWidget", "Standard Error", None))
        self.result_treewidget.headerItem().setText(0, _translate("DCWidget", "Parameter", None))
        self.result_treewidget.headerItem().setText(1, _translate("DCWidget", "Input", None))
        self.result_treewidget.headerItem().setText(2, _translate("DCWidget", "Adjustment", None))
        self.result_treewidget.headerItem().setText(3, _translate("DCWidget", "Output", None))
        self.result_treewidget.headerItem().setText(4, _translate("DCWidget", "Standard Error", None))
        self.residual_treewidget.headerItem().setText(0, _translate("DCWidget", "Mean Residual for Input Values", None))
        self.residual_treewidget.headerItem().setText(1, _translate("DCWidget", "Mean Residual Predicted", None))
        self.residual_treewidget.headerItem().setText(2, _translate("DCWidget", "Determinant", None))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_7), _translate("DCWidget", "Base Set Results", None))
        self.curvestat_treewidget.headerItem().setText(0, _translate("DCWidget", "Band", None))
        self.curvestat_treewidget.headerItem().setText(1, _translate("DCWidget", "# of Observations", None))
        self.curvestat_treewidget.headerItem().setStatusTip(1, _translate("DCWidget", "Number of observations.", None))
        self.curvestat_treewidget.headerItem().setToolTip(1, _translate("DCWidget", "Number of observations.", None))
        self.curvestat_treewidget.headerItem().setText(2, _translate("DCWidget", "Standard Deviation", None))
        self.curvestat_treewidget.headerItem().setToolTip(2, _translate("DCWidget", "Standard deviation.", None))
        self.curvestat_treewidget.headerItem().setText(3, _translate("DCWidget", "# of Obs. in Phs. Rng.", None))
        self.curvestat_treewidget.headerItem().setToolTip(3, _translate("DCWidget", "Number of observations in phase range as configured in curve properties.", None))
        self.curvestat_treewidget.headerItem().setText(4, _translate("DCWidget", "Std. Dev. in Phs. Rng.", None))
        self.curvestat_treewidget.headerItem().setToolTip(4, _translate("DCWidget", "Standard deviation in phase range as configured in curve properties.", None))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_8), _translate("DCWidget", "Statistical Curve Information", None))
        self.plot_btn.setText(_translate("DCWidget", "Plot", None))
        self.popmain_btn.setText(_translate("DCWidget", "Pop", None))
        self.autoupdate_chk.setText(_translate("DCWidget", "Auto Update", None))
        self.time_combobox.setItemText(0, _translate("DCWidget", "Phase", None))
        self.time_combobox.setItemText(1, _translate("DCWidget", "HJD", None))
        self.uselc_chk.setToolTip(_translate("DCWidget", "Use LC to output higher resolution model curve. [?]", None))
        self.uselc_chk.setWhatsThis(_translate("DCWidget", "This will generate a lcin.active file and run LC, then plot synthetic results onto the observations, instead of reading from dcout.active file. UI will freeze for a moment to compute synthetic points.\n"
"\n"
"Line plotting will be used for LC synthetic points. DC outputs will be plotted with scatter plot.", None))
        self.uselc_chk.setText(_translate("DCWidget", "Use LC", None))

