# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dcwidget.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DCWidget(object):
    def setupUi(self, DCWidget):
        DCWidget.setObjectName(_fromUtf8("DCWidget"))
        DCWidget.resize(1675, 691)
        DCWidget.setMinimumSize(QtCore.QSize(1675, 691))
        DCWidget.setMaximumSize(QtCore.QSize(1675, 691))
        self.rundc2015_btn = QtGui.QPushButton(DCWidget)
        self.rundc2015_btn.setGeometry(QtCore.QRect(245, 20, 191, 91))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.rundc2015_btn.setFont(font)
        self.rundc2015_btn.setObjectName(_fromUtf8("rundc2015_btn"))
        self.updateinputs_btn = QtGui.QPushButton(DCWidget)
        self.updateinputs_btn.setGeometry(QtCore.QRect(465, 20, 191, 41))
        self.updateinputs_btn.setObjectName(_fromUtf8("updateinputs_btn"))
        self.exportresults_btn = QtGui.QPushButton(DCWidget)
        self.exportresults_btn.setGeometry(QtCore.QRect(465, 70, 191, 41))
        self.exportresults_btn.setObjectName(_fromUtf8("exportresults_btn"))
        self.viewlaastdcout_btn = QtGui.QPushButton(DCWidget)
        self.viewlaastdcout_btn.setGeometry(QtCore.QRect(685, 70, 191, 41))
        self.viewlaastdcout_btn.setObjectName(_fromUtf8("viewlaastdcout_btn"))
        self.viewlastdcin_btn = QtGui.QPushButton(DCWidget)
        self.viewlastdcin_btn.setGeometry(QtCore.QRect(685, 20, 191, 41))
        self.viewlastdcin_btn.setObjectName(_fromUtf8("viewlastdcin_btn"))
        self.line_2 = QtGui.QFrame(DCWidget)
        self.line_2.setGeometry(QtCore.QRect(430, 20, 41, 91))
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.label_8 = QtGui.QLabel(DCWidget)
        self.label_8.setGeometry(QtCore.QRect(20, 20, 141, 31))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.iteration_spinbox = QtGui.QSpinBox(DCWidget)
        self.iteration_spinbox.setGeometry(QtCore.QRect(170, 20, 51, 31))
        self.iteration_spinbox.setMinimum(1)
        self.iteration_spinbox.setObjectName(_fromUtf8("iteration_spinbox"))
        self.line_3 = QtGui.QFrame(DCWidget)
        self.line_3.setGeometry(QtCore.QRect(10, 110, 871, 21))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.line_4 = QtGui.QFrame(DCWidget)
        self.line_4.setGeometry(QtCore.QRect(10, 340, 871, 21))
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.tabWidget_2 = QtGui.QTabWidget(DCWidget)
        self.tabWidget_2.setGeometry(QtCore.QRect(10, 130, 871, 211))
        self.tabWidget_2.setTabPosition(QtGui.QTabWidget.West)
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.tabWidget = QtGui.QTabWidget(self.tab_3)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 841, 207))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.f1_chk = QtGui.QCheckBox(self.tab)
        self.f1_chk.setGeometry(QtCore.QRect(10, 80, 70, 17))
        self.f1_chk.setObjectName(_fromUtf8("f1_chk"))
        self.dpdt_chk = QtGui.QCheckBox(self.tab)
        self.dpdt_chk.setGeometry(QtCore.QRect(200, 20, 70, 17))
        self.dpdt_chk.setObjectName(_fromUtf8("dpdt_chk"))
        self.xinc3b_chk = QtGui.QCheckBox(self.tab)
        self.xinc3b_chk.setGeometry(QtCore.QRect(200, 100, 81, 17))
        self.xinc3b_chk.setObjectName(_fromUtf8("xinc3b_chk"))
        self.p3b_chk = QtGui.QCheckBox(self.tab)
        self.p3b_chk.setGeometry(QtCore.QRect(100, 100, 70, 17))
        self.p3b_chk.setObjectName(_fromUtf8("p3b_chk"))
        self.q_chk = QtGui.QCheckBox(self.tab)
        self.q_chk.setGeometry(QtCore.QRect(290, 40, 70, 17))
        self.q_chk.setObjectName(_fromUtf8("q_chk"))
        self.g2_chk = QtGui.QCheckBox(self.tab)
        self.g2_chk.setGeometry(QtCore.QRect(290, 60, 70, 17))
        self.g2_chk.setObjectName(_fromUtf8("g2_chk"))
        self.p0_chk = QtGui.QCheckBox(self.tab)
        self.p0_chk.setGeometry(QtCore.QRect(100, 20, 70, 17))
        self.p0_chk.setObjectName(_fromUtf8("p0_chk"))
        self.perr0_chk = QtGui.QCheckBox(self.tab)
        self.perr0_chk.setGeometry(QtCore.QRect(290, 20, 70, 17))
        self.perr0_chk.setObjectName(_fromUtf8("perr0_chk"))
        self.pshift_chk = QtGui.QCheckBox(self.tab)
        self.pshift_chk.setGeometry(QtCore.QRect(480, 20, 81, 17))
        self.pshift_chk.setObjectName(_fromUtf8("pshift_chk"))
        self.s1long_chk = QtGui.QCheckBox(self.tab)
        self.s1long_chk.setGeometry(QtCore.QRect(100, 120, 91, 17))
        self.s1long_chk.setObjectName(_fromUtf8("s1long_chk"))
        self.s1lat_chk = QtGui.QCheckBox(self.tab)
        self.s1lat_chk.setGeometry(QtCore.QRect(10, 120, 81, 17))
        self.s1lat_chk.setObjectName(_fromUtf8("s1lat_chk"))
        self.e_chk = QtGui.QCheckBox(self.tab)
        self.e_chk.setGeometry(QtCore.QRect(100, 40, 70, 17))
        self.e_chk.setObjectName(_fromUtf8("e_chk"))
        self.s2long_chk = QtGui.QCheckBox(self.tab)
        self.s2long_chk.setGeometry(QtCore.QRect(100, 140, 91, 17))
        self.s2long_chk.setObjectName(_fromUtf8("s2long_chk"))
        self.a_chk = QtGui.QCheckBox(self.tab)
        self.a_chk.setGeometry(QtCore.QRect(10, 40, 70, 17))
        self.a_chk.setObjectName(_fromUtf8("a_chk"))
        self.x1_chk = QtGui.QCheckBox(self.tab)
        self.x1_chk.setGeometry(QtCore.QRect(390, 80, 70, 17))
        self.x1_chk.setObjectName(_fromUtf8("x1_chk"))
        self.alb2_chk = QtGui.QCheckBox(self.tab)
        self.alb2_chk.setGeometry(QtCore.QRect(480, 60, 70, 17))
        self.alb2_chk.setObjectName(_fromUtf8("alb2_chk"))
        self.s1tmax1_chk = QtGui.QCheckBox(self.tab)
        self.s1tmax1_chk.setGeometry(QtCore.QRect(480, 120, 91, 17))
        self.s1tmax1_chk.setObjectName(_fromUtf8("s1tmax1_chk"))
        self.tc3b_chk = QtGui.QCheckBox(self.tab)
        self.tc3b_chk.setGeometry(QtCore.QRect(390, 100, 70, 17))
        self.tc3b_chk.setObjectName(_fromUtf8("tc3b_chk"))
        self.t1_chk = QtGui.QCheckBox(self.tab)
        self.t1_chk.setGeometry(QtCore.QRect(10, 60, 70, 17))
        self.t1_chk.setObjectName(_fromUtf8("t1_chk"))
        self.s1tstart_chk = QtGui.QCheckBox(self.tab)
        self.s1tstart_chk.setGeometry(QtCore.QRect(390, 120, 91, 17))
        self.s1tstart_chk.setObjectName(_fromUtf8("s1tstart_chk"))
        self.dperdt_chk = QtGui.QCheckBox(self.tab)
        self.dperdt_chk.setGeometry(QtCore.QRect(390, 20, 70, 17))
        self.dperdt_chk.setObjectName(_fromUtf8("dperdt_chk"))
        self.s1rad_chk = QtGui.QCheckBox(self.tab)
        self.s1rad_chk.setGeometry(QtCore.QRect(200, 120, 81, 17))
        self.s1rad_chk.setObjectName(_fromUtf8("s1rad_chk"))
        self.s2lat_chk = QtGui.QCheckBox(self.tab)
        self.s2lat_chk.setGeometry(QtCore.QRect(10, 140, 81, 17))
        self.s2lat_chk.setObjectName(_fromUtf8("s2lat_chk"))
        self.s2tstart_chk = QtGui.QCheckBox(self.tab)
        self.s2tstart_chk.setGeometry(QtCore.QRect(390, 140, 91, 17))
        self.s2tstart_chk.setObjectName(_fromUtf8("s2tstart_chk"))
        self.t2_chk = QtGui.QCheckBox(self.tab)
        self.t2_chk.setGeometry(QtCore.QRect(100, 60, 70, 17))
        self.t2_chk.setObjectName(_fromUtf8("t2_chk"))
        self.s2rad_chk = QtGui.QCheckBox(self.tab)
        self.s2rad_chk.setGeometry(QtCore.QRect(200, 140, 81, 17))
        self.s2rad_chk.setObjectName(_fromUtf8("s2rad_chk"))
        self.perr3b_chk = QtGui.QCheckBox(self.tab)
        self.perr3b_chk.setGeometry(QtCore.QRect(480, 100, 91, 17))
        self.perr3b_chk.setObjectName(_fromUtf8("perr3b_chk"))
        self.f2_chk = QtGui.QCheckBox(self.tab)
        self.f2_chk.setGeometry(QtCore.QRect(100, 80, 70, 17))
        self.f2_chk.setObjectName(_fromUtf8("f2_chk"))
        self.x2_chk = QtGui.QCheckBox(self.tab)
        self.x2_chk.setGeometry(QtCore.QRect(480, 80, 70, 17))
        self.x2_chk.setObjectName(_fromUtf8("x2_chk"))
        self.l2_chk = QtGui.QCheckBox(self.tab)
        self.l2_chk.setGeometry(QtCore.QRect(290, 80, 70, 17))
        self.l2_chk.setObjectName(_fromUtf8("l2_chk"))
        self.s2temp_chk = QtGui.QCheckBox(self.tab)
        self.s2temp_chk.setGeometry(QtCore.QRect(290, 140, 91, 17))
        self.s2temp_chk.setObjectName(_fromUtf8("s2temp_chk"))
        self.e3b_chk = QtGui.QCheckBox(self.tab)
        self.e3b_chk.setGeometry(QtCore.QRect(290, 100, 70, 17))
        self.e3b_chk.setObjectName(_fromUtf8("e3b_chk"))
        self.s2tmax1_chk = QtGui.QCheckBox(self.tab)
        self.s2tmax1_chk.setGeometry(QtCore.QRect(480, 140, 91, 17))
        self.s2tmax1_chk.setObjectName(_fromUtf8("s2tmax1_chk"))
        self.incl_chk = QtGui.QCheckBox(self.tab)
        self.incl_chk.setGeometry(QtCore.QRect(200, 40, 70, 17))
        self.incl_chk.setObjectName(_fromUtf8("incl_chk"))
        self.s1temp_chk = QtGui.QCheckBox(self.tab)
        self.s1temp_chk.setGeometry(QtCore.QRect(290, 120, 91, 17))
        self.s1temp_chk.setObjectName(_fromUtf8("s1temp_chk"))
        self.g1_chk = QtGui.QCheckBox(self.tab)
        self.g1_chk.setGeometry(QtCore.QRect(200, 60, 70, 17))
        self.g1_chk.setObjectName(_fromUtf8("g1_chk"))
        self.alb1_chk = QtGui.QCheckBox(self.tab)
        self.alb1_chk.setGeometry(QtCore.QRect(390, 60, 70, 17))
        self.alb1_chk.setObjectName(_fromUtf8("alb1_chk"))
        self.l1_chk = QtGui.QCheckBox(self.tab)
        self.l1_chk.setGeometry(QtCore.QRect(200, 80, 70, 17))
        self.l1_chk.setObjectName(_fromUtf8("l1_chk"))
        self.jd0_chk = QtGui.QCheckBox(self.tab)
        self.jd0_chk.setGeometry(QtCore.QRect(10, 20, 70, 17))
        self.jd0_chk.setObjectName(_fromUtf8("jd0_chk"))
        self.a3b_chk = QtGui.QCheckBox(self.tab)
        self.a3b_chk.setGeometry(QtCore.QRect(10, 100, 70, 17))
        self.a3b_chk.setObjectName(_fromUtf8("a3b_chk"))
        self.el3_chk = QtGui.QCheckBox(self.tab)
        self.el3_chk.setGeometry(QtCore.QRect(580, 100, 70, 17))
        self.el3_chk.setToolTip(_fromUtf8(""))
        self.el3_chk.setObjectName(_fromUtf8("el3_chk"))
        self.desextinc_chk = QtGui.QCheckBox(self.tab)
        self.desextinc_chk.setGeometry(QtCore.QRect(670, 100, 81, 17))
        self.desextinc_chk.setObjectName(_fromUtf8("desextinc_chk"))
        self.s1tend_chk = QtGui.QCheckBox(self.tab)
        self.s1tend_chk.setGeometry(QtCore.QRect(670, 120, 81, 17))
        self.s1tend_chk.setObjectName(_fromUtf8("s1tend_chk"))
        self.pot2_chk = QtGui.QCheckBox(self.tab)
        self.pot2_chk.setGeometry(QtCore.QRect(670, 80, 71, 17))
        self.pot2_chk.setObjectName(_fromUtf8("pot2_chk"))
        self.s2tend_chk = QtGui.QCheckBox(self.tab)
        self.s2tend_chk.setGeometry(QtCore.QRect(670, 140, 81, 17))
        self.s2tend_chk.setObjectName(_fromUtf8("s2tend_chk"))
        self.s1tmax2_chk = QtGui.QCheckBox(self.tab)
        self.s1tmax2_chk.setGeometry(QtCore.QRect(580, 120, 91, 17))
        self.s1tmax2_chk.setObjectName(_fromUtf8("s1tmax2_chk"))
        self.s2tmax2_chk = QtGui.QCheckBox(self.tab)
        self.s2tmax2_chk.setGeometry(QtCore.QRect(580, 140, 91, 17))
        self.s2tmax2_chk.setObjectName(_fromUtf8("s2tmax2_chk"))
        self.pot1_chk = QtGui.QCheckBox(self.tab)
        self.pot1_chk.setGeometry(QtCore.QRect(580, 80, 70, 17))
        self.pot1_chk.setObjectName(_fromUtf8("pot1_chk"))
        self.label_78 = QtGui.QLabel(self.tab)
        self.label_78.setGeometry(QtCore.QRect(570, 18, 201, 20))
        self.label_78.setObjectName(_fromUtf8("label_78"))
        self.marqmul_spinbox = QtGui.QSpinBox(self.tab)
        self.marqmul_spinbox.setGeometry(QtCore.QRect(770, 16, 51, 25))
        self.marqmul_spinbox.setProperty("value", 5)
        self.marqmul_spinbox.setObjectName(_fromUtf8("marqmul_spinbox"))
        self.label_77 = QtGui.QLabel(self.tab)
        self.label_77.setGeometry(QtCore.QRect(570, 52, 181, 21))
        self.label_77.setObjectName(_fromUtf8("label_77"))
        self.vlr_spinbox = QtGui.QDoubleSpinBox(self.tab)
        self.vlr_spinbox.setGeometry(QtCore.QRect(740, 50, 81, 25))
        self.vlr_spinbox.setDecimals(3)
        self.vlr_spinbox.setMaximum(1.0)
        self.vlr_spinbox.setSingleStep(0.01)
        self.vlr_spinbox.setProperty("value", 1.0)
        self.vlr_spinbox.setObjectName(_fromUtf8("vlr_spinbox"))
        self.clearbaseset_btn = QtGui.QPushButton(self.tab)
        self.clearbaseset_btn.setGeometry(QtCore.QRect(760, 80, 61, 35))
        self.clearbaseset_btn.setObjectName(_fromUtf8("clearbaseset_btn"))
        self.addsubset_btn = QtGui.QPushButton(self.tab)
        self.addsubset_btn.setGeometry(QtCore.QRect(760, 125, 61, 35))
        self.addsubset_btn.setObjectName(_fromUtf8("addsubset_btn"))
        self.vgam_chk = QtGui.QCheckBox(self.tab)
        self.vgam_chk.setGeometry(QtCore.QRect(480, 40, 70, 17))
        self.vgam_chk.setObjectName(_fromUtf8("vgam_chk"))
        self.logd_chk = QtGui.QCheckBox(self.tab)
        self.logd_chk.setGeometry(QtCore.QRect(390, 40, 70, 17))
        self.logd_chk.setObjectName(_fromUtf8("logd_chk"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tabWidget_2.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.del_f2_ipt = QtGui.QLineEdit(self.tab_4)
        self.del_f2_ipt.setGeometry(QtCore.QRect(580, 120, 60, 25))
        self.del_f2_ipt.setObjectName(_fromUtf8("del_f2_ipt"))
        self.del_x2_ipt = QtGui.QLineEdit(self.tab_4)
        self.del_x2_ipt.setGeometry(QtCore.QRect(740, 120, 60, 25))
        self.del_x2_ipt.setObjectName(_fromUtf8("del_x2_ipt"))
        self.label_16 = QtGui.QLabel(self.tab_4)
        self.label_16.setGeometry(QtCore.QRect(580, 100, 51, 16))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_15 = QtGui.QLabel(self.tab_4)
        self.label_15.setGeometry(QtCore.QRect(100, 50, 51, 16))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.del_g1_ipt = QtGui.QLineEdit(self.tab_4)
        self.del_g1_ipt.setGeometry(QtCore.QRect(20, 120, 60, 25))
        self.del_g1_ipt.setObjectName(_fromUtf8("del_g1_ipt"))
        self.label_28 = QtGui.QLabel(self.tab_4)
        self.label_28.setGeometry(QtCore.QRect(100, 100, 51, 16))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.del_e_ipt = QtGui.QLineEdit(self.tab_4)
        self.del_e_ipt.setGeometry(QtCore.QRect(100, 70, 60, 25))
        self.del_e_ipt.setObjectName(_fromUtf8("del_e_ipt"))
        self.label_29 = QtGui.QLabel(self.tab_4)
        self.label_29.setGeometry(QtCore.QRect(180, 100, 51, 16))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.del_s1lng_ipt = QtGui.QLineEdit(self.tab_4)
        self.del_s1lng_ipt.setGeometry(QtCore.QRect(100, 170, 60, 25))
        self.del_s1lng_ipt.setObjectName(_fromUtf8("del_s1lng_ipt"))
        self.label_31 = QtGui.QLabel(self.tab_4)
        self.label_31.setGeometry(QtCore.QRect(750, 100, 51, 16))
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.label_34 = QtGui.QLabel(self.tab_4)
        self.label_34.setGeometry(QtCore.QRect(740, 50, 51, 16))
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.del_x1_ipt = QtGui.QLineEdit(self.tab_4)
        self.del_x1_ipt.setGeometry(QtCore.QRect(660, 120, 60, 25))
        self.del_x1_ipt.setObjectName(_fromUtf8("del_x1_ipt"))
        self.label_12 = QtGui.QLabel(self.tab_4)
        self.label_12.setGeometry(QtCore.QRect(260, 150, 61, 16))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.del_alb1_ipt = QtGui.QLineEdit(self.tab_4)
        self.del_alb1_ipt.setGeometry(QtCore.QRect(340, 120, 60, 25))
        self.del_alb1_ipt.setObjectName(_fromUtf8("del_alb1_ipt"))
        self.label_5 = QtGui.QLabel(self.tab_4)
        self.label_5.setGeometry(QtCore.QRect(20, 150, 51, 16))
        self.label_5.setStatusTip(_fromUtf8(""))
        self.label_5.setWhatsThis(_fromUtf8(""))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_19 = QtGui.QLabel(self.tab_4)
        self.label_19.setGeometry(QtCore.QRect(500, 50, 51, 16))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.line_7 = QtGui.QFrame(self.tab_4)
        self.line_7.setGeometry(QtCore.QRect(20, 25, 711, 21))
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.label_20 = QtGui.QLabel(self.tab_4)
        self.label_20.setGeometry(QtCore.QRect(420, 100, 51, 16))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.label_13 = QtGui.QLabel(self.tab_4)
        self.label_13.setGeometry(QtCore.QRect(580, 150, 61, 16))
        self.label_13.setStatusTip(_fromUtf8(""))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.del_s2lng_ipt = QtGui.QLineEdit(self.tab_4)
        self.del_s2lng_ipt.setGeometry(QtCore.QRect(420, 170, 60, 25))
        self.del_s2lng_ipt.setObjectName(_fromUtf8("del_s2lng_ipt"))
        self.del_alb2_ipt = QtGui.QLineEdit(self.tab_4)
        self.del_alb2_ipt.setGeometry(QtCore.QRect(420, 120, 60, 25))
        self.del_alb2_ipt.setObjectName(_fromUtf8("del_alb2_ipt"))
        self.label_21 = QtGui.QLabel(self.tab_4)
        self.label_21.setGeometry(QtCore.QRect(340, 100, 51, 16))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.del_perr0_ipt = QtGui.QLineEdit(self.tab_4)
        self.del_perr0_ipt.setGeometry(QtCore.QRect(420, 70, 60, 25))
        self.del_perr0_ipt.setObjectName(_fromUtf8("del_perr0_ipt"))
        self.label_23 = QtGui.QLabel(self.tab_4)
        self.label_23.setGeometry(QtCore.QRect(580, 50, 51, 16))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.label_14 = QtGui.QLabel(self.tab_4)
        self.label_14.setGeometry(QtCore.QRect(420, 150, 51, 16))
        self.label_14.setStatusTip(_fromUtf8(""))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.del_pot2_ipt = QtGui.QLineEdit(self.tab_4)
        self.del_pot2_ipt.setGeometry(QtCore.QRect(580, 70, 60, 25))
        self.del_pot2_ipt.setObjectName(_fromUtf8("del_pot2_ipt"))
        self.del_g2_ipt = QtGui.QLineEdit(self.tab_4)
        self.del_g2_ipt.setGeometry(QtCore.QRect(100, 120, 60, 25))
        self.del_g2_ipt.setObjectName(_fromUtf8("del_g2_ipt"))
        self.del_l2_ipt = QtGui.QLineEdit(self.tab_4)
        self.del_l2_ipt.setGeometry(QtCore.QRect(740, 70, 60, 25))
        self.del_l2_ipt.setObjectName(_fromUtf8("del_l2_ipt"))
        self.label_7 = QtGui.QLabel(self.tab_4)
        self.label_7.setGeometry(QtCore.QRect(500, 100, 51, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_10 = QtGui.QLabel(self.tab_4)
        self.label_10.setGeometry(QtCore.QRect(340, 150, 51, 16))
        self.label_10.setStatusTip(_fromUtf8(""))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.del_l1_ipt = QtGui.QLineEdit(self.tab_4)
        self.del_l1_ipt.setGeometry(QtCore.QRect(660, 70, 60, 25))
        self.del_l1_ipt.setObjectName(_fromUtf8("del_l1_ipt"))
        self.del_a_ipt = QtGui.QLineEdit(self.tab_4)
        self.del_a_ipt.setGeometry(QtCore.QRect(20, 70, 60, 25))
        self.del_a_ipt.setObjectName(_fromUtf8("del_a_ipt"))
        self.del_f1_ipt = QtGui.QLineEdit(self.tab_4)
        self.del_f1_ipt.setGeometry(QtCore.QRect(500, 120, 60, 25))
        self.del_f1_ipt.setObjectName(_fromUtf8("del_f1_ipt"))
        self.del_s1lat_ipt = QtGui.QLineEdit(self.tab_4)
        self.del_s1lat_ipt.setGeometry(QtCore.QRect(20, 170, 60, 25))
        self.del_s1lat_ipt.setToolTip(_fromUtf8(""))
        self.del_s1lat_ipt.setObjectName(_fromUtf8("del_s1lat_ipt"))
        self.del_s1agrad_ipt = QtGui.QLineEdit(self.tab_4)
        self.del_s1agrad_ipt.setGeometry(QtCore.QRect(180, 170, 60, 25))
        self.del_s1agrad_ipt.setObjectName(_fromUtf8("del_s1agrad_ipt"))
        self.label_6 = QtGui.QLabel(self.tab_4)
        self.label_6.setGeometry(QtCore.QRect(182, 150, 51, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.del_pot1_ipt = QtGui.QLineEdit(self.tab_4)
        self.del_pot1_ipt.setGeometry(QtCore.QRect(500, 70, 60, 25))
        self.del_pot1_ipt.setObjectName(_fromUtf8("del_pot1_ipt"))
        self.del_s1tmpf_ipt = QtGui.QLineEdit(self.tab_4)
        self.del_s1tmpf_ipt.setGeometry(QtCore.QRect(260, 170, 60, 25))
        self.del_s1tmpf_ipt.setObjectName(_fromUtf8("del_s1tmpf_ipt"))
        self.setdeldefaults_btn = QtGui.QPushButton(self.tab_4)
        self.setdeldefaults_btn.setGeometry(QtCore.QRect(660, 160, 141, 35))
        self.setdeldefaults_btn.setObjectName(_fromUtf8("setdeldefaults_btn"))
        self.label_32 = QtGui.QLabel(self.tab_4)
        self.label_32.setGeometry(QtCore.QRect(20, 50, 50, 20))
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.del_pshift_ipt = QtGui.QLineEdit(self.tab_4)
        self.del_pshift_ipt.setGeometry(QtCore.QRect(340, 70, 60, 25))
        self.del_pshift_ipt.setObjectName(_fromUtf8("del_pshift_ipt"))
        self.label_33 = QtGui.QLabel(self.tab_4)
        self.label_33.setGeometry(QtCore.QRect(660, 50, 51, 16))
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.del_s2agrad_ipt = QtGui.QLineEdit(self.tab_4)
        self.del_s2agrad_ipt.setGeometry(QtCore.QRect(500, 170, 60, 25))
        self.del_s2agrad_ipt.setObjectName(_fromUtf8("del_s2agrad_ipt"))
        self.del_s2lat_ipt = QtGui.QLineEdit(self.tab_4)
        self.del_s2lat_ipt.setGeometry(QtCore.QRect(340, 170, 60, 25))
        self.del_s2lat_ipt.setObjectName(_fromUtf8("del_s2lat_ipt"))
        self.label_18 = QtGui.QLabel(self.tab_4)
        self.label_18.setGeometry(QtCore.QRect(20, 100, 51, 16))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.label_30 = QtGui.QLabel(self.tab_4)
        self.label_30.setGeometry(QtCore.QRect(660, 100, 51, 16))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.del_t1_ipt = QtGui.QLineEdit(self.tab_4)
        self.del_t1_ipt.setGeometry(QtCore.QRect(180, 120, 60, 25))
        self.del_t1_ipt.setObjectName(_fromUtf8("del_t1_ipt"))
        self.del_i_ipt = QtGui.QLineEdit(self.tab_4)
        self.del_i_ipt.setGeometry(QtCore.QRect(180, 70, 60, 25))
        self.del_i_ipt.setObjectName(_fromUtf8("del_i_ipt"))
        self.label_22 = QtGui.QLabel(self.tab_4)
        self.label_22.setGeometry(QtCore.QRect(260, 50, 51, 16))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.label_27 = QtGui.QLabel(self.tab_4)
        self.label_27.setGeometry(QtCore.QRect(260, 100, 51, 16))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.label_11 = QtGui.QLabel(self.tab_4)
        self.label_11.setGeometry(QtCore.QRect(180, 50, 51, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_9 = QtGui.QLabel(self.tab_4)
        self.label_9.setGeometry(QtCore.QRect(340, 50, 51, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_26 = QtGui.QLabel(self.tab_4)
        self.label_26.setGeometry(QtCore.QRect(500, 150, 51, 16))
        self.label_26.setStatusTip(_fromUtf8(""))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.del_q_ipt = QtGui.QLineEdit(self.tab_4)
        self.del_q_ipt.setGeometry(QtCore.QRect(260, 70, 60, 25))
        self.del_q_ipt.setObjectName(_fromUtf8("del_q_ipt"))
        self.label_24 = QtGui.QLabel(self.tab_4)
        self.label_24.setGeometry(QtCore.QRect(20, 0, 521, 41))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.del_s2tmpf_ipt = QtGui.QLineEdit(self.tab_4)
        self.del_s2tmpf_ipt.setGeometry(QtCore.QRect(580, 170, 60, 25))
        self.del_s2tmpf_ipt.setObjectName(_fromUtf8("del_s2tmpf_ipt"))
        self.del_t2_ipt = QtGui.QLineEdit(self.tab_4)
        self.del_t2_ipt.setGeometry(QtCore.QRect(260, 120, 60, 25))
        self.del_t2_ipt.setObjectName(_fromUtf8("del_t2_ipt"))
        self.label_25 = QtGui.QLabel(self.tab_4)
        self.label_25.setGeometry(QtCore.QRect(420, 50, 51, 16))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.label_17 = QtGui.QLabel(self.tab_4)
        self.label_17.setGeometry(QtCore.QRect(102, 150, 51, 16))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.tabWidget_2.addTab(self.tab_4, _fromUtf8(""))
        self.ifoc_chk = QtGui.QCheckBox(DCWidget)
        self.ifoc_chk.setEnabled(False)
        self.ifoc_chk.setGeometry(QtCore.QRect(20, 55, 171, 21))
        self.ifoc_chk.setChecked(True)
        self.ifoc_chk.setObjectName(_fromUtf8("ifoc_chk"))
        self.ifder_chk = QtGui.QCheckBox(DCWidget)
        self.ifder_chk.setEnabled(False)
        self.ifder_chk.setGeometry(QtCore.QRect(20, 80, 161, 21))
        self.ifder_chk.setCheckable(True)
        self.ifder_chk.setChecked(True)
        self.ifder_chk.setObjectName(_fromUtf8("ifder_chk"))
        self.tabWidget_3 = QtGui.QTabWidget(DCWidget)
        self.tabWidget_3.setGeometry(QtCore.QRect(10, 360, 871, 321))
        self.tabWidget_3.setObjectName(_fromUtf8("tabWidget_3"))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.result_treewidget = QtGui.QTreeWidget(self.tab_2)
        self.result_treewidget.setGeometry(QtCore.QRect(5, 5, 857, 281))
        self.result_treewidget.setAlternatingRowColors(True)
        self.result_treewidget.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.result_treewidget.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.result_treewidget.setHeaderHidden(False)
        self.result_treewidget.setObjectName(_fromUtf8("result_treewidget"))
        self.result_treewidget.header().setDefaultSectionSize(160)
        self.tabWidget_3.addTab(self.tab_2, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.curvestat_treewidget = QtGui.QTreeWidget(self.tab_5)
        self.curvestat_treewidget.setGeometry(QtCore.QRect(5, 5, 857, 281))
        self.curvestat_treewidget.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.curvestat_treewidget.setIndentation(0)
        self.curvestat_treewidget.setColumnCount(5)
        self.curvestat_treewidget.setObjectName(_fromUtf8("curvestat_treewidget"))
        self.curvestat_treewidget.header().setDefaultSectionSize(160)
        self.tabWidget_3.addTab(self.tab_5, _fromUtf8(""))
        self.plotwidget = QtGui.QWidget(DCWidget)
        self.plotwidget.setGeometry(QtCore.QRect(900, 80, 761, 601))
        self.plotwidget.setObjectName(_fromUtf8("plotwidget"))
        self.autoupdate_chk = QtGui.QCheckBox(DCWidget)
        self.autoupdate_chk.setGeometry(QtCore.QRect(1370, 20, 111, 21))
        self.autoupdate_chk.setObjectName(_fromUtf8("autoupdate_chk"))
        self.line = QtGui.QFrame(DCWidget)
        self.line.setGeometry(QtCore.QRect(900, 60, 761, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.popmain_btn = QtGui.QPushButton(DCWidget)
        self.popmain_btn.setGeometry(QtCore.QRect(1510, 20, 150, 41))
        self.popmain_btn.setObjectName(_fromUtf8("popmain_btn"))
        self.line_6 = QtGui.QFrame(DCWidget)
        self.line_6.setGeometry(QtCore.QRect(1480, 20, 31, 41))
        self.line_6.setFrameShape(QtGui.QFrame.VLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.plot_btn = QtGui.QPushButton(DCWidget)
        self.plot_btn.setGeometry(QtCore.QRect(1255, 20, 100, 41))
        self.plot_btn.setObjectName(_fromUtf8("plot_btn"))
        self.data_combobox = QtGui.QComboBox(DCWidget)
        self.data_combobox.setGeometry(QtCore.QRect(900, 25, 251, 30))
        self.data_combobox.setObjectName(_fromUtf8("data_combobox"))
        self.line_8 = QtGui.QFrame(DCWidget)
        self.line_8.setGeometry(QtCore.QRect(880, 20, 21, 661))
        self.line_8.setFrameShape(QtGui.QFrame.VLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.line_9 = QtGui.QFrame(DCWidget)
        self.line_9.setGeometry(QtCore.QRect(650, 20, 41, 91))
        self.line_9.setFrameShape(QtGui.QFrame.VLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName(_fromUtf8("line_9"))
        self.time_combobox = QtGui.QComboBox(DCWidget)
        self.time_combobox.setGeometry(QtCore.QRect(1160, 25, 81, 30))
        self.time_combobox.setObjectName(_fromUtf8("time_combobox"))
        self.time_combobox.addItem(_fromUtf8(""))
        self.time_combobox.addItem(_fromUtf8(""))
        self.uselc_chk = QtGui.QCheckBox(DCWidget)
        self.uselc_chk.setGeometry(QtCore.QRect(1370, 40, 111, 21))
        self.uselc_chk.setChecked(True)
        self.uselc_chk.setObjectName(_fromUtf8("uselc_chk"))

        self.retranslateUi(DCWidget)
        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(DCWidget)

    def retranslateUi(self, DCWidget):
        DCWidget.setWindowTitle(_translate("DCWidget", "Run Differential Corrections", None))
        self.rundc2015_btn.setText(_translate("DCWidget", "Run DC", None))
        self.updateinputs_btn.setText(_translate("DCWidget", "Copy Results to Inputs", None))
        self.exportresults_btn.setText(_translate("DCWidget", "Export Results", None))
        self.viewlaastdcout_btn.setText(_translate("DCWidget", "View last dcout.active", None))
        self.viewlastdcin_btn.setText(_translate("DCWidget", "View last dcin.active", None))
        self.label_8.setText(_translate("DCWidget", "Number of iterations", None))
        self.f1_chk.setText(_translate("DCWidget", "F1", None))
        self.dpdt_chk.setText(_translate("DCWidget", "dPdt", None))
        self.xinc3b_chk.setText(_translate("DCWidget", "XINC3B", None))
        self.p3b_chk.setText(_translate("DCWidget", "P3B", None))
        self.q_chk.setText(_translate("DCWidget", "Q", None))
        self.g2_chk.setText(_translate("DCWidget", "G2", None))
        self.p0_chk.setText(_translate("DCWidget", "P0", None))
        self.perr0_chk.setText(_translate("DCWidget", "PERR0", None))
        self.pshift_chk.setText(_translate("DCWidget", "PSHIFT", None))
        self.s1long_chk.setText(_translate("DCWidget", "S1 LON", None))
        self.s1lat_chk.setText(_translate("DCWidget", "S1 LAT", None))
        self.e_chk.setText(_translate("DCWidget", "e", None))
        self.s2long_chk.setText(_translate("DCWidget", "S2 LON", None))
        self.a_chk.setText(_translate("DCWidget", "a", None))
        self.x1_chk.setText(_translate("DCWidget", "X1", None))
        self.alb2_chk.setText(_translate("DCWidget", "ALB2", None))
        self.s1tmax1_chk.setText(_translate("DCWidget", "S1 Tmax1", None))
        self.tc3b_chk.setText(_translate("DCWidget", "TC3B", None))
        self.t1_chk.setText(_translate("DCWidget", "T1", None))
        self.s1tstart_chk.setText(_translate("DCWidget", "S1 Tstart", None))
        self.dperdt_chk.setText(_translate("DCWidget", "dPERdt", None))
        self.s1rad_chk.setText(_translate("DCWidget", "S1 RAD", None))
        self.s2lat_chk.setText(_translate("DCWidget", "S2 LAT", None))
        self.s2tstart_chk.setText(_translate("DCWidget", "S2 Tstart", None))
        self.t2_chk.setText(_translate("DCWidget", "T2", None))
        self.s2rad_chk.setText(_translate("DCWidget", "S2 RAD", None))
        self.perr3b_chk.setText(_translate("DCWidget", "PERR3B", None))
        self.f2_chk.setText(_translate("DCWidget", "F2", None))
        self.x2_chk.setText(_translate("DCWidget", "X2", None))
        self.l2_chk.setText(_translate("DCWidget", "L2", None))
        self.s2temp_chk.setText(_translate("DCWidget", "S2 TEMP", None))
        self.e3b_chk.setText(_translate("DCWidget", "E3B", None))
        self.s2tmax1_chk.setText(_translate("DCWidget", "S2 Tmax1", None))
        self.incl_chk.setText(_translate("DCWidget", "INCL", None))
        self.s1temp_chk.setText(_translate("DCWidget", "S1 TEMP", None))
        self.g1_chk.setText(_translate("DCWidget", "G1", None))
        self.alb1_chk.setText(_translate("DCWidget", "ALB1", None))
        self.l1_chk.setText(_translate("DCWidget", "L1", None))
        self.jd0_chk.setText(_translate("DCWidget", "JD0", None))
        self.a3b_chk.setText(_translate("DCWidget", "A3B", None))
        self.el3_chk.setText(_translate("DCWidget", "EL3", None))
        self.desextinc_chk.setToolTip(_translate("DCWidget", "DESEXTINC", None))
        self.desextinc_chk.setText(_translate("DCWidget", "DEXT", None))
        self.s1tend_chk.setText(_translate("DCWidget", "S1 Tend", None))
        self.pot2_chk.setText(_translate("DCWidget", "POT2", None))
        self.s2tend_chk.setText(_translate("DCWidget", "S2 Tend", None))
        self.s1tmax2_chk.setText(_translate("DCWidget", "S1 Tmax2", None))
        self.s2tmax2_chk.setText(_translate("DCWidget", "S2 Tmax2", None))
        self.pot1_chk.setText(_translate("DCWidget", "POT1", None))
        self.label_78.setToolTip(_translate("DCWidget", "λ to be used in the Levenberg-Marquardt method.", None))
        self.label_78.setStatusTip(_translate("DCWidget", "XLAMDA", None))
        self.label_78.setText(_translate("DCWidget", "Marquardt multiplier  1.000d −", None))
        self.label_77.setToolTip(_translate("DCWidget", "The fraction of DC’s output corrections to be applied to the input parameters to form the output parameters.", None))
        self.label_77.setStatusTip(_translate("DCWidget", "VLR", None))
        self.label_77.setText(_translate("DCWidget", "Vector Lenght Reduction", None))
        self.clearbaseset_btn.setText(_translate("DCWidget", "Clear", None))
        self.addsubset_btn.setText(_translate("DCWidget", "Add", None))
        self.vgam_chk.setText(_translate("DCWidget", "VGAM", None))
        self.logd_chk.setText(_translate("DCWidget", "logD", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("DCWidget", "Base Set", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("DCWidget", "KEEP\'s", None))
        self.del_f2_ipt.setText(_translate("DCWidget", "0.01", None))
        self.del_x2_ipt.setText(_translate("DCWidget", "0.01", None))
        self.label_16.setToolTip(_translate("DCWidget", "Ratio of axial rotation rate vs. mean orbital rate", None))
        self.label_16.setText(_translate("DCWidget", "F2", None))
        self.label_15.setToolTip(_translate("DCWidget", "Orbit eccentricity", None))
        self.label_15.setText(_translate("DCWidget", "e", None))
        self.del_g1_ipt.setText(_translate("DCWidget", "0.01", None))
        self.label_28.setToolTip(_translate("DCWidget", "Gravity darkening exponent", None))
        self.label_28.setText(_translate("DCWidget", "G2", None))
        self.del_e_ipt.setText(_translate("DCWidget", "0.001", None))
        self.label_29.setToolTip(_translate("DCWidget", "Average surface temperature in 10000K", None))
        self.label_29.setText(_translate("DCWidget", "T1", None))
        self.del_s1lng_ipt.setText(_translate("DCWidget", "0.02", None))
        self.label_31.setToolTip(_translate("DCWidget", "Limb darkening coefficient", None))
        self.label_31.setText(_translate("DCWidget", "X2", None))
        self.label_34.setToolTip(_translate("DCWidget", "Relative monochromatic luminosity", None))
        self.label_34.setText(_translate("DCWidget", "L2", None))
        self.del_x1_ipt.setText(_translate("DCWidget", "0.01", None))
        self.label_12.setToolTip(_translate("DCWidget", "Spot 1 Temperature Factor", None))
        self.label_12.setText(_translate("DCWidget", "S1 TEMP", None))
        self.del_alb1_ipt.setText(_translate("DCWidget", "0.05", None))
        self.label_5.setToolTip(_translate("DCWidget", "Spot 1 Latitude", None))
        self.label_5.setText(_translate("DCWidget", "S1 LAT", None))
        self.label_19.setToolTip(_translate("DCWidget", "Surface potential", None))
        self.label_19.setText(_translate("DCWidget", "POT1", None))
        self.label_20.setToolTip(_translate("DCWidget", "Bolometric Albedo", None))
        self.label_20.setText(_translate("DCWidget", "ALB2", None))
        self.label_13.setToolTip(_translate("DCWidget", "Spot 2 Temperature Factor", None))
        self.label_13.setText(_translate("DCWidget", "S2 TEMP", None))
        self.del_s2lng_ipt.setText(_translate("DCWidget", "0.001", None))
        self.del_alb2_ipt.setText(_translate("DCWidget", "0.05", None))
        self.label_21.setToolTip(_translate("DCWidget", "Bolometric Albedo", None))
        self.label_21.setText(_translate("DCWidget", "ALB1", None))
        self.del_perr0_ipt.setText(_translate("DCWidget", "0.01", None))
        self.label_23.setToolTip(_translate("DCWidget", "Surface potential", None))
        self.label_23.setText(_translate("DCWidget", "POT2", None))
        self.label_14.setToolTip(_translate("DCWidget", "Spot 2 Longitude", None))
        self.label_14.setText(_translate("DCWidget", "S2 LON", None))
        self.del_pot2_ipt.setText(_translate("DCWidget", "0.02", None))
        self.del_g2_ipt.setText(_translate("DCWidget", "0.01", None))
        self.del_l2_ipt.setText(_translate("DCWidget", "0.01", None))
        self.label_7.setToolTip(_translate("DCWidget", "Ratio of axial rotation rate vs. mean orbital rate", None))
        self.label_7.setText(_translate("DCWidget", "F1", None))
        self.label_10.setToolTip(_translate("DCWidget", "Spot 2 Latitude", None))
        self.label_10.setText(_translate("DCWidget", "S2 LAT", None))
        self.del_l1_ipt.setText(_translate("DCWidget", "0.01", None))
        self.del_a_ipt.setText(_translate("DCWidget", "0.05", None))
        self.del_f1_ipt.setText(_translate("DCWidget", "0.01", None))
        self.del_s1lat_ipt.setText(_translate("DCWidget", "0.02", None))
        self.del_s1agrad_ipt.setText(_translate("DCWidget", "0.001", None))
        self.label_6.setToolTip(_translate("DCWidget", "Spot 1 Angular Radius", None))
        self.label_6.setText(_translate("DCWidget", "S1 RAD", None))
        self.del_pot1_ipt.setText(_translate("DCWidget", "0.02", None))
        self.del_s1tmpf_ipt.setText(_translate("DCWidget", "0.02", None))
        self.setdeldefaults_btn.setText(_translate("DCWidget", "Set Defaults", None))
        self.label_32.setToolTip(_translate("DCWidget", "Semi-major axis", None))
        self.label_32.setText(_translate("DCWidget", "a", None))
        self.del_pshift_ipt.setText(_translate("DCWidget", "0.002", None))
        self.label_33.setToolTip(_translate("DCWidget", "Relative monochromatic luminosity", None))
        self.label_33.setText(_translate("DCWidget", "L1", None))
        self.del_s2agrad_ipt.setText(_translate("DCWidget", "0.0001", None))
        self.del_s2lat_ipt.setText(_translate("DCWidget", "0.02", None))
        self.label_18.setToolTip(_translate("DCWidget", "Gravity darkening exponent", None))
        self.label_18.setText(_translate("DCWidget", "G1", None))
        self.label_30.setToolTip(_translate("DCWidget", "Limb darkening coefficient", None))
        self.label_30.setText(_translate("DCWidget", "X1", None))
        self.del_t1_ipt.setText(_translate("DCWidget", "0.02", None))
        self.del_i_ipt.setText(_translate("DCWidget", "0.2", None))
        self.label_22.setToolTip(_translate("DCWidget", "Mass ratio, star 2/star 1", None))
        self.label_22.setText(_translate("DCWidget", "Q", None))
        self.label_27.setToolTip(_translate("DCWidget", "Average surface temperature in 10000K", None))
        self.label_27.setText(_translate("DCWidget", "T2", None))
        self.label_11.setToolTip(_translate("DCWidget", "Inclination", None))
        self.label_11.setText(_translate("DCWidget", "i", None))
        self.label_9.setToolTip(_translate("DCWidget", "Phase Shift", None))
        self.label_9.setText(_translate("DCWidget", "PSHIFT", None))
        self.label_26.setToolTip(_translate("DCWidget", "Spot 2 Angular Radius", None))
        self.label_26.setText(_translate("DCWidget", "S2 RAD", None))
        self.del_q_ipt.setText(_translate("DCWidget", "0.003", None))
        self.label_24.setText(_translate("DCWidget", "Parameter increments for approximating derivatives in finite differences. ", None))
        self.del_s2tmpf_ipt.setText(_translate("DCWidget", "0.02", None))
        self.del_t2_ipt.setText(_translate("DCWidget", "0.02", None))
        self.label_25.setToolTip(_translate("DCWidget", "V Gamma", None))
        self.label_25.setText(_translate("DCWidget", "PERR0", None))
        self.label_17.setToolTip(_translate("DCWidget", "Spot 1 Longitude", None))
        self.label_17.setText(_translate("DCWidget", "S1 LON", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("DCWidget", "DEL\'s", None))
        self.ifoc_chk.setToolTip(_translate("DCWidget", "Write extra two columns of \"observed\" and \"computed\" data in dcout file.", None))
        self.ifoc_chk.setStatusTip(_translate("DCWidget", "IFOC", None))
        self.ifoc_chk.setText(_translate("DCWidget", "Output O - C", None))
        self.ifder_chk.setToolTip(_translate("DCWidget", "Write matrix of parameter derivatives and residuals, or observational equations. [?]", None))
        self.ifder_chk.setStatusTip(_translate("DCWidget", "IFDER", None))
        self.ifder_chk.setWhatsThis(_translate("DCWidget", "<html><head/><body><p>Write control integer IFDER is set to 1 for “yes, write” or to 0 for “do not write.” It decides whether the matrix of parameter derivatives and residuals, or observational equations (both the unweighted and the weighted versions), are written. Since the observational equations for the first iteration pertain to the input parameters (and they change only a little for subsequent iterations), they are written only for the base set.</p></body></html>", None))
        self.ifder_chk.setText(_translate("DCWidget", "Output derivatives", None))
        self.result_treewidget.headerItem().setText(0, _translate("DCWidget", "Parameter", None))
        self.result_treewidget.headerItem().setText(1, _translate("DCWidget", "Input", None))
        self.result_treewidget.headerItem().setText(2, _translate("DCWidget", "Adjustment", None))
        self.result_treewidget.headerItem().setText(3, _translate("DCWidget", "Output", None))
        self.result_treewidget.headerItem().setText(4, _translate("DCWidget", "Standard Error", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_2), _translate("DCWidget", "Base Set Results", None))
        self.curvestat_treewidget.headerItem().setText(0, _translate("DCWidget", "Band", None))
        self.curvestat_treewidget.headerItem().setText(1, _translate("DCWidget", "# of Observations", None))
        self.curvestat_treewidget.headerItem().setStatusTip(1, _translate("DCWidget", "Number of observations.", None))
        self.curvestat_treewidget.headerItem().setToolTip(1, _translate("DCWidget", "Number of observations.", None))
        self.curvestat_treewidget.headerItem().setText(2, _translate("DCWidget", "Standard Deviation", None))
        self.curvestat_treewidget.headerItem().setToolTip(2, _translate("DCWidget", "Standard deviation.", None))
        self.curvestat_treewidget.headerItem().setText(3, _translate("DCWidget", "# of Obs. in Phs. Rng.", None))
        self.curvestat_treewidget.headerItem().setToolTip(3, _translate("DCWidget", "Number of observations in phase range as configured in curve properties.", None))
        self.curvestat_treewidget.headerItem().setText(4, _translate("DCWidget", "Std. Dev. in Phs. Rng.", None))
        self.curvestat_treewidget.headerItem().setToolTip(4, _translate("DCWidget", "Standard deviation in phase range as configured in curve properties.", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_5), _translate("DCWidget", "Statistical Curve Information", None))
        self.autoupdate_chk.setText(_translate("DCWidget", "Auto Update", None))
        self.popmain_btn.setText(_translate("DCWidget", "Pop Plot Window", None))
        self.plot_btn.setText(_translate("DCWidget", "Plot", None))
        self.time_combobox.setItemText(0, _translate("DCWidget", "Phase", None))
        self.time_combobox.setItemText(1, _translate("DCWidget", "HJD", None))
        self.uselc_chk.setToolTip(_translate("DCWidget", "Use LC to output higher resolution model curve. [?]", None))
        self.uselc_chk.setWhatsThis(_translate("DCWidget", "This will generate a lcin.active file and run LC, then plot synthetic results onto the observations, instead of reading from dcout.active file. UI will freeze for a moment to compute synthetic points.\n"
"\n"
"Line plotting will be used for LC synthetic points. DC outputs will be plotted with scatter plot.", None))
        self.uselc_chk.setText(_translate("DCWidget", "Use LC", None))

