# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lineprofilewidget.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_LineProfileWidget(object):
    def setupUi(self, LineProfileWidget):
        LineProfileWidget.setObjectName(_fromUtf8("LineProfileWidget"))
        LineProfileWidget.resize(1033, 742)
        self.horizontalLayout_2 = QtGui.QHBoxLayout(LineProfileWidget)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.tabWidget = QtGui.QTabWidget(LineProfileWidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.tab)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setMargin(6)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.plot_btn = QtGui.QPushButton(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot_btn.sizePolicy().hasHeightForWidth())
        self.plot_btn.setSizePolicy(sizePolicy)
        self.plot_btn.setMinimumSize(QtCore.QSize(125, 0))
        self.plot_btn.setObjectName(_fromUtf8("plot_btn"))
        self.horizontalLayout.addWidget(self.plot_btn)
        self.export_btn = QtGui.QPushButton(self.tab)
        self.export_btn.setMinimumSize(QtCore.QSize(125, 0))
        self.export_btn.setObjectName(_fromUtf8("export_btn"))
        self.horizontalLayout.addWidget(self.export_btn)
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout.addWidget(self.label_3)
        self.phase_spinbox = QtGui.QDoubleSpinBox(self.tab)
        self.phase_spinbox.setDecimals(4)
        self.phase_spinbox.setSingleStep(0.1)
        self.phase_spinbox.setProperty("value", 0.25)
        self.phase_spinbox.setObjectName(_fromUtf8("phase_spinbox"))
        self.horizontalLayout.addWidget(self.phase_spinbox)
        self.gridLayout_3.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.plot_widget = QtGui.QWidget(self.tab)
        self.plot_widget.setMinimumSize(QtCore.QSize(0, 350))
        self.plot_widget.setObjectName(_fromUtf8("plot_widget"))
        self.gridLayout_3.addWidget(self.plot_widget, 3, 0, 1, 3)
        self.line_3 = QtGui.QFrame(self.tab)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout_3.addWidget(self.line_3, 1, 0, 1, 3)
        self.line = QtGui.QFrame(self.tab)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_3.addWidget(self.line, 0, 1, 1, 1)
        self.s1_groupbox = QtGui.QGroupBox(self.tab)
        self.s1_groupbox.setCheckable(True)
        self.s1_groupbox.setObjectName(_fromUtf8("s1_groupbox"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.s1_groupbox)
        self.horizontalLayout_4.setMargin(5)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.s1_contslope_spinbox = QtGui.QDoubleSpinBox(self.s1_groupbox)
        self.s1_contslope_spinbox.setDecimals(5)
        self.s1_contslope_spinbox.setObjectName(_fromUtf8("s1_contslope_spinbox"))
        self.gridLayout.addWidget(self.s1_contslope_spinbox, 1, 3, 1, 1)
        self.s1_subgrid_spinbox = QtGui.QSpinBox(self.s1_groupbox)
        self.s1_subgrid_spinbox.setMinimum(1)
        self.s1_subgrid_spinbox.setMaximum(999)
        self.s1_subgrid_spinbox.setProperty("value", 1)
        self.s1_subgrid_spinbox.setObjectName(_fromUtf8("s1_subgrid_spinbox"))
        self.gridLayout.addWidget(self.s1_subgrid_spinbox, 1, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.s1_groupbox)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 1, 0, 1, 1)
        self.s1_add_btn = QtGui.QPushButton(self.s1_groupbox)
        self.s1_add_btn.setObjectName(_fromUtf8("s1_add_btn"))
        self.gridLayout.addWidget(self.s1_add_btn, 0, 4, 1, 1)
        self.s1_contscale_spinbox = QtGui.QDoubleSpinBox(self.s1_groupbox)
        self.s1_contscale_spinbox.setDecimals(5)
        self.s1_contscale_spinbox.setMinimum(0.0)
        self.s1_contscale_spinbox.setMaximum(99.0)
        self.s1_contscale_spinbox.setProperty("value", 1.0)
        self.s1_contscale_spinbox.setObjectName(_fromUtf8("s1_contscale_spinbox"))
        self.gridLayout.addWidget(self.s1_contscale_spinbox, 0, 3, 1, 1)
        self.label_4 = QtGui.QLabel(self.s1_groupbox)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 0, 2, 1, 1)
        self.s1_remove_btn = QtGui.QPushButton(self.s1_groupbox)
        self.s1_remove_btn.setObjectName(_fromUtf8("s1_remove_btn"))
        self.gridLayout.addWidget(self.s1_remove_btn, 1, 4, 1, 1)
        self.label_5 = QtGui.QLabel(self.s1_groupbox)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 1, 2, 1, 1)
        self.label = QtGui.QLabel(self.s1_groupbox)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.s1_binwidth_spinbox = QtGui.QDoubleSpinBox(self.s1_groupbox)
        self.s1_binwidth_spinbox.setDecimals(6)
        self.s1_binwidth_spinbox.setMinimum(1e-06)
        self.s1_binwidth_spinbox.setMaximum(1.0)
        self.s1_binwidth_spinbox.setSingleStep(0.0001)
        self.s1_binwidth_spinbox.setProperty("value", 1e-05)
        self.s1_binwidth_spinbox.setObjectName(_fromUtf8("s1_binwidth_spinbox"))
        self.gridLayout.addWidget(self.s1_binwidth_spinbox, 0, 1, 1, 1)
        self.s1_treewidget = QtGui.QTreeWidget(self.s1_groupbox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.s1_treewidget.sizePolicy().hasHeightForWidth())
        self.s1_treewidget.setSizePolicy(sizePolicy)
        self.s1_treewidget.setMinimumSize(QtCore.QSize(0, 150))
        self.s1_treewidget.setMaximumSize(QtCore.QSize(16777215, 270))
        self.s1_treewidget.setObjectName(_fromUtf8("s1_treewidget"))
        self.gridLayout.addWidget(self.s1_treewidget, 2, 0, 1, 5)
        self.horizontalLayout_4.addLayout(self.gridLayout)
        self.gridLayout_3.addWidget(self.s1_groupbox, 0, 0, 1, 1)
        self.s2_groupbox = QtGui.QGroupBox(self.tab)
        self.s2_groupbox.setCheckable(True)
        self.s2_groupbox.setObjectName(_fromUtf8("s2_groupbox"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.s2_groupbox)
        self.verticalLayout_2.setMargin(5)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.s2_add_btn = QtGui.QPushButton(self.s2_groupbox)
        self.s2_add_btn.setObjectName(_fromUtf8("s2_add_btn"))
        self.gridLayout_2.addWidget(self.s2_add_btn, 0, 5, 1, 1)
        self.label_11 = QtGui.QLabel(self.s2_groupbox)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_2.addWidget(self.label_11, 1, 3, 1, 1)
        self.s2_contscale_spinbox = QtGui.QDoubleSpinBox(self.s2_groupbox)
        self.s2_contscale_spinbox.setDecimals(5)
        self.s2_contscale_spinbox.setMaximum(99.0)
        self.s2_contscale_spinbox.setProperty("value", 1.0)
        self.s2_contscale_spinbox.setObjectName(_fromUtf8("s2_contscale_spinbox"))
        self.gridLayout_2.addWidget(self.s2_contscale_spinbox, 0, 4, 1, 1)
        self.s2_treewidget = QtGui.QTreeWidget(self.s2_groupbox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.s2_treewidget.sizePolicy().hasHeightForWidth())
        self.s2_treewidget.setSizePolicy(sizePolicy)
        self.s2_treewidget.setMinimumSize(QtCore.QSize(0, 150))
        self.s2_treewidget.setMaximumSize(QtCore.QSize(16777215, 270))
        self.s2_treewidget.setObjectName(_fromUtf8("s2_treewidget"))
        self.gridLayout_2.addWidget(self.s2_treewidget, 2, 1, 1, 5)
        self.label_15 = QtGui.QLabel(self.s2_groupbox)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_2.addWidget(self.label_15, 0, 1, 1, 1)
        self.s2_contslope_spinbox = QtGui.QDoubleSpinBox(self.s2_groupbox)
        self.s2_contslope_spinbox.setDecimals(5)
        self.s2_contslope_spinbox.setMaximum(1.0)
        self.s2_contslope_spinbox.setObjectName(_fromUtf8("s2_contslope_spinbox"))
        self.gridLayout_2.addWidget(self.s2_contslope_spinbox, 1, 4, 1, 1)
        self.s2_binwidth_spinbox = QtGui.QDoubleSpinBox(self.s2_groupbox)
        self.s2_binwidth_spinbox.setDecimals(6)
        self.s2_binwidth_spinbox.setMinimum(1e-06)
        self.s2_binwidth_spinbox.setMaximum(1.0)
        self.s2_binwidth_spinbox.setSingleStep(0.0001)
        self.s2_binwidth_spinbox.setProperty("value", 1e-05)
        self.s2_binwidth_spinbox.setObjectName(_fromUtf8("s2_binwidth_spinbox"))
        self.gridLayout_2.addWidget(self.s2_binwidth_spinbox, 0, 2, 1, 1)
        self.label_13 = QtGui.QLabel(self.s2_groupbox)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_2.addWidget(self.label_13, 1, 1, 1, 1)
        self.s2_subgrid_spinbox = QtGui.QSpinBox(self.s2_groupbox)
        self.s2_subgrid_spinbox.setMinimum(1)
        self.s2_subgrid_spinbox.setObjectName(_fromUtf8("s2_subgrid_spinbox"))
        self.gridLayout_2.addWidget(self.s2_subgrid_spinbox, 1, 2, 1, 1)
        self.s2_remove_btn = QtGui.QPushButton(self.s2_groupbox)
        self.s2_remove_btn.setObjectName(_fromUtf8("s2_remove_btn"))
        self.gridLayout_2.addWidget(self.s2_remove_btn, 1, 5, 1, 1)
        self.label_12 = QtGui.QLabel(self.s2_groupbox)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_2.addWidget(self.label_12, 0, 3, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.gridLayout_3.addWidget(self.s2_groupbox, 0, 2, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout_3)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.tabWidget)

        self.retranslateUi(LineProfileWidget)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(LineProfileWidget)

    def retranslateUi(self, LineProfileWidget):
        LineProfileWidget.setWindowTitle(_translate("LineProfileWidget", "Spectral Line Profiles", None))
        self.plot_btn.setText(_translate("LineProfileWidget", "Plot", None))
        self.export_btn.setText(_translate("LineProfileWidget", "Export", None))
        self.label_3.setText(_translate("LineProfileWidget", "Phase", None))
        self.s1_groupbox.setTitle(_translate("LineProfileWidget", "Star 1", None))
        self.label_6.setToolTip(_translate("LineProfileWidget", "<html><head/><body><p>Grid fineness for micro-integration on each surface element. Subgrid = 1 means that there is no micro-integration. Subgrid = n breaks each surface element into n<span style=\" vertical-align:super;\">2</span> pieces, each with its own radial velocity, thus improving integration accuracy.</p></body></html>", None))
        self.label_6.setText(_translate("LineProfileWidget", "Subgrid", None))
        self.s1_add_btn.setText(_translate("LineProfileWidget", "Add", None))
        self.label_4.setToolTip(_translate("LineProfileWidget", "The continuum scale (continuum flux at the reference wavelength). The unit is decided by\n"
"the user.", None))
        self.label_4.setText(_translate("LineProfileWidget", "Cont. Scale", None))
        self.s1_remove_btn.setText(_translate("LineProfileWidget", "Remove", None))
        self.label_5.setToolTip(_translate("LineProfileWidget", "The continuum slope in flux units per micron.", None))
        self.label_5.setText(_translate("LineProfileWidget", "Cont. Slope", None))
        self.label.setToolTip(_translate("LineProfileWidget", "The bin width in microns. Too small a bin width gives noisy profiles. Too large a bin\n"
"width gives insufficient spectral resolution.", None))
        self.label.setText(_translate("LineProfileWidget", "Bin Width", None))
        self.s1_treewidget.headerItem().setText(0, _translate("LineProfileWidget", "Wavelength", None))
        self.s1_treewidget.headerItem().setToolTip(0, _translate("LineProfileWidget", "The line rest wavelength in microns", None))
        self.s1_treewidget.headerItem().setText(1, _translate("LineProfileWidget", "Equivalent Width", None))
        self.s1_treewidget.headerItem().setToolTip(1, _translate("LineProfileWidget", "<html><head/><body><p>The line equivalent width for a line, in microns—the traditional measure of line strength.</p><p>Absorption and emission lines both have positive equivalent width by program (WD) convention. Whether a line is in absorption or emission is controlled by parameters Rectangle Line Depth.</p></body></html>", None))
        self.s1_treewidget.headerItem().setText(2, _translate("LineProfileWidget", "Rectangle Line Depth", None))
        self.s1_treewidget.headerItem().setToolTip(2, _translate("LineProfileWidget", "<html><head/><body><p>Rectangular line depth for a line. </p><p>Line profiles are formed by binning of Doppler shifted elements that have rectangular profiles, each with a depth and a width. The user supplies the depth and the program (WD) then calculates the rectangular line width needed to reproduce the specified equivalent width. The depth is relative to a unit continuum, so 0.80000 means that 80 percent of the continuum flux is missing within the rectangular profile element, or that the residual flux is 20 percent of the continuum. Negative depths correspond to emission lines, so −0.50000 means 50 percent above the continuum. Depths must be less than 1.0000 (i.e. an absorption line cannot go to zero flux or below), but can be less than −1.0000 (an emission line can go arbitrarily high).</p></body></html>", None))
        self.s1_treewidget.headerItem().setText(3, _translate("LineProfileWidget", "KKS", None))
        self.s1_treewidget.headerItem().setToolTip(3, _translate("LineProfileWidget", "<html><head/><body><p>This integer specifies a surface region associated with a given spectral line. </p><p>If KKS=0, the line is not specific to a location but applies to the entire star. </p><p>If KKS=1, then the line applies only to the first spot on that star</p><p>if KKS=2 it applies only to the second spot, and so on. </p><p>Naturally the star must have spots for this scheme to work, but the spots need not be hot or cool spots—they can have temperature factors of unity. </p><p>Negative KKS specifies avoidance of regions. Thus KKS=−4 means that the spectral line applies everywhere on the star except within spot 4. If you find this confusing, just set KKS=0 and the line applies in the old simple way—everywhere on the star.</p></body></html>", None))
        self.s2_groupbox.setTitle(_translate("LineProfileWidget", "Star 2", None))
        self.s2_add_btn.setText(_translate("LineProfileWidget", "Add", None))
        self.label_11.setToolTip(_translate("LineProfileWidget", "The continuum slope in flux units per micron.", None))
        self.label_11.setText(_translate("LineProfileWidget", "Cont. Slope", None))
        self.s2_treewidget.headerItem().setText(0, _translate("LineProfileWidget", "Wavelength", None))
        self.s2_treewidget.headerItem().setToolTip(0, _translate("LineProfileWidget", "The line rest wavelength in microns", None))
        self.s2_treewidget.headerItem().setText(1, _translate("LineProfileWidget", "Equivalent Width", None))
        self.s2_treewidget.headerItem().setToolTip(1, _translate("LineProfileWidget", "<html><head/><body><p>The line equivalent width for a line, in microns—the traditional measure of line strength.</p><p>Absorption and emission lines both have positive equivalent width by program (WD) convention. Whether a line is in absorption or emission is controlled by parameters Rectangle Line Depth.</p></body></html>", None))
        self.s2_treewidget.headerItem().setText(2, _translate("LineProfileWidget", "Rectangle Line Depth", None))
        self.s2_treewidget.headerItem().setToolTip(2, _translate("LineProfileWidget", "<html><head/><body><p>Rectangular line depth for a line. </p><p>Line profiles are formed by binning of Doppler shifted elements that have rectangular profiles, each with a depth and a width. The user supplies the depth and the program (WD) then calculates the rectangular line width needed to reproduce the specified equivalent width. The depth is relative to a unit continuum, so 0.80000 means that 80 percent of the continuum flux is missing within the rectangular profile element, or that the residual flux is 20 percent of the continuum. Negative depths correspond to emission lines, so −0.50000 means 50 percent above the continuum. Depths must be less than 1.0000 (i.e. an absorption line cannot go to zero flux or below), but can be less than −1.0000 (an emission line can go arbitrarily high).</p></body></html>", None))
        self.s2_treewidget.headerItem().setText(3, _translate("LineProfileWidget", "KKS", None))
        self.s2_treewidget.headerItem().setToolTip(3, _translate("LineProfileWidget", "<html><head/><body><p>This integer specifies a surface region associated with a given spectral line. </p><p>If KKS=0, the line is not specific to a location but applies to the entire star. </p><p>If KKS=1, then the line applies only to the first spot on that star</p><p>if KKS=2 it applies only to the second spot, and so on. </p><p>Naturally the star must have spots for this scheme to work, but the spots need not be hot or cool spots—they can have temperature factors of unity. </p><p>Negative KKS specifies avoidance of regions. Thus KKS=−4 means that the spectral line applies everywhere on the star except within spot 4. If you find this confusing, just set KKS=0 and the line applies in the old simple way—everywhere on the star.</p></body></html>", None))
        self.label_15.setToolTip(_translate("LineProfileWidget", "The bin width in microns. Too small a bin width gives noisy profiles. Too large a bin\n"
"width gives insufficient spectral resolution.", None))
        self.label_15.setText(_translate("LineProfileWidget", "Bin Width", None))
        self.label_13.setToolTip(_translate("LineProfileWidget", "<html><head/><body><p>Grid fineness for micro-integration on each surface element. Subgrid = 1 means that there is no micro-integration. Subgrid = n breaks each surface element into n<span style=\" vertical-align:super;\">2</span> pieces, each with its own radial velocity, thus improving integration accuracy.</p></body></html>", None))
        self.label_13.setText(_translate("LineProfileWidget", "Subgrid", None))
        self.s2_remove_btn.setText(_translate("LineProfileWidget", "Remove", None))
        self.label_12.setToolTip(_translate("LineProfileWidget", "The continuum scale (continuum flux at the reference wavelength). The unit is decided by\n"
"the user.", None))
        self.label_12.setText(_translate("LineProfileWidget", "Cont. Scale", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("LineProfileWidget", "Plot Line Profiles", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("LineProfileWidget", "Animation", None))

