# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Wed Nov 22 11:03:02 2017
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(780, 345)
        MainWindow.setMinimumSize(QtCore.QSize(780, 345))
        MainWindow.setMaximumSize(QtCore.QSize(780, 345))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 40, 761, 281))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.jdphs_combobox = QtGui.QComboBox(self.tab)
        self.jdphs_combobox.setGeometry(QtCore.QRect(50, 10, 81, 22))
        self.jdphs_combobox.setObjectName(_fromUtf8("jdphs_combobox"))
        self.jdphs_combobox.addItem(_fromUtf8(""))
        self.jdphs_combobox.addItem(_fromUtf8(""))
        self.label_41 = QtGui.QLabel(self.tab)
        self.label_41.setGeometry(QtCore.QRect(10, 10, 41, 21))
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.pshift_ipt = QtGui.QLineEdit(self.tab)
        self.pshift_ipt.setGeometry(QtCore.QRect(250, 60, 71, 20))
        self.pshift_ipt.setObjectName(_fromUtf8("pshift_ipt"))
        self.rm_ipt = QtGui.QLineEdit(self.tab)
        self.rm_ipt.setGeometry(QtCore.QRect(580, 160, 71, 20))
        self.rm_ipt.setObjectName(_fromUtf8("rm_ipt"))
        self.dpdt_ipt = QtGui.QLineEdit(self.tab)
        self.dpdt_ipt.setGeometry(QtCore.QRect(170, 60, 71, 20))
        self.dpdt_ipt.setObjectName(_fromUtf8("dpdt_ipt"))
        self.label_42 = QtGui.QLabel(self.tab)
        self.label_42.setGeometry(QtCore.QRect(410, 40, 46, 21))
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.label_67 = QtGui.QLabel(self.tab)
        self.label_67.setGeometry(QtCore.QRect(490, 140, 51, 16))
        self.label_67.setObjectName(_fromUtf8("label_67"))
        self.label_75 = QtGui.QLabel(self.tab)
        self.label_75.setGeometry(QtCore.QRect(250, 190, 51, 16))
        self.label_75.setObjectName(_fromUtf8("label_75"))
        self.dpclog_ipt = QtGui.QLineEdit(self.tab)
        self.dpclog_ipt.setGeometry(QtCore.QRect(660, 160, 71, 20))
        self.dpclog_ipt.setObjectName(_fromUtf8("dpclog_ipt"))
        self.abunin_ipt = QtGui.QLineEdit(self.tab)
        self.abunin_ipt.setGeometry(QtCore.QRect(490, 160, 71, 20))
        self.abunin_ipt.setObjectName(_fromUtf8("abunin_ipt"))
        self.perr0_ipt = QtGui.QLineEdit(self.tab)
        self.perr0_ipt.setGeometry(QtCore.QRect(10, 110, 71, 20))
        self.perr0_ipt.setToolTip(_fromUtf8(""))
        self.perr0_ipt.setObjectName(_fromUtf8("perr0_ipt"))
        self.label_74 = QtGui.QLabel(self.tab)
        self.label_74.setGeometry(QtCore.QRect(170, 190, 51, 16))
        self.label_74.setObjectName(_fromUtf8("label_74"))
        self.nga_spinbox = QtGui.QSpinBox(self.tab)
        self.nga_spinbox.setGeometry(QtCore.QRect(410, 60, 42, 20))
        self.nga_spinbox.setMinimum(1)
        self.nga_spinbox.setMaximum(10)
        self.nga_spinbox.setObjectName(_fromUtf8("nga_spinbox"))
        self.label_62 = QtGui.QLabel(self.tab)
        self.label_62.setGeometry(QtCore.QRect(90, 140, 51, 21))
        self.label_62.setObjectName(_fromUtf8("label_62"))
        self.label_47 = QtGui.QLabel(self.tab)
        self.label_47.setGeometry(QtCore.QRect(330, 40, 51, 21))
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.phsv_ipt = QtGui.QLineEdit(self.tab)
        self.phsv_ipt.setGeometry(QtCore.QRect(170, 210, 71, 20))
        self.phsv_ipt.setObjectName(_fromUtf8("phsv_ipt"))
        self.label_45 = QtGui.QLabel(self.tab)
        self.label_45.setGeometry(QtCore.QRect(170, 40, 51, 21))
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.label_64 = QtGui.QLabel(self.tab)
        self.label_64.setGeometry(QtCore.QRect(410, 140, 51, 16))
        self.label_64.setObjectName(_fromUtf8("label_64"))
        self.jd0_ipt = QtGui.QLineEdit(self.tab)
        self.jd0_ipt.setGeometry(QtCore.QRect(10, 60, 71, 20))
        self.jd0_ipt.setObjectName(_fromUtf8("jd0_ipt"))
        self.label_55 = QtGui.QLabel(self.tab)
        self.label_55.setGeometry(QtCore.QRect(10, 90, 51, 21))
        self.label_55.setObjectName(_fromUtf8("label_55"))
        self.label_83 = QtGui.QLabel(self.tab)
        self.label_83.setGeometry(QtCore.QRect(660, 140, 51, 16))
        self.label_83.setStatusTip(_fromUtf8(""))
        self.label_83.setObjectName(_fromUtf8("label_83"))
        self.tavc_ipt = QtGui.QLineEdit(self.tab)
        self.tavc_ipt.setGeometry(QtCore.QRect(90, 210, 71, 20))
        self.tavc_ipt.setObjectName(_fromUtf8("tavc_ipt"))
        self.vgam_ipt = QtGui.QLineEdit(self.tab)
        self.vgam_ipt.setGeometry(QtCore.QRect(330, 160, 71, 20))
        self.vgam_ipt.setObjectName(_fromUtf8("vgam_ipt"))
        self.label_46 = QtGui.QLabel(self.tab)
        self.label_46.setGeometry(QtCore.QRect(250, 40, 71, 21))
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.label_80 = QtGui.QLabel(self.tab)
        self.label_80.setGeometry(QtCore.QRect(580, 140, 51, 16))
        self.label_80.setStatusTip(_fromUtf8(""))
        self.label_80.setObjectName(_fromUtf8("label_80"))
        self.label_57 = QtGui.QLabel(self.tab)
        self.label_57.setGeometry(QtCore.QRect(170, 90, 51, 21))
        self.label_57.setObjectName(_fromUtf8("label_57"))
        self.label_60 = QtGui.QLabel(self.tab)
        self.label_60.setGeometry(QtCore.QRect(170, 140, 51, 21))
        self.label_60.setObjectName(_fromUtf8("label_60"))
        self.label_44 = QtGui.QLabel(self.tab)
        self.label_44.setGeometry(QtCore.QRect(90, 40, 51, 21))
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.label_63 = QtGui.QLabel(self.tab)
        self.label_63.setGeometry(QtCore.QRect(330, 140, 51, 16))
        self.label_63.setObjectName(_fromUtf8("label_63"))
        self.p0_ipt = QtGui.QLineEdit(self.tab)
        self.p0_ipt.setGeometry(QtCore.QRect(90, 60, 71, 20))
        self.p0_ipt.setObjectName(_fromUtf8("p0_ipt"))
        self.the_ipt = QtGui.QLineEdit(self.tab)
        self.the_ipt.setGeometry(QtCore.QRect(170, 110, 71, 20))
        self.the_ipt.setToolTip(_fromUtf8(""))
        self.the_ipt.setObjectName(_fromUtf8("the_ipt"))
        self.pcsv_ipt = QtGui.QLineEdit(self.tab)
        self.pcsv_ipt.setGeometry(QtCore.QRect(250, 210, 71, 20))
        self.pcsv_ipt.setObjectName(_fromUtf8("pcsv_ipt"))
        self.delph_ipt = QtGui.QLineEdit(self.tab)
        self.delph_ipt.setGeometry(QtCore.QRect(330, 60, 71, 20))
        self.delph_ipt.setObjectName(_fromUtf8("delph_ipt"))
        self.tavh_ipt = QtGui.QLineEdit(self.tab)
        self.tavh_ipt.setGeometry(QtCore.QRect(10, 210, 71, 20))
        self.tavh_ipt.setObjectName(_fromUtf8("tavh_ipt"))
        self.xincl_ipt = QtGui.QLineEdit(self.tab)
        self.xincl_ipt.setGeometry(QtCore.QRect(410, 160, 71, 20))
        self.xincl_ipt.setObjectName(_fromUtf8("xincl_ipt"))
        self.e_ipt = QtGui.QLineEdit(self.tab)
        self.e_ipt.setGeometry(QtCore.QRect(90, 160, 71, 20))
        self.e_ipt.setToolTip(_fromUtf8(""))
        self.e_ipt.setObjectName(_fromUtf8("e_ipt"))
        self.vunit_ipt = QtGui.QLineEdit(self.tab)
        self.vunit_ipt.setGeometry(QtCore.QRect(250, 110, 71, 20))
        self.vunit_ipt.setToolTip(_fromUtf8(""))
        self.vunit_ipt.setObjectName(_fromUtf8("vunit_ipt"))
        self.label_43 = QtGui.QLabel(self.tab)
        self.label_43.setGeometry(QtCore.QRect(10, 40, 51, 21))
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.label_70 = QtGui.QLabel(self.tab)
        self.label_70.setGeometry(QtCore.QRect(90, 190, 51, 16))
        self.label_70.setObjectName(_fromUtf8("label_70"))
        self.f2_ipt = QtGui.QLineEdit(self.tab)
        self.f2_ipt.setGeometry(QtCore.QRect(250, 160, 71, 20))
        self.f2_ipt.setToolTip(_fromUtf8(""))
        self.f2_ipt.setObjectName(_fromUtf8("f2_ipt"))
        self.label_71 = QtGui.QLabel(self.tab)
        self.label_71.setGeometry(QtCore.QRect(10, 190, 51, 16))
        self.label_71.setObjectName(_fromUtf8("label_71"))
        self.dperdt_ipt = QtGui.QLineEdit(self.tab)
        self.dperdt_ipt.setGeometry(QtCore.QRect(90, 110, 71, 20))
        self.dperdt_ipt.setToolTip(_fromUtf8(""))
        self.dperdt_ipt.setObjectName(_fromUtf8("dperdt_ipt"))
        self.a_ipt = QtGui.QLineEdit(self.tab)
        self.a_ipt.setGeometry(QtCore.QRect(10, 160, 71, 20))
        self.a_ipt.setToolTip(_fromUtf8(""))
        self.a_ipt.setObjectName(_fromUtf8("a_ipt"))
        self.label_61 = QtGui.QLabel(self.tab)
        self.label_61.setGeometry(QtCore.QRect(250, 140, 51, 21))
        self.label_61.setObjectName(_fromUtf8("label_61"))
        self.label_59 = QtGui.QLabel(self.tab)
        self.label_59.setGeometry(QtCore.QRect(10, 140, 51, 21))
        self.label_59.setObjectName(_fromUtf8("label_59"))
        self.label_56 = QtGui.QLabel(self.tab)
        self.label_56.setGeometry(QtCore.QRect(90, 90, 51, 21))
        self.label_56.setObjectName(_fromUtf8("label_56"))
        self.label_58 = QtGui.QLabel(self.tab)
        self.label_58.setGeometry(QtCore.QRect(250, 90, 51, 21))
        self.label_58.setObjectName(_fromUtf8("label_58"))
        self.f1_ipt = QtGui.QLineEdit(self.tab)
        self.f1_ipt.setGeometry(QtCore.QRect(170, 160, 71, 20))
        self.f1_ipt.setToolTip(_fromUtf8(""))
        self.f1_ipt.setObjectName(_fromUtf8("f1_ipt"))
        self.loadwidget_btn = QtGui.QPushButton(self.tab)
        self.loadwidget_btn.setGeometry(QtCore.QRect(610, 10, 131, 31))
        self.loadwidget_btn.setObjectName(_fromUtf8("loadwidget_btn"))
        self.spotconfigure_btn = QtGui.QPushButton(self.tab)
        self.spotconfigure_btn.setGeometry(QtCore.QRect(610, 50, 131, 31))
        self.spotconfigure_btn.setObjectName(_fromUtf8("spotconfigure_btn"))
        self.maglite_combobox = QtGui.QComboBox(self.tab)
        self.maglite_combobox.setGeometry(QtCore.QRect(230, 10, 91, 22))
        self.maglite_combobox.setObjectName(_fromUtf8("maglite_combobox"))
        self.maglite_combobox.addItem(_fromUtf8(""))
        self.maglite_combobox.addItem(_fromUtf8(""))
        self.label_38 = QtGui.QLabel(self.tab)
        self.label_38.setGeometry(QtCore.QRect(170, 10, 71, 21))
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.label_90 = QtGui.QLabel(self.tab_3)
        self.label_90.setGeometry(QtCore.QRect(230, 80, 41, 21))
        self.label_90.setObjectName(_fromUtf8("label_90"))
        self.gr1_spinbox = QtGui.QDoubleSpinBox(self.tab_3)
        self.gr1_spinbox.setGeometry(QtCore.QRect(350, 40, 62, 22))
        self.gr1_spinbox.setDecimals(3)
        self.gr1_spinbox.setMaximum(1.0)
        self.gr1_spinbox.setSingleStep(0.1)
        self.gr1_spinbox.setProperty("value", 0.32)
        self.gr1_spinbox.setObjectName(_fromUtf8("gr1_spinbox"))
        self.alb2_spinbox = QtGui.QDoubleSpinBox(self.tab_3)
        self.alb2_spinbox.setGeometry(QtCore.QRect(270, 80, 41, 22))
        self.alb2_spinbox.setDecimals(1)
        self.alb2_spinbox.setMaximum(1.0)
        self.alb2_spinbox.setSingleStep(0.1)
        self.alb2_spinbox.setProperty("value", 0.5)
        self.alb2_spinbox.setObjectName(_fromUtf8("alb2_spinbox"))
        self.label_91 = QtGui.QLabel(self.tab_3)
        self.label_91.setGeometry(QtCore.QRect(640, 80, 31, 21))
        self.label_91.setObjectName(_fromUtf8("label_91"))
        self.ld2_combobox = QtGui.QComboBox(self.tab_3)
        self.ld2_combobox.setGeometry(QtCore.QRect(50, 210, 111, 22))
        self.ld2_combobox.setObjectName(_fromUtf8("ld2_combobox"))
        self.ld2_combobox.addItem(_fromUtf8(""))
        self.ld2_combobox.addItem(_fromUtf8(""))
        self.ld2_combobox.addItem(_fromUtf8(""))
        self.n1_spinbox = QtGui.QSpinBox(self.tab_3)
        self.n1_spinbox.setGeometry(QtCore.QRect(580, 40, 42, 20))
        self.n1_spinbox.setMinimum(1)
        self.n1_spinbox.setMaximum(100)
        self.n1_spinbox.setProperty("value", 30)
        self.n1_spinbox.setObjectName(_fromUtf8("n1_spinbox"))
        self.gr2_spinbox = QtGui.QDoubleSpinBox(self.tab_3)
        self.gr2_spinbox.setGeometry(QtCore.QRect(350, 80, 62, 22))
        self.gr2_spinbox.setDecimals(3)
        self.gr2_spinbox.setMaximum(1.0)
        self.gr2_spinbox.setSingleStep(0.1)
        self.gr2_spinbox.setProperty("value", 0.32)
        self.gr2_spinbox.setObjectName(_fromUtf8("gr2_spinbox"))
        self.ld2_chk = QtGui.QCheckBox(self.tab_3)
        self.ld2_chk.setGeometry(QtCore.QRect(180, 210, 16, 21))
        self.ld2_chk.setText(_fromUtf8(""))
        self.ld2_chk.setChecked(True)
        self.ld2_chk.setObjectName(_fromUtf8("ld2_chk"))
        self.label_92 = QtGui.QLabel(self.tab_3)
        self.label_92.setGeometry(QtCore.QRect(560, 80, 21, 21))
        self.label_92.setObjectName(_fromUtf8("label_92"))
        self.label_93 = QtGui.QLabel(self.tab_3)
        self.label_93.setGeometry(QtCore.QRect(320, 40, 31, 21))
        self.label_93.setObjectName(_fromUtf8("label_93"))
        self.label_94 = QtGui.QLabel(self.tab_3)
        self.label_94.setGeometry(QtCore.QRect(340, 190, 51, 16))
        self.label_94.setObjectName(_fromUtf8("label_94"))
        self.xbol1_ipt = QtGui.QLineEdit(self.tab_3)
        self.xbol1_ipt.setGeometry(QtCore.QRect(240, 160, 71, 20))
        self.xbol1_ipt.setObjectName(_fromUtf8("xbol1_ipt"))
        self.label_95 = QtGui.QLabel(self.tab_3)
        self.label_95.setGeometry(QtCore.QRect(560, 40, 21, 21))
        self.label_95.setObjectName(_fromUtf8("label_95"))
        self.line_2 = QtGui.QFrame(self.tab_3)
        self.line_2.setGeometry(QtCore.QRect(440, 110, 271, 21))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.ifat2_combobox = QtGui.QComboBox(self.tab_3)
        self.ifat2_combobox.setGeometry(QtCore.QRect(60, 80, 151, 22))
        self.ifat2_combobox.setObjectName(_fromUtf8("ifat2_combobox"))
        self.ifat2_combobox.addItem(_fromUtf8(""))
        self.ifat2_combobox.addItem(_fromUtf8(""))
        self.label_96 = QtGui.QLabel(self.tab_3)
        self.label_96.setGeometry(QtCore.QRect(640, 40, 31, 21))
        self.label_96.setObjectName(_fromUtf8("label_96"))
        self.label_97 = QtGui.QLabel(self.tab_3)
        self.label_97.setGeometry(QtCore.QRect(240, 190, 51, 16))
        self.label_97.setObjectName(_fromUtf8("label_97"))
        self.xbol2_ipt = QtGui.QLineEdit(self.tab_3)
        self.xbol2_ipt.setGeometry(QtCore.QRect(240, 210, 71, 20))
        self.xbol2_ipt.setObjectName(_fromUtf8("xbol2_ipt"))
        self.label_36 = QtGui.QLabel(self.tab_3)
        self.label_36.setGeometry(QtCore.QRect(20, 210, 31, 21))
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.alb1_spinbox = QtGui.QDoubleSpinBox(self.tab_3)
        self.alb1_spinbox.setGeometry(QtCore.QRect(270, 40, 41, 22))
        self.alb1_spinbox.setDecimals(1)
        self.alb1_spinbox.setMaximum(1.0)
        self.alb1_spinbox.setSingleStep(0.1)
        self.alb1_spinbox.setProperty("value", 0.5)
        self.alb1_spinbox.setObjectName(_fromUtf8("alb1_spinbox"))
        self.nref_spinbox = QtGui.QSpinBox(self.tab_3)
        self.nref_spinbox.setGeometry(QtCore.QRect(520, 190, 42, 20))
        self.nref_spinbox.setMaximum(9)
        self.nref_spinbox.setObjectName(_fromUtf8("nref_spinbox"))
        self.mref_chk = QtGui.QCheckBox(self.tab_3)
        self.mref_chk.setGeometry(QtCore.QRect(520, 160, 71, 21))
        self.mref_chk.setObjectName(_fromUtf8("mref_chk"))
        self.ybol1_ipt = QtGui.QLineEdit(self.tab_3)
        self.ybol1_ipt.setGeometry(QtCore.QRect(340, 160, 71, 20))
        self.ybol1_ipt.setObjectName(_fromUtf8("ybol1_ipt"))
        self.line_3 = QtGui.QFrame(self.tab_3)
        self.line_3.setGeometry(QtCore.QRect(420, 20, 20, 91))
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.label_98 = QtGui.QLabel(self.tab_3)
        self.label_98.setGeometry(QtCore.QRect(240, 140, 51, 16))
        self.label_98.setObjectName(_fromUtf8("label_98"))
        self.line_4 = QtGui.QFrame(self.tab_3)
        self.line_4.setGeometry(QtCore.QRect(420, 130, 20, 101))
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.n2_spinbox = QtGui.QSpinBox(self.tab_3)
        self.n2_spinbox.setGeometry(QtCore.QRect(580, 80, 42, 20))
        self.n2_spinbox.setMinimum(1)
        self.n2_spinbox.setMaximum(100)
        self.n2_spinbox.setProperty("value", 30)
        self.n2_spinbox.setObjectName(_fromUtf8("n2_spinbox"))
        self.label_34 = QtGui.QLabel(self.tab_3)
        self.label_34.setGeometry(QtCore.QRect(570, 190, 31, 21))
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.label_99 = QtGui.QLabel(self.tab_3)
        self.label_99.setGeometry(QtCore.QRect(320, 80, 31, 21))
        self.label_99.setObjectName(_fromUtf8("label_99"))
        self.label_100 = QtGui.QLabel(self.tab_3)
        self.label_100.setGeometry(QtCore.QRect(20, 40, 31, 21))
        self.label_100.setObjectName(_fromUtf8("label_100"))
        self.ipb_chk = QtGui.QCheckBox(self.tab_3)
        self.ipb_chk.setGeometry(QtCore.QRect(590, 160, 41, 21))
        self.ipb_chk.setChecked(False)
        self.ipb_chk.setObjectName(_fromUtf8("ipb_chk"))
        self.label_101 = QtGui.QLabel(self.tab_3)
        self.label_101.setGeometry(QtCore.QRect(340, 140, 51, 16))
        self.label_101.setObjectName(_fromUtf8("label_101"))
        self.line = QtGui.QFrame(self.tab_3)
        self.line.setGeometry(QtCore.QRect(20, 110, 401, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.label_35 = QtGui.QLabel(self.tab_3)
        self.label_35.setGeometry(QtCore.QRect(20, 160, 31, 21))
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.n1l_spinbox = QtGui.QSpinBox(self.tab_3)
        self.n1l_spinbox.setGeometry(QtCore.QRect(670, 40, 42, 20))
        self.n1l_spinbox.setMinimum(1)
        self.n1l_spinbox.setMaximum(100)
        self.n1l_spinbox.setProperty("value", 15)
        self.n1l_spinbox.setObjectName(_fromUtf8("n1l_spinbox"))
        self.label_102 = QtGui.QLabel(self.tab_3)
        self.label_102.setGeometry(QtCore.QRect(230, 40, 41, 21))
        self.label_102.setObjectName(_fromUtf8("label_102"))
        self.ld1_combobox = QtGui.QComboBox(self.tab_3)
        self.ld1_combobox.setGeometry(QtCore.QRect(50, 160, 111, 22))
        self.ld1_combobox.setObjectName(_fromUtf8("ld1_combobox"))
        self.ld1_combobox.addItem(_fromUtf8(""))
        self.ld1_combobox.addItem(_fromUtf8(""))
        self.ld1_combobox.addItem(_fromUtf8(""))
        self.label_103 = QtGui.QLabel(self.tab_3)
        self.label_103.setGeometry(QtCore.QRect(20, 80, 31, 21))
        self.label_103.setObjectName(_fromUtf8("label_103"))
        self.ld1_chk = QtGui.QCheckBox(self.tab_3)
        self.ld1_chk.setGeometry(QtCore.QRect(180, 160, 16, 21))
        self.ld1_chk.setText(_fromUtf8(""))
        self.ld1_chk.setChecked(True)
        self.ld1_chk.setObjectName(_fromUtf8("ld1_chk"))
        self.n2l_spinbox = QtGui.QSpinBox(self.tab_3)
        self.n2l_spinbox.setGeometry(QtCore.QRect(670, 80, 42, 20))
        self.n2l_spinbox.setMinimum(1)
        self.n2l_spinbox.setMaximum(100)
        self.n2l_spinbox.setProperty("value", 15)
        self.n2l_spinbox.setObjectName(_fromUtf8("n2l_spinbox"))
        self.ifat1_combobox = QtGui.QComboBox(self.tab_3)
        self.ifat1_combobox.setGeometry(QtCore.QRect(60, 40, 151, 22))
        self.ifat1_combobox.setObjectName(_fromUtf8("ifat1_combobox"))
        self.ifat1_combobox.addItem(_fromUtf8(""))
        self.ifat1_combobox.addItem(_fromUtf8(""))
        self.ybol2_ipt = QtGui.QLineEdit(self.tab_3)
        self.ybol2_ipt.setGeometry(QtCore.QRect(340, 210, 71, 20))
        self.ybol2_ipt.setObjectName(_fromUtf8("ybol2_ipt"))
        self.label = QtGui.QLabel(self.tab_3)
        self.label.setGeometry(QtCore.QRect(20, 130, 91, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.tab_3)
        self.label_2.setGeometry(QtCore.QRect(560, 20, 31, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.tab_3)
        self.label_3.setGeometry(QtCore.QRect(440, 130, 151, 21))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.isym_combobox = QtGui.QComboBox(self.tab_3)
        self.isym_combobox.setGeometry(QtCore.QRect(440, 60, 111, 22))
        self.isym_combobox.setObjectName(_fromUtf8("isym_combobox"))
        self.isym_combobox.addItem(_fromUtf8(""))
        self.isym_combobox.addItem(_fromUtf8(""))
        self.label_50 = QtGui.QLabel(self.tab_3)
        self.label_50.setGeometry(QtCore.QRect(440, 30, 111, 21))
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.label_51 = QtGui.QLabel(self.tab_3)
        self.label_51.setGeometry(QtCore.QRect(160, 139, 51, 21))
        self.label_51.setObjectName(_fromUtf8("label_51"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.label_104 = QtGui.QLabel(self.tab_4)
        self.label_104.setGeometry(QtCore.QRect(100, 50, 51, 16))
        self.label_104.setStatusTip(_fromUtf8(""))
        self.label_104.setObjectName(_fromUtf8("label_104"))
        self.a3b_ipt = QtGui.QLineEdit(self.tab_4)
        self.a3b_ipt.setGeometry(QtCore.QRect(20, 70, 71, 20))
        self.a3b_ipt.setObjectName(_fromUtf8("a3b_ipt"))
        self.label_105 = QtGui.QLabel(self.tab_4)
        self.label_105.setGeometry(QtCore.QRect(180, 50, 51, 16))
        self.label_105.setStatusTip(_fromUtf8(""))
        self.label_105.setObjectName(_fromUtf8("label_105"))
        self.perr3b_ipt = QtGui.QLineEdit(self.tab_4)
        self.perr3b_ipt.setGeometry(QtCore.QRect(100, 120, 71, 20))
        self.perr3b_ipt.setObjectName(_fromUtf8("perr3b_ipt"))
        self.label_106 = QtGui.QLabel(self.tab_4)
        self.label_106.setGeometry(QtCore.QRect(180, 100, 51, 16))
        self.label_106.setStatusTip(_fromUtf8(""))
        self.label_106.setObjectName(_fromUtf8("label_106"))
        self.e3b_ipt = QtGui.QLineEdit(self.tab_4)
        self.e3b_ipt.setGeometry(QtCore.QRect(20, 120, 71, 20))
        self.e3b_ipt.setObjectName(_fromUtf8("e3b_ipt"))
        self.tc3b_ipt = QtGui.QLineEdit(self.tab_4)
        self.tc3b_ipt.setGeometry(QtCore.QRect(180, 120, 71, 20))
        self.tc3b_ipt.setObjectName(_fromUtf8("tc3b_ipt"))
        self.label_107 = QtGui.QLabel(self.tab_4)
        self.label_107.setGeometry(QtCore.QRect(20, 50, 51, 16))
        self.label_107.setObjectName(_fromUtf8("label_107"))
        self.p3b_ipt = QtGui.QLineEdit(self.tab_4)
        self.p3b_ipt.setGeometry(QtCore.QRect(100, 70, 71, 20))
        self.p3b_ipt.setObjectName(_fromUtf8("p3b_ipt"))
        self.label_108 = QtGui.QLabel(self.tab_4)
        self.label_108.setGeometry(QtCore.QRect(100, 100, 51, 16))
        self.label_108.setStatusTip(_fromUtf8(""))
        self.label_108.setObjectName(_fromUtf8("label_108"))
        self.label_109 = QtGui.QLabel(self.tab_4)
        self.label_109.setGeometry(QtCore.QRect(20, 100, 51, 16))
        self.label_109.setObjectName(_fromUtf8("label_109"))
        self.xinc3b_ipt = QtGui.QLineEdit(self.tab_4)
        self.xinc3b_ipt.setGeometry(QtCore.QRect(180, 70, 71, 20))
        self.xinc3b_ipt.setObjectName(_fromUtf8("xinc3b_ipt"))
        self.if3b_chk = QtGui.QCheckBox(self.tab_4)
        self.if3b_chk.setGeometry(QtCore.QRect(10, 10, 251, 21))
        self.if3b_chk.setObjectName(_fromUtf8("if3b_chk"))
        self.line_5 = QtGui.QFrame(self.tab_4)
        self.line_5.setGeometry(QtCore.QRect(10, 30, 241, 21))
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.del_s2tmpf_ipt = QtGui.QLineEdit(self.tab_5)
        self.del_s2tmpf_ipt.setGeometry(QtCore.QRect(652, 60, 71, 20))
        self.del_s2tmpf_ipt.setObjectName(_fromUtf8("del_s2tmpf_ipt"))
        self.del_pshift_ipt = QtGui.QLineEdit(self.tab_5)
        self.del_pshift_ipt.setGeometry(QtCore.QRect(378, 110, 71, 20))
        self.del_pshift_ipt.setObjectName(_fromUtf8("del_pshift_ipt"))
        self.del_t1_ipt = QtGui.QLineEdit(self.tab_5)
        self.del_t1_ipt.setGeometry(QtCore.QRect(190, 160, 71, 20))
        self.del_t1_ipt.setObjectName(_fromUtf8("del_t1_ipt"))
        self.label_27 = QtGui.QLabel(self.tab_5)
        self.label_27.setGeometry(QtCore.QRect(286, 140, 51, 16))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.label_5 = QtGui.QLabel(self.tab_5)
        self.label_5.setGeometry(QtCore.QRect(12, 40, 51, 16))
        self.label_5.setStatusTip(_fromUtf8(""))
        self.label_5.setWhatsThis(_fromUtf8(""))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.del_f1_ipt = QtGui.QLineEdit(self.tab_5)
        self.del_f1_ipt.setGeometry(QtCore.QRect(194, 110, 71, 20))
        self.del_f1_ipt.setObjectName(_fromUtf8("del_f1_ipt"))
        self.del_s1lng_ipt = QtGui.QLineEdit(self.tab_5)
        self.del_s1lng_ipt.setGeometry(QtCore.QRect(104, 60, 71, 20))
        self.del_s1lng_ipt.setObjectName(_fromUtf8("del_s1lng_ipt"))
        self.label_16 = QtGui.QLabel(self.tab_5)
        self.label_16.setGeometry(QtCore.QRect(286, 90, 51, 16))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.del_s2lat_ipt = QtGui.QLineEdit(self.tab_5)
        self.del_s2lat_ipt.setGeometry(QtCore.QRect(378, 60, 71, 20))
        self.del_s2lat_ipt.setObjectName(_fromUtf8("del_s2lat_ipt"))
        self.label_7 = QtGui.QLabel(self.tab_5)
        self.label_7.setGeometry(QtCore.QRect(194, 90, 51, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_6 = QtGui.QLabel(self.tab_5)
        self.label_6.setGeometry(QtCore.QRect(194, 40, 51, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_15 = QtGui.QLabel(self.tab_5)
        self.label_15.setGeometry(QtCore.QRect(104, 90, 51, 16))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.del_f2_ipt = QtGui.QLineEdit(self.tab_5)
        self.del_f2_ipt.setGeometry(QtCore.QRect(286, 110, 71, 20))
        self.del_f2_ipt.setObjectName(_fromUtf8("del_f2_ipt"))
        self.del_g1_ipt = QtGui.QLineEdit(self.tab_5)
        self.del_g1_ipt.setGeometry(QtCore.QRect(10, 160, 71, 20))
        self.del_g1_ipt.setObjectName(_fromUtf8("del_g1_ipt"))
        self.del_i_ipt = QtGui.QLineEdit(self.tab_5)
        self.del_i_ipt.setGeometry(QtCore.QRect(560, 110, 71, 20))
        self.del_i_ipt.setObjectName(_fromUtf8("del_i_ipt"))
        self.label_8 = QtGui.QLabel(self.tab_5)
        self.label_8.setGeometry(QtCore.QRect(378, 40, 51, 16))
        self.label_8.setStatusTip(_fromUtf8(""))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_28 = QtGui.QLabel(self.tab_5)
        self.label_28.setGeometry(QtCore.QRect(100, 140, 51, 16))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.label_19 = QtGui.QLabel(self.tab_5)
        self.label_19.setGeometry(QtCore.QRect(560, 140, 51, 16))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.label_20 = QtGui.QLabel(self.tab_5)
        self.label_20.setGeometry(QtCore.QRect(470, 140, 51, 16))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.label_10 = QtGui.QLabel(self.tab_5)
        self.label_10.setGeometry(QtCore.QRect(560, 90, 51, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_21 = QtGui.QLabel(self.tab_5)
        self.label_21.setGeometry(QtCore.QRect(378, 140, 51, 16))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.label_18 = QtGui.QLabel(self.tab_5)
        self.label_18.setGeometry(QtCore.QRect(10, 140, 51, 16))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.del_s2agrad_ipt = QtGui.QLineEdit(self.tab_5)
        self.del_s2agrad_ipt.setGeometry(QtCore.QRect(560, 60, 71, 20))
        self.del_s2agrad_ipt.setObjectName(_fromUtf8("del_s2agrad_ipt"))
        self.label_22 = QtGui.QLabel(self.tab_5)
        self.label_22.setGeometry(QtCore.QRect(650, 90, 51, 16))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.del_s1agrad_ipt = QtGui.QLineEdit(self.tab_5)
        self.del_s1agrad_ipt.setGeometry(QtCore.QRect(192, 60, 71, 20))
        self.del_s1agrad_ipt.setObjectName(_fromUtf8("del_s1agrad_ipt"))
        self.label_11 = QtGui.QLabel(self.tab_5)
        self.label_11.setGeometry(QtCore.QRect(104, 40, 51, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.del_s2lng_ipt = QtGui.QLineEdit(self.tab_5)
        self.del_s2lng_ipt.setGeometry(QtCore.QRect(470, 60, 71, 20))
        self.del_s2lng_ipt.setObjectName(_fromUtf8("del_s2lng_ipt"))
        self.label_23 = QtGui.QLabel(self.tab_5)
        self.label_23.setGeometry(QtCore.QRect(652, 140, 51, 16))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.del_a_ipt = QtGui.QLineEdit(self.tab_5)
        self.del_a_ipt.setGeometry(QtCore.QRect(12, 110, 71, 20))
        self.del_a_ipt.setObjectName(_fromUtf8("del_a_ipt"))
        self.del_perr0_ipt = QtGui.QLineEdit(self.tab_5)
        self.del_perr0_ipt.setGeometry(QtCore.QRect(470, 110, 71, 20))
        self.del_perr0_ipt.setObjectName(_fromUtf8("del_perr0_ipt"))
        self.label_9 = QtGui.QLabel(self.tab_5)
        self.label_9.setGeometry(QtCore.QRect(378, 90, 51, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.del_alb2_ipt = QtGui.QLineEdit(self.tab_5)
        self.del_alb2_ipt.setGeometry(QtCore.QRect(470, 160, 71, 20))
        self.del_alb2_ipt.setObjectName(_fromUtf8("del_alb2_ipt"))
        self.label_13 = QtGui.QLabel(self.tab_5)
        self.label_13.setGeometry(QtCore.QRect(652, 40, 51, 16))
        self.label_13.setStatusTip(_fromUtf8(""))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.del_q_ipt = QtGui.QLineEdit(self.tab_5)
        self.del_q_ipt.setGeometry(QtCore.QRect(650, 110, 71, 20))
        self.del_q_ipt.setObjectName(_fromUtf8("del_q_ipt"))
        self.label_12 = QtGui.QLabel(self.tab_5)
        self.label_12.setGeometry(QtCore.QRect(286, 40, 51, 16))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_14 = QtGui.QLabel(self.tab_5)
        self.label_14.setGeometry(QtCore.QRect(470, 40, 51, 16))
        self.label_14.setStatusTip(_fromUtf8(""))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.del_s1lat_ipt = QtGui.QLineEdit(self.tab_5)
        self.del_s1lat_ipt.setGeometry(QtCore.QRect(12, 60, 71, 20))
        self.del_s1lat_ipt.setToolTip(_fromUtf8(""))
        self.del_s1lat_ipt.setObjectName(_fromUtf8("del_s1lat_ipt"))
        self.del_pot2_ipt = QtGui.QLineEdit(self.tab_5)
        self.del_pot2_ipt.setGeometry(QtCore.QRect(652, 160, 71, 20))
        self.del_pot2_ipt.setObjectName(_fromUtf8("del_pot2_ipt"))
        self.label_17 = QtGui.QLabel(self.tab_5)
        self.label_17.setGeometry(QtCore.QRect(12, 90, 51, 16))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.del_t2_ipt = QtGui.QLineEdit(self.tab_5)
        self.del_t2_ipt.setGeometry(QtCore.QRect(286, 160, 71, 20))
        self.del_t2_ipt.setObjectName(_fromUtf8("del_t2_ipt"))
        self.del_alb1_ipt = QtGui.QLineEdit(self.tab_5)
        self.del_alb1_ipt.setGeometry(QtCore.QRect(378, 160, 71, 20))
        self.del_alb1_ipt.setObjectName(_fromUtf8("del_alb1_ipt"))
        self.label_24 = QtGui.QLabel(self.tab_5)
        self.label_24.setGeometry(QtCore.QRect(11, -5, 571, 41))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.del_s1tmpf_ipt = QtGui.QLineEdit(self.tab_5)
        self.del_s1tmpf_ipt.setGeometry(QtCore.QRect(286, 60, 71, 20))
        self.del_s1tmpf_ipt.setObjectName(_fromUtf8("del_s1tmpf_ipt"))
        self.del_e_ipt = QtGui.QLineEdit(self.tab_5)
        self.del_e_ipt.setGeometry(QtCore.QRect(104, 110, 71, 20))
        self.del_e_ipt.setObjectName(_fromUtf8("del_e_ipt"))
        self.del_pot1_ipt = QtGui.QLineEdit(self.tab_5)
        self.del_pot1_ipt.setGeometry(QtCore.QRect(560, 160, 71, 20))
        self.del_pot1_ipt.setObjectName(_fromUtf8("del_pot1_ipt"))
        self.label_25 = QtGui.QLabel(self.tab_5)
        self.label_25.setGeometry(QtCore.QRect(470, 90, 51, 16))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.label_29 = QtGui.QLabel(self.tab_5)
        self.label_29.setGeometry(QtCore.QRect(190, 140, 51, 16))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.label_26 = QtGui.QLabel(self.tab_5)
        self.label_26.setGeometry(QtCore.QRect(560, 40, 51, 16))
        self.label_26.setStatusTip(_fromUtf8(""))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.del_g2_ipt = QtGui.QLineEdit(self.tab_5)
        self.del_g2_ipt.setGeometry(QtCore.QRect(100, 160, 71, 20))
        self.del_g2_ipt.setObjectName(_fromUtf8("del_g2_ipt"))
        self.del_l2_ipt = QtGui.QLineEdit(self.tab_5)
        self.del_l2_ipt.setGeometry(QtCore.QRect(100, 210, 71, 20))
        self.del_l2_ipt.setObjectName(_fromUtf8("del_l2_ipt"))
        self.del_l1_ipt = QtGui.QLineEdit(self.tab_5)
        self.del_l1_ipt.setGeometry(QtCore.QRect(10, 210, 71, 20))
        self.del_l1_ipt.setObjectName(_fromUtf8("del_l1_ipt"))
        self.label_30 = QtGui.QLabel(self.tab_5)
        self.label_30.setGeometry(QtCore.QRect(192, 190, 51, 16))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.del_x1_ipt = QtGui.QLineEdit(self.tab_5)
        self.del_x1_ipt.setGeometry(QtCore.QRect(192, 210, 71, 20))
        self.del_x1_ipt.setObjectName(_fromUtf8("del_x1_ipt"))
        self.label_31 = QtGui.QLabel(self.tab_5)
        self.label_31.setGeometry(QtCore.QRect(284, 190, 51, 16))
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.label_32 = QtGui.QLabel(self.tab_5)
        self.label_32.setGeometry(QtCore.QRect(100, 190, 51, 16))
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.label_33 = QtGui.QLabel(self.tab_5)
        self.label_33.setGeometry(QtCore.QRect(10, 190, 51, 16))
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.del_x2_ipt = QtGui.QLineEdit(self.tab_5)
        self.del_x2_ipt.setGeometry(QtCore.QRect(286, 210, 71, 20))
        self.del_x2_ipt.setObjectName(_fromUtf8("del_x2_ipt"))
        self.line_7 = QtGui.QFrame(self.tab_5)
        self.line_7.setGeometry(QtCore.QRect(10, 20, 711, 21))
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.setdeldefaults_btn = QtGui.QPushButton(self.tab_5)
        self.setdeldefaults_btn.setGeometry(QtCore.QRect(593, 200, 131, 31))
        self.setdeldefaults_btn.setObjectName(_fromUtf8("setdeldefaults_btn"))
        self.tabWidget.addTab(self.tab_5, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.label_37 = QtGui.QLabel(self.tab_6)
        self.label_37.setGeometry(QtCore.QRect(10, 0, 721, 31))
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.line_6 = QtGui.QFrame(self.tab_6)
        self.line_6.setGeometry(QtCore.QRect(10, 20, 711, 20))
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.pshift_chk = QtGui.QCheckBox(self.tab_6)
        self.pshift_chk.setGeometry(QtCore.QRect(380, 80, 70, 17))
        self.pshift_chk.setObjectName(_fromUtf8("pshift_chk"))
        self.f2_chk = QtGui.QCheckBox(self.tab_6)
        self.f2_chk.setGeometry(QtCore.QRect(310, 80, 70, 17))
        self.f2_chk.setObjectName(_fromUtf8("f2_chk"))
        self.e_chk = QtGui.QCheckBox(self.tab_6)
        self.e_chk.setGeometry(QtCore.QRect(80, 80, 70, 17))
        self.e_chk.setObjectName(_fromUtf8("e_chk"))
        self.a_chk = QtGui.QCheckBox(self.tab_6)
        self.a_chk.setGeometry(QtCore.QRect(10, 80, 70, 17))
        self.a_chk.setObjectName(_fromUtf8("a_chk"))
        self.s1rad_chk = QtGui.QCheckBox(self.tab_6)
        self.s1rad_chk.setGeometry(QtCore.QRect(160, 140, 70, 17))
        self.s1rad_chk.setObjectName(_fromUtf8("s1rad_chk"))
        self.perr0_chk = QtGui.QCheckBox(self.tab_6)
        self.perr0_chk.setGeometry(QtCore.QRect(160, 80, 70, 17))
        self.perr0_chk.setObjectName(_fromUtf8("perr0_chk"))
        self.alb2_chk = QtGui.QCheckBox(self.tab_6)
        self.alb2_chk.setGeometry(QtCore.QRect(380, 110, 70, 17))
        self.alb2_chk.setObjectName(_fromUtf8("alb2_chk"))
        self.s1long_chk = QtGui.QCheckBox(self.tab_6)
        self.s1long_chk.setGeometry(QtCore.QRect(80, 140, 81, 17))
        self.s1long_chk.setObjectName(_fromUtf8("s1long_chk"))
        self.g1_chk = QtGui.QCheckBox(self.tab_6)
        self.g1_chk.setGeometry(QtCore.QRect(160, 110, 70, 17))
        self.g1_chk.setObjectName(_fromUtf8("g1_chk"))
        self.a3b_chk = QtGui.QCheckBox(self.tab_6)
        self.a3b_chk.setGeometry(QtCore.QRect(10, 170, 70, 17))
        self.a3b_chk.setObjectName(_fromUtf8("a3b_chk"))
        self.g2_chk = QtGui.QCheckBox(self.tab_6)
        self.g2_chk.setGeometry(QtCore.QRect(230, 110, 70, 17))
        self.g2_chk.setObjectName(_fromUtf8("g2_chk"))
        self.q_chk = QtGui.QCheckBox(self.tab_6)
        self.q_chk.setGeometry(QtCore.QRect(590, 110, 70, 17))
        self.q_chk.setObjectName(_fromUtf8("q_chk"))
        self.s1temp_chk = QtGui.QCheckBox(self.tab_6)
        self.s1temp_chk.setGeometry(QtCore.QRect(230, 140, 81, 17))
        self.s1temp_chk.setObjectName(_fromUtf8("s1temp_chk"))
        self.s2long_chk = QtGui.QCheckBox(self.tab_6)
        self.s2long_chk.setGeometry(QtCore.QRect(380, 140, 81, 17))
        self.s2long_chk.setObjectName(_fromUtf8("s2long_chk"))
        self.dpdt_chk = QtGui.QCheckBox(self.tab_6)
        self.dpdt_chk.setGeometry(QtCore.QRect(160, 50, 70, 17))
        self.dpdt_chk.setObjectName(_fromUtf8("dpdt_chk"))
        self.tc3b_chk = QtGui.QCheckBox(self.tab_6)
        self.tc3b_chk.setGeometry(QtCore.QRect(310, 170, 70, 17))
        self.tc3b_chk.setObjectName(_fromUtf8("tc3b_chk"))
        self.pot1_chk = QtGui.QCheckBox(self.tab_6)
        self.pot1_chk.setGeometry(QtCore.QRect(460, 110, 70, 17))
        self.pot1_chk.setObjectName(_fromUtf8("pot1_chk"))
        self.l2_chk = QtGui.QCheckBox(self.tab_6)
        self.l2_chk.setGeometry(QtCore.QRect(230, 200, 70, 17))
        self.l2_chk.setObjectName(_fromUtf8("l2_chk"))
        self.l1_chk = QtGui.QCheckBox(self.tab_6)
        self.l1_chk.setGeometry(QtCore.QRect(160, 200, 70, 17))
        self.l1_chk.setObjectName(_fromUtf8("l1_chk"))
        self.el3_chk = QtGui.QCheckBox(self.tab_6)
        self.el3_chk.setGeometry(QtCore.QRect(450, 200, 70, 17))
        self.el3_chk.setToolTip(_fromUtf8(""))
        self.el3_chk.setObjectName(_fromUtf8("el3_chk"))
        self.pot2_chk = QtGui.QCheckBox(self.tab_6)
        self.pot2_chk.setGeometry(QtCore.QRect(530, 110, 70, 17))
        self.pot2_chk.setObjectName(_fromUtf8("pot2_chk"))
        self.vgam_chk = QtGui.QCheckBox(self.tab_6)
        self.vgam_chk.setGeometry(QtCore.QRect(460, 80, 70, 17))
        self.vgam_chk.setObjectName(_fromUtf8("vgam_chk"))
        self.p0_chk = QtGui.QCheckBox(self.tab_6)
        self.p0_chk.setGeometry(QtCore.QRect(80, 50, 70, 17))
        self.p0_chk.setObjectName(_fromUtf8("p0_chk"))
        self.s2lat_chk = QtGui.QCheckBox(self.tab_6)
        self.s2lat_chk.setGeometry(QtCore.QRect(310, 140, 70, 17))
        self.s2lat_chk.setObjectName(_fromUtf8("s2lat_chk"))
        self.alb1_chk = QtGui.QCheckBox(self.tab_6)
        self.alb1_chk.setGeometry(QtCore.QRect(310, 110, 70, 17))
        self.alb1_chk.setObjectName(_fromUtf8("alb1_chk"))
        self.x1_chk = QtGui.QCheckBox(self.tab_6)
        self.x1_chk.setGeometry(QtCore.QRect(310, 200, 70, 17))
        self.x1_chk.setObjectName(_fromUtf8("x1_chk"))
        self.s1lat_chk = QtGui.QCheckBox(self.tab_6)
        self.s1lat_chk.setGeometry(QtCore.QRect(10, 140, 70, 17))
        self.s1lat_chk.setObjectName(_fromUtf8("s1lat_chk"))
        self.t2_chk = QtGui.QCheckBox(self.tab_6)
        self.t2_chk.setGeometry(QtCore.QRect(80, 110, 70, 17))
        self.t2_chk.setObjectName(_fromUtf8("t2_chk"))
        self.s2temp_chk = QtGui.QCheckBox(self.tab_6)
        self.s2temp_chk.setGeometry(QtCore.QRect(530, 140, 81, 17))
        self.s2temp_chk.setObjectName(_fromUtf8("s2temp_chk"))
        self.logd_chk = QtGui.QCheckBox(self.tab_6)
        self.logd_chk.setGeometry(QtCore.QRect(10, 200, 70, 17))
        self.logd_chk.setObjectName(_fromUtf8("logd_chk"))
        self.incl_chk = QtGui.QCheckBox(self.tab_6)
        self.incl_chk.setGeometry(QtCore.QRect(530, 80, 70, 17))
        self.incl_chk.setObjectName(_fromUtf8("incl_chk"))
        self.f1_chk = QtGui.QCheckBox(self.tab_6)
        self.f1_chk.setGeometry(QtCore.QRect(230, 80, 70, 17))
        self.f1_chk.setObjectName(_fromUtf8("f1_chk"))
        self.perr3b_chk = QtGui.QCheckBox(self.tab_6)
        self.perr3b_chk.setGeometry(QtCore.QRect(380, 170, 70, 17))
        self.perr3b_chk.setObjectName(_fromUtf8("perr3b_chk"))
        self.p3b_chk = QtGui.QCheckBox(self.tab_6)
        self.p3b_chk.setGeometry(QtCore.QRect(80, 170, 70, 17))
        self.p3b_chk.setObjectName(_fromUtf8("p3b_chk"))
        self.x2_chk = QtGui.QCheckBox(self.tab_6)
        self.x2_chk.setGeometry(QtCore.QRect(380, 200, 70, 17))
        self.x2_chk.setObjectName(_fromUtf8("x2_chk"))
        self.t1_chk = QtGui.QCheckBox(self.tab_6)
        self.t1_chk.setGeometry(QtCore.QRect(10, 110, 70, 17))
        self.t1_chk.setObjectName(_fromUtf8("t1_chk"))
        self.e3b_chk = QtGui.QCheckBox(self.tab_6)
        self.e3b_chk.setGeometry(QtCore.QRect(230, 170, 70, 17))
        self.e3b_chk.setObjectName(_fromUtf8("e3b_chk"))
        self.jd0_chk = QtGui.QCheckBox(self.tab_6)
        self.jd0_chk.setGeometry(QtCore.QRect(10, 50, 70, 17))
        self.jd0_chk.setObjectName(_fromUtf8("jd0_chk"))
        self.s2rad_chk = QtGui.QCheckBox(self.tab_6)
        self.s2rad_chk.setGeometry(QtCore.QRect(460, 140, 70, 17))
        self.s2rad_chk.setObjectName(_fromUtf8("s2rad_chk"))
        self.xinc3b_chk = QtGui.QCheckBox(self.tab_6)
        self.xinc3b_chk.setGeometry(QtCore.QRect(160, 170, 70, 17))
        self.xinc3b_chk.setObjectName(_fromUtf8("xinc3b_chk"))
        self.dperdt_chk = QtGui.QCheckBox(self.tab_6)
        self.dperdt_chk.setGeometry(QtCore.QRect(230, 50, 70, 17))
        self.dperdt_chk.setObjectName(_fromUtf8("dperdt_chk"))
        self.desextinc_chk = QtGui.QCheckBox(self.tab_6)
        self.desextinc_chk.setGeometry(QtCore.QRect(80, 200, 70, 17))
        self.desextinc_chk.setObjectName(_fromUtf8("desextinc_chk"))
        self.setkeepdefaults_btn = QtGui.QPushButton(self.tab_6)
        self.setkeepdefaults_btn.setGeometry(QtCore.QRect(593, 200, 131, 31))
        self.setkeepdefaults_btn.setObjectName(_fromUtf8("setkeepdefaults_btn"))
        self.clearkeeps_btn = QtGui.QPushButton(self.tab_6)
        self.clearkeeps_btn.setGeometry(QtCore.QRect(593, 160, 131, 31))
        self.clearkeeps_btn.setObjectName(_fromUtf8("clearkeeps_btn"))
        self.tabWidget.addTab(self.tab_6, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.linkext_spinbox = QtGui.QSpinBox(self.tab_2)
        self.linkext_spinbox.setGeometry(QtCore.QRect(90, 20, 42, 20))
        self.linkext_spinbox.setMaximum(9)
        self.linkext_spinbox.setObjectName(_fromUtf8("linkext_spinbox"))
        self.icor1_chk = QtGui.QCheckBox(self.tab_2)
        self.icor1_chk.setGeometry(QtCore.QRect(20, 20, 70, 21))
        self.icor1_chk.setObjectName(_fromUtf8("icor1_chk"))
        self.label_40 = QtGui.QLabel(self.tab_2)
        self.label_40.setGeometry(QtCore.QRect(140, 50, 71, 21))
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.label_39 = QtGui.QLabel(self.tab_2)
        self.label_39.setGeometry(QtCore.QRect(140, 20, 51, 20))
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.icor2_chk = QtGui.QCheckBox(self.tab_2)
        self.icor2_chk.setGeometry(QtCore.QRect(20, 50, 70, 21))
        self.icor2_chk.setObjectName(_fromUtf8("icor2_chk"))
        self.desextinc_ipt = QtGui.QLineEdit(self.tab_2)
        self.desextinc_ipt.setGeometry(QtCore.QRect(90, 50, 41, 20))
        self.desextinc_ipt.setObjectName(_fromUtf8("desextinc_ipt"))
        self.theme_combobox = QtGui.QComboBox(self.tab_2)
        self.theme_combobox.setGeometry(QtCore.QRect(120, 170, 131, 22))
        self.theme_combobox.setObjectName(_fromUtf8("theme_combobox"))
        self.label_4 = QtGui.QLabel(self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(20, 170, 101, 21))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.line_8 = QtGui.QFrame(self.tab_2)
        self.line_8.setGeometry(QtCore.QRect(410, 10, 20, 231))
        self.line_8.setFrameShape(QtGui.QFrame.VLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.pywd_about_title = QtGui.QLabel(self.tab_2)
        self.pywd_about_title.setGeometry(QtCore.QRect(430, 13, 291, 21))
        self.pywd_about_title.setObjectName(_fromUtf8("pywd_about_title"))
        self.line_9 = QtGui.QFrame(self.tab_2)
        self.line_9.setGeometry(QtCore.QRect(430, 30, 321, 21))
        self.line_9.setFrameShape(QtGui.QFrame.HLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName(_fromUtf8("line_9"))
        self.pywd_about = QtGui.QLabel(self.tab_2)
        self.pywd_about.setGeometry(QtCore.QRect(430, 50, 321, 61))
        self.pywd_about.setTextFormat(QtCore.Qt.RichText)
        self.pywd_about.setScaledContents(False)
        self.pywd_about.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignTop)
        self.pywd_about.setWordWrap(True)
        self.pywd_about.setObjectName(_fromUtf8("pywd_about"))
        self.lineEdit = QtGui.QLineEdit(self.tab_2)
        self.lineEdit.setGeometry(QtCore.QRect(540, 120, 211, 20))
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.lineEdit_2 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_2.setGeometry(QtCore.QRect(540, 150, 211, 20))
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.label_49 = QtGui.QLabel(self.tab_2)
        self.label_49.setGeometry(QtCore.QRect(430, 120, 91, 20))
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.label_52 = QtGui.QLabel(self.tab_2)
        self.label_52.setGeometry(QtCore.QRect(430, 150, 101, 21))
        self.label_52.setObjectName(_fromUtf8("label_52"))
        self.ifoc_chk = QtGui.QCheckBox(self.tab_2)
        self.ifoc_chk.setGeometry(QtCore.QRect(20, 80, 70, 21))
        self.ifoc_chk.setObjectName(_fromUtf8("ifoc_chk"))
        self.ifder_chk = QtGui.QCheckBox(self.tab_2)
        self.ifder_chk.setGeometry(QtCore.QRect(20, 110, 70, 21))
        self.ifder_chk.setObjectName(_fromUtf8("ifder_chk"))
        self.iflcin_chk = QtGui.QCheckBox(self.tab_2)
        self.iflcin_chk.setGeometry(QtCore.QRect(20, 140, 70, 21))
        self.iflcin_chk.setObjectName(_fromUtf8("iflcin_chk"))
        self.ifcgs_chk = QtGui.QCheckBox(self.tab_2)
        self.ifcgs_chk.setGeometry(QtCore.QRect(90, 80, 79, 18))
        self.ifcgs_chk.setObjectName(_fromUtf8("ifcgs_chk"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.label_48 = QtGui.QLabel(self.centralwidget)
        self.label_48.setGeometry(QtCore.QRect(10, 10, 151, 21))
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.mode_combobox = QtGui.QComboBox(self.centralwidget)
        self.mode_combobox.setGeometry(QtCore.QRect(160, 10, 91, 22))
        self.mode_combobox.setObjectName(_fromUtf8("mode_combobox"))
        self.mode_combobox.addItem(_fromUtf8(""))
        self.mode_combobox.addItem(_fromUtf8(""))
        self.mode_combobox.addItem(_fromUtf8(""))
        self.mode_combobox.addItem(_fromUtf8(""))
        self.mode_combobox.addItem(_fromUtf8(""))
        self.mode_combobox.addItem(_fromUtf8(""))
        self.mode_combobox.addItem(_fromUtf8(""))
        self.mode_combobox.addItem(_fromUtf8(""))
        self.whatsthis_btn = QtGui.QPushButton(self.centralwidget)
        self.whatsthis_btn.setGeometry(QtCore.QRect(740, 10, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.whatsthis_btn.setFont(font)
        self.whatsthis_btn.setObjectName(_fromUtf8("whatsthis_btn"))
        self.export_btn = QtGui.QPushButton(self.centralwidget)
        self.export_btn.setGeometry(QtCore.QRect(590, 10, 141, 31))
        self.export_btn.setObjectName(_fromUtf8("export_btn"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.mode_combobox.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "PyWD2015", None))
        self.jdphs_combobox.setItemText(0, _translate("MainWindow", "Phase", None))
        self.jdphs_combobox.setItemText(1, _translate("MainWindow", "Time", None))
        self.label_41.setToolTip(_translate("MainWindow", "Set whether time or phase is the independent variable", None))
        self.label_41.setText(_translate("MainWindow", "JDPHS", None))
        self.pshift_ipt.setText(_translate("MainWindow", "0", None))
        self.rm_ipt.setToolTip(_translate("MainWindow", "Binary system inclination", None))
        self.rm_ipt.setText(_translate("MainWindow", "0", None))
        self.dpdt_ipt.setText(_translate("MainWindow", "0", None))
        self.label_42.setToolTip(_translate("MainWindow", "Number of Gaussian abscissas in the Gaussian quadrature of time/phase smearing, set 1 for no smearing", None))
        self.label_42.setText(_translate("MainWindow", "NGA", None))
        self.label_67.setToolTip(_translate("MainWindow", " System metallicity as usually defined logarithmically, relative to the Sun", None))
        self.label_67.setText(_translate("MainWindow", "ABUNIN", None))
        self.label_75.setToolTip(_translate("MainWindow", "The potential for star 2, as defined by Kopal (1954) for synchronous, circular orbit case", None))
        self.label_75.setText(_translate("MainWindow", "PCSV", None))
        self.dpclog_ipt.setToolTip(_translate("MainWindow", "Binary system inclination", None))
        self.dpclog_ipt.setText(_translate("MainWindow", "1.83714", None))
        self.abunin_ipt.setToolTip(_translate("MainWindow", "Binary system inclination", None))
        self.abunin_ipt.setText(_translate("MainWindow", "0", None))
        self.perr0_ipt.setText(_translate("MainWindow", "0", None))
        self.label_74.setToolTip(_translate("MainWindow", "The potential for star 1, as defined by Kopal (1954) for synchronous, circular orbit case", None))
        self.label_74.setText(_translate("MainWindow", "PHSV", None))
        self.label_62.setToolTip(_translate("MainWindow", "First time derivative of omega", None))
        self.label_62.setText(_translate("MainWindow", "e", None))
        self.label_47.setToolTip(_translate("MainWindow", "Duration of light curve observation for phase smearing computation", None))
        self.label_47.setText(_translate("MainWindow", "DELPH", None))
        self.phsv_ipt.setToolTip(_translate("MainWindow", "Binary system inclination", None))
        self.phsv_ipt.setText(_translate("MainWindow", "0", None))
        self.label_45.setText(_translate("MainWindow", "dPdt", None))
        self.label_64.setToolTip(_translate("MainWindow", "Binary system orbital inclination, XINCL", None))
        self.label_64.setText(_translate("MainWindow", "INCL", None))
        self.jd0_ipt.setText(_translate("MainWindow", "0", None))
        self.label_55.setToolTip(_translate("MainWindow", "Initial argument of periastron for star 1 in radians, the argument of periastron for star 2 differs by π radians", None))
        self.label_55.setText(_translate("MainWindow", "PERR0", None))
        self.label_83.setToolTip(_translate("MainWindow", "Base 10 logarithm of distance in parsecs", None))
        self.label_83.setText(_translate("MainWindow", "DPCLOG", None))
        self.tavc_ipt.setToolTip(_translate("MainWindow", "Binary system inclination", None))
        self.tavc_ipt.setText(_translate("MainWindow", "0", None))
        self.vgam_ipt.setText(_translate("MainWindow", "0", None))
        self.label_46.setToolTip(_translate("MainWindow", "Constant shift to be applied to computed phases; Phase Shift", None))
        self.label_46.setText(_translate("MainWindow", "PSHIFT", None))
        self.label_80.setToolTip(_translate("MainWindow", "Mass ratio of binary components, M2/M1", None))
        self.label_80.setText(_translate("MainWindow", "RM", None))
        self.label_57.setToolTip(_translate("MainWindow", "Semi-duration of primary eclipses in phase units, applied only in Mode -1", None))
        self.label_57.setText(_translate("MainWindow", "TH E", None))
        self.label_60.setToolTip(_translate("MainWindow", "Ratio of axial rotation rate vs. mean orbital rate", None))
        self.label_60.setText(_translate("MainWindow", "F1", None))
        self.label_44.setText(_translate("MainWindow", "P0", None))
        self.label_63.setToolTip(_translate("MainWindow", "V Gamma", None))
        self.label_63.setText(_translate("MainWindow", "VGAM", None))
        self.p0_ipt.setText(_translate("MainWindow", "0", None))
        self.the_ipt.setText(_translate("MainWindow", "0", None))
        self.pcsv_ipt.setToolTip(_translate("MainWindow", "Binary system inclination", None))
        self.pcsv_ipt.setText(_translate("MainWindow", "0", None))
        self.delph_ipt.setText(_translate("MainWindow", "0", None))
        self.tavh_ipt.setToolTip(_translate("MainWindow", "Binary system inclination", None))
        self.tavh_ipt.setText(_translate("MainWindow", "0", None))
        self.xincl_ipt.setToolTip(_translate("MainWindow", "Binary system inclination", None))
        self.xincl_ipt.setText(_translate("MainWindow", "0", None))
        self.e_ipt.setText(_translate("MainWindow", "0", None))
        self.vunit_ipt.setText(_translate("MainWindow", "100", None))
        self.label_43.setText(_translate("MainWindow", "JD0", None))
        self.label_70.setToolTip(_translate("MainWindow", "Mean effective temperature for star 1, re-radiation or spots not included", None))
        self.label_70.setText(_translate("MainWindow", "TAVC", None))
        self.f2_ipt.setText(_translate("MainWindow", "1", None))
        self.label_71.setToolTip(_translate("MainWindow", "Mean effective temperature for star 1, re-radiation or spots not included", None))
        self.label_71.setText(_translate("MainWindow", "TAVH", None))
        self.dperdt_ipt.setText(_translate("MainWindow", "0", None))
        self.a_ipt.setText(_translate("MainWindow", "0", None))
        self.label_61.setToolTip(_translate("MainWindow", "Ratio of axial rotation rate vs. mean orbital rate", None))
        self.label_61.setText(_translate("MainWindow", "F2", None))
        self.label_59.setToolTip(_translate("MainWindow", "Semi-major axis", None))
        self.label_59.setText(_translate("MainWindow", "a", None))
        self.label_56.setToolTip(_translate("MainWindow", "First time derivative of omega", None))
        self.label_56.setText(_translate("MainWindow", "dPERdt", None))
        self.label_58.setToolTip(_translate("MainWindow", "Radial velocity input in km/s", None))
        self.label_58.setText(_translate("MainWindow", "VUNIT", None))
        self.f1_ipt.setText(_translate("MainWindow", "1", None))
        self.loadwidget_btn.setText(_translate("MainWindow", "Load Observations", None))
        self.spotconfigure_btn.setText(_translate("MainWindow", "Configure Spots", None))
        self.maglite_combobox.setItemText(0, _translate("MainWindow", "Flux", None))
        self.maglite_combobox.setItemText(1, _translate("MainWindow", "Magnitude", None))
        self.label_38.setToolTip(_translate("MainWindow", "Input unit", None))
        self.label_38.setText(_translate("MainWindow", "MAGLITE", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Initial Values", None))
        self.label_90.setToolTip(_translate("MainWindow", "The bolometric albedo for reflection heating and re-radiation on star 2", None))
        self.label_90.setText(_translate("MainWindow", "ALB2", None))
        self.label_91.setToolTip(_translate("MainWindow", "Coarse grid size integers of star 2, used in certain derivatives to save computation time", None))
        self.label_91.setText(_translate("MainWindow", "N2L", None))
        self.ld2_combobox.setItemText(0, _translate("MainWindow", "Linear Cosine", None))
        self.ld2_combobox.setItemText(1, _translate("MainWindow", "Logarithmic", None))
        self.ld2_combobox.setItemText(2, _translate("MainWindow", "Square Root", None))
        self.label_92.setToolTip(_translate("MainWindow", "Grid size integers (number of latitude rows per hemisphere) of star 2", None))
        self.label_92.setText(_translate("MainWindow", "N2", None))
        self.label_93.setToolTip(_translate("MainWindow", "Exponent for the bolometric gravity brightening for star 1", None))
        self.label_93.setText(_translate("MainWindow", "GR1", None))
        self.label_94.setToolTip(_translate("MainWindow", "Used if LD2 is set to Logarithmic, this is the coefficient of cos γ ln(cos γ) term in the bolometric logarithmic limb darkening law, for star 2", None))
        self.label_94.setText(_translate("MainWindow", "YBOL2", None))
        self.xbol1_ipt.setToolTip(_translate("MainWindow", "Binary system inclination", None))
        self.xbol1_ipt.setText(_translate("MainWindow", "0", None))
        self.label_95.setToolTip(_translate("MainWindow", "Grid size integers (number of latitude rows per hemisphere) of star 1", None))
        self.label_95.setText(_translate("MainWindow", "N1", None))
        self.ifat2_combobox.setItemText(0, _translate("MainWindow", "Stellar Atmosphere", None))
        self.ifat2_combobox.setItemText(1, _translate("MainWindow", "Blackbody", None))
        self.label_96.setToolTip(_translate("MainWindow", "Coarse grid size integers of star 1, used in certain derivatives to save computation time", None))
        self.label_96.setText(_translate("MainWindow", "N1L", None))
        self.label_97.setToolTip(_translate("MainWindow", "The coefficient of cos γ in the bolometric limb darkening law, for star 2", None))
        self.label_97.setText(_translate("MainWindow", "XBOL2", None))
        self.xbol2_ipt.setToolTip(_translate("MainWindow", "Binary system inclination", None))
        self.xbol2_ipt.setText(_translate("MainWindow", "0", None))
        self.label_36.setToolTip(_translate("MainWindow", "<html><head/><body><p>Set limb darkening law for star 2. <span style=\" font-weight:600;\">Uncheck</span> &quot;Set Fixed&quot; box to <span style=\" font-weight:600;\">ignore</span> input x, y coefficients in light curve and velocity curve input dialogs, and allow DC to calculate limb darkening coefficients internally (in terms of Teff, log g, and (M/H)).</p></body></html>", None))
        self.label_36.setText(_translate("MainWindow", "LD2", None))
        self.mref_chk.setToolTip(_translate("MainWindow", "Use detailed reflection computation", None))
        self.mref_chk.setText(_translate("MainWindow", "MREF", None))
        self.ybol1_ipt.setToolTip(_translate("MainWindow", "Binary system inclination", None))
        self.ybol1_ipt.setText(_translate("MainWindow", "0", None))
        self.label_98.setToolTip(_translate("MainWindow", "The coefficient of cos γ in the bolometric limb darkening law, for star 1", None))
        self.label_98.setText(_translate("MainWindow", "XBOL1", None))
        self.label_34.setToolTip(_translate("MainWindow", "Number of reflections in detailed reflection computation", None))
        self.label_34.setText(_translate("MainWindow", "NREF", None))
        self.label_99.setToolTip(_translate("MainWindow", "Exponent for the bolometric gravity brightening for star 2", None))
        self.label_99.setText(_translate("MainWindow", "GR2", None))
        self.label_100.setToolTip(_translate("MainWindow", "Set local emission formulation for star 1", None))
        self.label_100.setText(_translate("MainWindow", "IFAT1", None))
        self.ipb_chk.setToolTip(_translate("MainWindow", "Check the box to set L2 manually", None))
        self.ipb_chk.setText(_translate("MainWindow", "IPB", None))
        self.label_101.setToolTip(_translate("MainWindow", "Used if LD1 is set to Logarithmic, this is the coefficient of cos γ ln(cos γ) term in the bolometric logarithmic limb darkening law, for star 1", None))
        self.label_101.setText(_translate("MainWindow", "YBOL1", None))
        self.label_35.setToolTip(_translate("MainWindow", "<html><head/><body><p>Set limb darkening law for star 1. <span style=\" font-weight:600;\">Uncheck</span> &quot;Set Fixed&quot; box to <span style=\" font-weight:600;\">ignore</span> input x, y coefficients in light curve and velocity curve input dialogs, and allow DC to calculate limb darkening coefficients internally (in terms of Teff, log g, and (M/H)).</p></body></html>", None))
        self.label_35.setText(_translate("MainWindow", "LD1", None))
        self.label_102.setToolTip(_translate("MainWindow", "The bolometric albedo for reflection heating and re-radiation on star 1", None))
        self.label_102.setText(_translate("MainWindow", "ALB1", None))
        self.ld1_combobox.setItemText(0, _translate("MainWindow", "Linear Cosine", None))
        self.ld1_combobox.setItemText(1, _translate("MainWindow", "Logarithmic", None))
        self.ld1_combobox.setItemText(2, _translate("MainWindow", "Square Root", None))
        self.label_103.setToolTip(_translate("MainWindow", "Set local emission formulation for star 2", None))
        self.label_103.setText(_translate("MainWindow", "IFAT2", None))
        self.ifat1_combobox.setItemText(0, _translate("MainWindow", "Stellar Atmosphere", None))
        self.ifat1_combobox.setItemText(1, _translate("MainWindow", "Blackbody", None))
        self.ybol2_ipt.setToolTip(_translate("MainWindow", "Binary system inclination", None))
        self.ybol2_ipt.setText(_translate("MainWindow", "0", None))
        self.label.setText(_translate("MainWindow", "Limb Darkening", None))
        self.label_2.setText(_translate("MainWindow", "Grids", None))
        self.label_3.setText(_translate("MainWindow", "Reflection Computation", None))
        self.isym_combobox.setItemText(0, _translate("MainWindow", "Symmetrical", None))
        self.isym_combobox.setItemText(1, _translate("MainWindow", "Asymmetrical", None))
        self.label_50.setToolTip(_translate("MainWindow", "Carry out solution with asymmetrical or symmetrical derivatives. Symmetrical derivatives are more reliable but take twice as long to compute", None))
        self.label_50.setText(_translate("MainWindow", "ISYM", None))
        self.label_51.setText(_translate("MainWindow", "Set Fixed", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Atmosphere", None))
        self.label_104.setToolTip(_translate("MainWindow", "Period of the 3rd body orbit in mean solar days", None))
        self.label_104.setText(_translate("MainWindow", "P3B", None))
        self.a3b_ipt.setToolTip(_translate("MainWindow", "Binary system inclination", None))
        self.a3b_ipt.setText(_translate("MainWindow", "0", None))
        self.label_105.setToolTip(_translate("MainWindow", "Inclination of the 3rd body orbit to the plane of the sky, in degrees", None))
        self.label_105.setText(_translate("MainWindow", "XINC3B", None))
        self.perr3b_ipt.setToolTip(_translate("MainWindow", "Binary system inclination", None))
        self.perr3b_ipt.setText(_translate("MainWindow", "0", None))
        self.label_106.setToolTip(_translate("MainWindow", "Time of superior conjunction of the EB center of mass in its reflex motion about\n"
"the triple system barycenter, in the adopted time system", None))
        self.label_106.setText(_translate("MainWindow", "TC3B", None))
        self.e3b_ipt.setToolTip(_translate("MainWindow", "Binary system inclination", None))
        self.e3b_ipt.setText(_translate("MainWindow", "0", None))
        self.tc3b_ipt.setToolTip(_translate("MainWindow", "Binary system inclination", None))
        self.tc3b_ipt.setText(_translate("MainWindow", "0", None))
        self.label_107.setToolTip(_translate("MainWindow", "Semi-major axis of the relative 3rd body orbit in solar radii", None))
        self.label_107.setText(_translate("MainWindow", "A3B", None))
        self.p3b_ipt.setToolTip(_translate("MainWindow", "Binary system inclination", None))
        self.p3b_ipt.setText(_translate("MainWindow", "0", None))
        self.label_108.setToolTip(_translate("MainWindow", "Argument of periastron of the 3rd body orbit in radians", None))
        self.label_108.setText(_translate("MainWindow", "PERR3B", None))
        self.label_109.setToolTip(_translate("MainWindow", "Eccentricity of the 3rd body orbit", None))
        self.label_109.setText(_translate("MainWindow", "E3B", None))
        self.xinc3b_ipt.setToolTip(_translate("MainWindow", "Binary system inclination", None))
        self.xinc3b_ipt.setText(_translate("MainWindow", "0", None))
        self.if3b_chk.setToolTip(_translate("MainWindow", "Include light time effect from a 3rd body", None))
        self.if3b_chk.setText(_translate("MainWindow", "IF3B - Enable third body parameters", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "3rd Body", None))
        self.del_s2tmpf_ipt.setText(_translate("MainWindow", "0.02", None))
        self.del_pshift_ipt.setText(_translate("MainWindow", "0.002", None))
        self.del_t1_ipt.setText(_translate("MainWindow", "0.02", None))
        self.label_27.setToolTip(_translate("MainWindow", "Average surface temperature in 10000K", None))
        self.label_27.setText(_translate("MainWindow", "T2", None))
        self.label_5.setToolTip(_translate("MainWindow", "Spot 1 Latitude", None))
        self.label_5.setText(_translate("MainWindow", "S1 LAT", None))
        self.del_f1_ipt.setText(_translate("MainWindow", "0.01", None))
        self.del_s1lng_ipt.setText(_translate("MainWindow", "0.02", None))
        self.label_16.setToolTip(_translate("MainWindow", "Ratio of axial rotation rate vs. mean orbital rate", None))
        self.label_16.setText(_translate("MainWindow", "F2", None))
        self.del_s2lat_ipt.setText(_translate("MainWindow", "0.02", None))
        self.label_7.setToolTip(_translate("MainWindow", "Ratio of axial rotation rate vs. mean orbital rate", None))
        self.label_7.setText(_translate("MainWindow", "F1", None))
        self.label_6.setToolTip(_translate("MainWindow", "Spot 1 Angular Radius", None))
        self.label_6.setText(_translate("MainWindow", "S1 RAD", None))
        self.label_15.setToolTip(_translate("MainWindow", "Orbit eccentricity", None))
        self.label_15.setText(_translate("MainWindow", "e", None))
        self.del_f2_ipt.setText(_translate("MainWindow", "0.01", None))
        self.del_g1_ipt.setText(_translate("MainWindow", "0.01", None))
        self.del_i_ipt.setText(_translate("MainWindow", "0.2", None))
        self.label_8.setToolTip(_translate("MainWindow", "Spot 2 Latitude", None))
        self.label_8.setText(_translate("MainWindow", "S2 LAT", None))
        self.label_28.setToolTip(_translate("MainWindow", "Gravity darkening exponent", None))
        self.label_28.setText(_translate("MainWindow", "G2", None))
        self.label_19.setToolTip(_translate("MainWindow", "Surface potential", None))
        self.label_19.setText(_translate("MainWindow", "POT1", None))
        self.label_20.setToolTip(_translate("MainWindow", "Bolometric Albedo", None))
        self.label_20.setText(_translate("MainWindow", "ALB2", None))
        self.label_10.setToolTip(_translate("MainWindow", "Inclination", None))
        self.label_10.setText(_translate("MainWindow", "i", None))
        self.label_21.setToolTip(_translate("MainWindow", "Bolometric Albedo", None))
        self.label_21.setText(_translate("MainWindow", "ALB1", None))
        self.label_18.setToolTip(_translate("MainWindow", "Gravity darkening exponent", None))
        self.label_18.setText(_translate("MainWindow", "G1", None))
        self.del_s2agrad_ipt.setText(_translate("MainWindow", "0.0001", None))
        self.label_22.setToolTip(_translate("MainWindow", "Mass ratio, star 2/star 1", None))
        self.label_22.setText(_translate("MainWindow", "Q", None))
        self.del_s1agrad_ipt.setText(_translate("MainWindow", "0.001", None))
        self.label_11.setToolTip(_translate("MainWindow", "Spot 1 Longitude", None))
        self.label_11.setText(_translate("MainWindow", "S1 LON", None))
        self.del_s2lng_ipt.setText(_translate("MainWindow", "0.001", None))
        self.label_23.setToolTip(_translate("MainWindow", "Surface potential", None))
        self.label_23.setText(_translate("MainWindow", "POT2", None))
        self.del_a_ipt.setText(_translate("MainWindow", "0.05", None))
        self.del_perr0_ipt.setText(_translate("MainWindow", "0.01", None))
        self.label_9.setToolTip(_translate("MainWindow", "Phase Shift", None))
        self.label_9.setText(_translate("MainWindow", "PSHIFT", None))
        self.del_alb2_ipt.setText(_translate("MainWindow", "0.05", None))
        self.label_13.setToolTip(_translate("MainWindow", "Spot 2 Temperature Factor", None))
        self.label_13.setText(_translate("MainWindow", "S2 TF", None))
        self.del_q_ipt.setText(_translate("MainWindow", "0.003", None))
        self.label_12.setToolTip(_translate("MainWindow", "Spot 1 Temperature Factor", None))
        self.label_12.setText(_translate("MainWindow", "S1 TF", None))
        self.label_14.setToolTip(_translate("MainWindow", "Spot 2 Longitude", None))
        self.label_14.setText(_translate("MainWindow", "S2 LON", None))
        self.del_s1lat_ipt.setText(_translate("MainWindow", "0.02", None))
        self.del_pot2_ipt.setText(_translate("MainWindow", "0.02", None))
        self.label_17.setToolTip(_translate("MainWindow", "Semi-major axis", None))
        self.label_17.setText(_translate("MainWindow", "a", None))
        self.del_t2_ipt.setText(_translate("MainWindow", "0.02", None))
        self.del_alb1_ipt.setText(_translate("MainWindow", "0.05", None))
        self.label_24.setText(_translate("MainWindow", "DEL\'s - Parameter increments for approximating derivatives in finite differences. Hover on labels for more information.", None))
        self.del_s1tmpf_ipt.setText(_translate("MainWindow", "0.02", None))
        self.del_e_ipt.setText(_translate("MainWindow", "0.001", None))
        self.del_pot1_ipt.setText(_translate("MainWindow", "0.02", None))
        self.label_25.setToolTip(_translate("MainWindow", "V Gamma", None))
        self.label_25.setText(_translate("MainWindow", "PERR0", None))
        self.label_29.setToolTip(_translate("MainWindow", "Average surface temperature in 10000K", None))
        self.label_29.setText(_translate("MainWindow", "T1", None))
        self.label_26.setToolTip(_translate("MainWindow", "Spot 2 Angular Radius", None))
        self.label_26.setText(_translate("MainWindow", "S2 RAD", None))
        self.del_g2_ipt.setText(_translate("MainWindow", "0.01", None))
        self.del_l2_ipt.setText(_translate("MainWindow", "0.01", None))
        self.del_l1_ipt.setText(_translate("MainWindow", "0.01", None))
        self.label_30.setToolTip(_translate("MainWindow", "Limb darkening coefficient", None))
        self.label_30.setText(_translate("MainWindow", "X1", None))
        self.del_x1_ipt.setText(_translate("MainWindow", "0.01", None))
        self.label_31.setToolTip(_translate("MainWindow", "Limb darkening coefficient", None))
        self.label_31.setText(_translate("MainWindow", "X2", None))
        self.label_32.setToolTip(_translate("MainWindow", "Relative monochromatic luminosity", None))
        self.label_32.setText(_translate("MainWindow", "L2", None))
        self.label_33.setToolTip(_translate("MainWindow", "Relative monochromatic luminosity", None))
        self.label_33.setText(_translate("MainWindow", "L1", None))
        self.del_x2_ipt.setText(_translate("MainWindow", "0.01", None))
        self.setdeldefaults_btn.setText(_translate("MainWindow", "Set Defaults", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "DEL\'s", None))
        self.label_37.setText(_translate("MainWindow", "KEEP\'s - Select which parameters to be adjusted. Hover on labels for more information.", None))
        self.pshift_chk.setText(_translate("MainWindow", "PSHIFT", None))
        self.f2_chk.setText(_translate("MainWindow", "F2", None))
        self.e_chk.setText(_translate("MainWindow", "e", None))
        self.a_chk.setText(_translate("MainWindow", "a", None))
        self.s1rad_chk.setText(_translate("MainWindow", "S1 RAD", None))
        self.perr0_chk.setText(_translate("MainWindow", "PERR0", None))
        self.alb2_chk.setText(_translate("MainWindow", "ALB2", None))
        self.s1long_chk.setText(_translate("MainWindow", "S1 LONG", None))
        self.g1_chk.setText(_translate("MainWindow", "G1", None))
        self.a3b_chk.setText(_translate("MainWindow", "A3B", None))
        self.g2_chk.setText(_translate("MainWindow", "G2", None))
        self.q_chk.setText(_translate("MainWindow", "Q", None))
        self.s1temp_chk.setText(_translate("MainWindow", "S1 TEMP", None))
        self.s2long_chk.setText(_translate("MainWindow", "S2 LONG", None))
        self.dpdt_chk.setText(_translate("MainWindow", "dPdt", None))
        self.tc3b_chk.setText(_translate("MainWindow", "TC3B", None))
        self.pot1_chk.setText(_translate("MainWindow", "POT1", None))
        self.l2_chk.setText(_translate("MainWindow", "L2", None))
        self.l1_chk.setText(_translate("MainWindow", "L1", None))
        self.el3_chk.setText(_translate("MainWindow", "EL3", None))
        self.pot2_chk.setText(_translate("MainWindow", "POT2", None))
        self.vgam_chk.setText(_translate("MainWindow", "VGAM", None))
        self.p0_chk.setText(_translate("MainWindow", "P0", None))
        self.s2lat_chk.setText(_translate("MainWindow", "S2 LAT", None))
        self.alb1_chk.setText(_translate("MainWindow", "ALB1", None))
        self.x1_chk.setText(_translate("MainWindow", "X1", None))
        self.s1lat_chk.setText(_translate("MainWindow", "S1 LAT", None))
        self.t2_chk.setText(_translate("MainWindow", "T2", None))
        self.s2temp_chk.setText(_translate("MainWindow", "S2 TEMP", None))
        self.logd_chk.setText(_translate("MainWindow", "logD", None))
        self.incl_chk.setText(_translate("MainWindow", "INCL", None))
        self.f1_chk.setText(_translate("MainWindow", "F1", None))
        self.perr3b_chk.setText(_translate("MainWindow", "PERR3B", None))
        self.p3b_chk.setText(_translate("MainWindow", "P3B", None))
        self.x2_chk.setText(_translate("MainWindow", "X2", None))
        self.t1_chk.setText(_translate("MainWindow", "T1", None))
        self.e3b_chk.setText(_translate("MainWindow", "E3B", None))
        self.jd0_chk.setText(_translate("MainWindow", "JD0", None))
        self.s2rad_chk.setText(_translate("MainWindow", "S2 RAD", None))
        self.xinc3b_chk.setText(_translate("MainWindow", "XINC3B", None))
        self.dperdt_chk.setText(_translate("MainWindow", "dPERdt", None))
        self.desextinc_chk.setToolTip(_translate("MainWindow", "DESEXTINC", None))
        self.desextinc_chk.setText(_translate("MainWindow", "DEXT", None))
        self.setkeepdefaults_btn.setText(_translate("MainWindow", "Set Defaults", None))
        self.clearkeeps_btn.setText(_translate("MainWindow", "Clear", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "KEEP\'s", None))
        self.icor1_chk.setToolTip(_translate("MainWindow", "Should computed RV\'s include proximity and eclipse corrections for star 1?", None))
        self.icor1_chk.setText(_translate("MainWindow", "ICOR1", None))
        self.label_40.setToolTip(_translate("MainWindow", "Interstellar extinction in the designated band, in magnitude", None))
        self.label_40.setText(_translate("MainWindow", "DESEXTINC", None))
        self.label_39.setToolTip(_translate("MainWindow", "Designated band for interstellar extinction. Set 0 if there isn\'t one.", None))
        self.label_39.setText(_translate("MainWindow", "LINKEXT", None))
        self.icor2_chk.setToolTip(_translate("MainWindow", "Should computed RV\'s include proximity and eclipse corrections for star 2?", None))
        self.icor2_chk.setText(_translate("MainWindow", "ICOR2", None))
        self.desextinc_ipt.setText(_translate("MainWindow", "0", None))
        self.label_4.setText(_translate("MainWindow", "Change Theme", None))
        self.pywd_about_title.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">About the PyWD2015</span></p></body></html>", None))
        self.pywd_about.setText(_translate("MainWindow", "<html><head/><body><p>PyWD2015 (or pywd for short) is a graphical user interface for generating dcin.active files for Wilson - Devinney\'s DC program for eclipsing binary modeling, targeting specifically the 2015 version.</p></body></html>", None))
        self.lineEdit.setText(_translate("MainWindow", "github.com/Varnani/PyWD2015", None))
        self.lineEdit_2.setText(_translate("MainWindow", "ftp://ftp.astro.ufl.edu/pub/wilson/", None))
        self.label_49.setText(_translate("MainWindow", "GitHub:", None))
        self.label_52.setText(_translate("MainWindow", "WD Homepage:", None))
        self.ifoc_chk.setToolTip(_translate("MainWindow", "Write extra two columns of \"observed\" and \"computed\" data in dcout file.", None))
        self.ifoc_chk.setText(_translate("MainWindow", "IFOC", None))
        self.ifder_chk.setToolTip(_translate("MainWindow", "Write matrix of parameter derivatives and residuals, or observational equations", None))
        self.ifder_chk.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Write control integer IFDER is set to 1 for “yes, write” or to 0 for “do not write.” It decides whether the matrix of parameter derivatives and residuals, or observational equations (both the unweighted and the weighted versions), are written. Since the observational equations for the first iteration pertain to the input parameters (and they change only a little for subsequent iterations), they are written only for the base set.</p></body></html>", None))
        self.ifder_chk.setText(_translate("MainWindow", "IFDER", None))
        self.iflcin_chk.setToolTip(_translate("MainWindow", "Write an input file for the LC program, from DC INPUT parameters", None))
        self.iflcin_chk.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>", None))
        self.iflcin_chk.setText(_translate("MainWindow", "IFLCIN", None))
        self.ifcgs_chk.setToolTip(_translate("MainWindow", "<html><head/><body><p>If absolute solution with flux unit erg s<span style=\" vertical-align:super;\">−1</span> cm<span style=\" vertical-align:super;\">−3</span> is desired, check this box. Uncheck this box for a conventional solution in arbitrarily scaled flux.</p></body></html>", None))
        self.ifcgs_chk.setText(_translate("MainWindow", "IFCGS", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Miscellaneous", None))
        self.label_48.setToolTip(_translate("MainWindow", "Sets predefined constraints for different conditions", None))
        self.label_48.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Mode -1:</span> This mode is for X-ray binaries for which the eclipse duration of a compact object is known from X-ray observations. The compact star must be star 1. The applied constraint is that the surface potential of the ordinary star (star 2) must be such as to produce the observed X-ray eclipse duration.</p><p><span style=\" font-weight:600;\">Mode 0:</span> No constraints are applied in mode 0, and the component luminosity ratio is not even required to be consistent with the surface temperatures.</p><p><span style=\" font-weight:600;\">Mode 1:</span> This is a mode for overcontact binaries, such as W UMa stars. Six or seven constraints are applied, depending on whether fixed or computed limb darkening is specified.</p><p><span style=\" font-weight:600;\">Mode 2:</span> This mode is for detached binaries with no constraints on the potentials. The only constraint is that the secondary luminosity, L2, is computed from the other parameters via the specified radiation prescription (blackbody or stellar atmosphere).</p><p><span style=\" font-weight:600;\">Mode 3:</span> This mode is for overcontact binaries and is like mode 1 except that the constraints on g2, T2, A2, x2, and y2 are not applied. The other two mode 1 constraints (on Ω1 and L2) are applied in mode 3, but T2, A2, g2, x2, and y2 are free.</p><p><span style=\" font-weight:600;\">Mode 4:</span> This mode is for semi-detached binaries with star 1 accurately filling its limiting lobe, which is the classical Roche lobe for synchronous rotation and a circular orbit, but differs from the classical Roche lobe for non-synchronous and eccentric cases.</p><p><span style=\" font-weight:600;\">Mode 5:</span> The same as mode 4, except that it is star 2 that fills its limiting lobe. This is the usual mode for Algol-type binaries.</p><p><span style=\" font-weight:600;\">Mode 6:</span> This mode is for double contact binaries, in which both stars accurately fill their limiting lobes. Astrophysically this makes sense only if at least one of the stars rotates non-synchronously. Mode 6 applies the surface potential constraints of modes 4 and 5 together.</p><p><br/></p></body></html>", None))
        self.label_48.setText(_translate("MainWindow", "Operation Mode [MODE]", None))
        self.mode_combobox.setItemText(0, _translate("MainWindow", "Mode -1", None))
        self.mode_combobox.setItemText(1, _translate("MainWindow", "Mode 0", None))
        self.mode_combobox.setItemText(2, _translate("MainWindow", "Mode 1", None))
        self.mode_combobox.setItemText(3, _translate("MainWindow", "Mode 2", None))
        self.mode_combobox.setItemText(4, _translate("MainWindow", "Mode 3", None))
        self.mode_combobox.setItemText(5, _translate("MainWindow", "Mode 4", None))
        self.mode_combobox.setItemText(6, _translate("MainWindow", "Mode 5", None))
        self.mode_combobox.setItemText(7, _translate("MainWindow", "Mode 6", None))
        self.whatsthis_btn.setText(_translate("MainWindow", "?", None))
        self.export_btn.setText(_translate("MainWindow", "Export dcin.active", None))

