# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfaces/wd_spotconfigurewidget.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_SpotConfigureWidget(object):
    def setupUi(self, SpotConfigureWidget):
        SpotConfigureWidget.setObjectName(_fromUtf8("SpotConfigureWidget"))
        SpotConfigureWidget.resize(920, 200)
        SpotConfigureWidget.setMinimumSize(QtCore.QSize(920, 200))
        SpotConfigureWidget.setMaximumSize(QtCore.QSize(920, 200))
        self.label = QtGui.QLabel(SpotConfigureWidget)
        self.label.setGeometry(QtCore.QRect(410, 100, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.line = QtGui.QFrame(SpotConfigureWidget)
        self.line.setGeometry(QtCore.QRect(60, 102, 321, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.label_70 = QtGui.QLabel(SpotConfigureWidget)
        self.label_70.setGeometry(QtCore.QRect(120, 130, 51, 16))
        self.label_70.setObjectName(_fromUtf8("label_70"))
        self.label_76 = QtGui.QLabel(SpotConfigureWidget)
        self.label_76.setGeometry(QtCore.QRect(330, 130, 51, 16))
        self.label_76.setObjectName(_fromUtf8("label_76"))
        self.label_74 = QtGui.QLabel(SpotConfigureWidget)
        self.label_74.setGeometry(QtCore.QRect(190, 130, 51, 16))
        self.label_74.setObjectName(_fromUtf8("label_74"))
        self.label_75 = QtGui.QLabel(SpotConfigureWidget)
        self.label_75.setGeometry(QtCore.QRect(260, 130, 51, 16))
        self.label_75.setObjectName(_fromUtf8("label_75"))
        self.label_71 = QtGui.QLabel(SpotConfigureWidget)
        self.label_71.setGeometry(QtCore.QRect(62, 130, 16, 16))
        self.label_71.setObjectName(_fromUtf8("label_71"))
        self.line_2 = QtGui.QFrame(SpotConfigureWidget)
        self.line_2.setGeometry(QtCore.QRect(540, 102, 321, 20))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.line_3 = QtGui.QFrame(SpotConfigureWidget)
        self.line_3.setGeometry(QtCore.QRect(441, 130, 41, 61))
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.spotconfigsave_btn = QtGui.QPushButton(SpotConfigureWidget)
        self.spotconfigsave_btn.setGeometry(QtCore.QRect(760, 20, 150, 30))
        self.spotconfigsave_btn.setObjectName(_fromUtf8("spotconfigsave_btn"))
        self.spotconfigload_btn = QtGui.QPushButton(SpotConfigureWidget)
        self.spotconfigload_btn.setGeometry(QtCore.QRect(760, 60, 150, 30))
        self.spotconfigload_btn.setObjectName(_fromUtf8("spotconfigload_btn"))
        self.label_2 = QtGui.QLabel(SpotConfigureWidget)
        self.label_2.setGeometry(QtCore.QRect(10, 100, 41, 21))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(SpotConfigureWidget)
        self.label_3.setGeometry(QtCore.QRect(880, 100, 41, 21))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(SpotConfigureWidget)
        self.label_4.setGeometry(QtCore.QRect(10, 130, 16, 21))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_72 = QtGui.QLabel(SpotConfigureWidget)
        self.label_72.setGeometry(QtCore.QRect(93, 130, 16, 16))
        self.label_72.setObjectName(_fromUtf8("label_72"))
        self.label_77 = QtGui.QLabel(SpotConfigureWidget)
        self.label_77.setGeometry(QtCore.QRect(790, 130, 51, 16))
        self.label_77.setObjectName(_fromUtf8("label_77"))
        self.label_78 = QtGui.QLabel(SpotConfigureWidget)
        self.label_78.setGeometry(QtCore.QRect(650, 130, 51, 16))
        self.label_78.setObjectName(_fromUtf8("label_78"))
        self.label_73 = QtGui.QLabel(SpotConfigureWidget)
        self.label_73.setGeometry(QtCore.QRect(522, 130, 16, 16))
        self.label_73.setObjectName(_fromUtf8("label_73"))
        self.label_8 = QtGui.QLabel(SpotConfigureWidget)
        self.label_8.setGeometry(QtCore.QRect(470, 130, 16, 21))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_79 = QtGui.QLabel(SpotConfigureWidget)
        self.label_79.setGeometry(QtCore.QRect(720, 130, 51, 16))
        self.label_79.setObjectName(_fromUtf8("label_79"))
        self.label_80 = QtGui.QLabel(SpotConfigureWidget)
        self.label_80.setGeometry(QtCore.QRect(553, 130, 16, 16))
        self.label_80.setObjectName(_fromUtf8("label_80"))
        self.label_81 = QtGui.QLabel(SpotConfigureWidget)
        self.label_81.setGeometry(QtCore.QRect(580, 130, 51, 16))
        self.label_81.setObjectName(_fromUtf8("label_81"))
        self.addspot2_btn = QtGui.QPushButton(SpotConfigureWidget)
        self.addspot2_btn.setGeometry(QtCore.QRect(469, 160, 442, 25))
        self.addspot2_btn.setObjectName(_fromUtf8("addspot2_btn"))
        self.spotconfigsave_label = QtGui.QLabel(SpotConfigureWidget)
        self.spotconfigsave_label.setGeometry(QtCore.QRect(20, 20, 731, 30))
        self.spotconfigsave_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spotconfigsave_label.setObjectName(_fromUtf8("spotconfigsave_label"))
        self.spotconfigload_label = QtGui.QLabel(SpotConfigureWidget)
        self.spotconfigload_label.setGeometry(QtCore.QRect(20, 60, 731, 30))
        self.spotconfigload_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spotconfigload_label.setObjectName(_fromUtf8("spotconfigload_label"))
        self.addspot1_btn = QtGui.QPushButton(SpotConfigureWidget)
        self.addspot1_btn.setGeometry(QtCore.QRect(10, 160, 442, 25))
        self.addspot1_btn.setMinimumSize(QtCore.QSize(0, 0))
        self.addspot1_btn.setObjectName(_fromUtf8("addspot1_btn"))

        self.retranslateUi(SpotConfigureWidget)
        QtCore.QMetaObject.connectSlotsByName(SpotConfigureWidget)

    def retranslateUi(self, SpotConfigureWidget):
        SpotConfigureWidget.setWindowTitle(_translate("SpotConfigureWidget", "Configure Spots", None))
        self.label.setText(_translate("SpotConfigureWidget", "Add or Remove Spots", None))
        self.label_70.setToolTip(_translate("SpotConfigureWidget", "Spot latitude", None))
        self.label_70.setText(_translate("SpotConfigureWidget", "LAT", None))
        self.label_76.setToolTip(_translate("SpotConfigureWidget", "Ratio of local spot temperature to local temperature without the spot", None))
        self.label_76.setText(_translate("SpotConfigureWidget", "TEMSP", None))
        self.label_74.setToolTip(_translate("SpotConfigureWidget", "Spot longitude", None))
        self.label_74.setText(_translate("SpotConfigureWidget", "LON", None))
        self.label_75.setToolTip(_translate("SpotConfigureWidget", "The angular radius of a star spot, in radians", None))
        self.label_75.setText(_translate("SpotConfigureWidget", "RADSP", None))
        self.label_71.setToolTip(_translate("SpotConfigureWidget", "Set spot for A", None))
        self.label_71.setText(_translate("SpotConfigureWidget", "A", None))
        self.spotconfigsave_btn.setText(_translate("SpotConfigureWidget", "Save Spot Configuration", None))
        self.spotconfigload_btn.setText(_translate("SpotConfigureWidget", "Load Spot Configuration", None))
        self.label_2.setText(_translate("SpotConfigureWidget", "Star 1", None))
        self.label_3.setText(_translate("SpotConfigureWidget", "Star 2", None))
        self.label_4.setText(_translate("SpotConfigureWidget", "#", None))
        self.label_72.setToolTip(_translate("SpotConfigureWidget", "Set spot for B", None))
        self.label_72.setText(_translate("SpotConfigureWidget", "B", None))
        self.label_77.setToolTip(_translate("SpotConfigureWidget", "Ratio of local spot temperature to local temperature without the spot", None))
        self.label_77.setText(_translate("SpotConfigureWidget", "TEMSP", None))
        self.label_78.setToolTip(_translate("SpotConfigureWidget", "Spot longitude", None))
        self.label_78.setText(_translate("SpotConfigureWidget", "LON", None))
        self.label_73.setToolTip(_translate("SpotConfigureWidget", "Set spot for A", None))
        self.label_73.setText(_translate("SpotConfigureWidget", "A", None))
        self.label_8.setText(_translate("SpotConfigureWidget", "#", None))
        self.label_79.setToolTip(_translate("SpotConfigureWidget", "The angular radius of a star spot, in radians", None))
        self.label_79.setText(_translate("SpotConfigureWidget", "RADSP", None))
        self.label_80.setToolTip(_translate("SpotConfigureWidget", "Set spot for B", None))
        self.label_80.setText(_translate("SpotConfigureWidget", "B", None))
        self.label_81.setToolTip(_translate("SpotConfigureWidget", "Spot latitude", None))
        self.label_81.setText(_translate("SpotConfigureWidget", "LAT", None))
        self.addspot2_btn.setText(_translate("SpotConfigureWidget", "Add Spot", None))
        self.spotconfigsave_label.setText(_translate("SpotConfigureWidget", "Save your current configuration.", None))
        self.spotconfigload_label.setText(_translate("SpotConfigureWidget", "Load previously saved configuration.", None))
        self.addspot1_btn.setText(_translate("SpotConfigureWidget", "Add Spot", None))

